### ISSUE TITLE
Automatically choose IPv6 by default if vhost6 is specified

### ISSUE THREAD

**Issue by TehPeGaSuS** [eggheads/eggdrop#1008]
Right now, users must set `set prefer-ipv6` to 1 in order to make eggdrop to forcefully use IPv6 connection, even if there's a `set vhost6` specified.
It would be nice, if when there's a `set vhost6` set, eggdrop would firstly try to connect via IPv6, falling back to IPv4 if there's no IPv6 connectivity (no IPv6 support, etc).
Small joke with code:
`if {[info exists vhost6]} { try IPv6 } else { try IPv4 }` :P

Cheers

**Comment by vanosg** [comment]
This is an intended feature for users who use both stacks, that is the point of the prefer-ipv6 setting. If you want to use ipv6, then set this to 1.
