### ISSUE TITLE
DNS module seems to not be able to process hostname "aliases"

### ISSUE THREAD

**Issue by TehPeGaSuS** [eggheads/eggdrop#1011]
Latest develop branch tested and I had the following issues when trying to connect to Freenode and Geekshed:

### With DNS module loaded
**Freenode connection**
```
[20:11:51] Trying server irc.freenode.net:+6697
[20:12:33] Failed connect to irc.freenode.net (DNS lookup failed)
```
**Geekshed connection**
```
[20:13:51] Trying server irc.geekshed.net:+6697
[20:14:33] Failed connect to irc.geekshed.net (DNS lookup failed)
```
### HOST command from terminal
**Freenode**
```
irc.freenode.net is an alias for chat.freenode.net.
chat.freenode.net has address 38.229.70.22
chat.freenode.net has address 185.30.166.37
chat.freenode.net has address 204.225.96.251
chat.freenode.net has address 82.96.96.11
chat.freenode.net has address 192.186.157.43
chat.freenode.net has IPv6 address 2001:5a0:3604:1:64:86:243:181
chat.freenode.net has IPv6 address 2a01:270:0:666f::1
chat.freenode.net has IPv6 address 2001:5a0:40:50:66:110:9:37
```
**Geekshed**
```
irc.geekshed.net is an alias for eu.geekshed.net.
eu.geekshed.net has address 188.166.72.15
```

As it can be seen, irc.freenode.net and irc.geekshed.net are `aliases` to chat.freenode.net and eu.geekshed.net respectively.

Somehow, the DNS module seems to not respect/process that.

Commenting the `loadmodule dns` line in the eggdrop.conf makes the above connections work at the 1st attempt.

**Comment by vanosg** [comment]
This is the standard 'unload dns module', referenced in #362. Flush DNS cache and paste the raw logs so we can see what dns responses are being given.

**Comment by michaelortmann** [comment]
if `loadmodule dns` is commented out, eggdrop core will use libc functions getaddrinfo(3), gethostbyname(3) which will use HOSTALIASES, see hostname(7).

but if eggdrop dns module is used, those functions wont be used.

@Geo: HOSTALIASES are like /etc/hosts, not part of dns protocol / server and are currently, like /etc/hosts, not implemented in eggdrop dns module.

If you dont stop me, i would like to implement HOSTALIASES for eggdrop dns mod, like i did did for /etc/hosts with pending #701, but in a new PR.

Im looking forward for rewiewing / merging of #701, so it wont overlap with this new PR.

**Comment by TehPeGaSuS** [comment]
Bot was stopped since yesterday.
Raw logs are enabled and the file is only saving `drv` flags:

**With DNS module loaded (failed connection):**
https://termbin.com/uhag

**Without DNS module loaded (successful connection):**
https://termbin.com/u5pz

If you need something more specific, let me know the exact commands you want me to do.

Cheers!

**Comment by michaelortmann** [comment]
Thank you PeGaSuS-Coder, so its not the HOSTALIASES issue, but the CNAME issue. Time to investigate.

**Comment by michaelortmann** [comment]
Meanwhile fixed by one of the dns mod PRs merged.

**Comment by TehPeGaSuS** [comment]
From my tests all seems to be working properly with the DNS module loaded now.
Specified `irc.freenode.net` as server and bot connected successfully to `hitchcock.freenode.net`.

**Comment by TehPeGaSuS** [comment]
Closing, as this is already fixed by some of the DNS mod PRs.
