### ISSUE TITLE
Build issue (link) with -fno-common

### ISSUE THREAD

**Issue by dbaio** [eggheads/eggdrop#1023]
Hi.

Issue appeared on FreeBSD HEAD.

LLVM/Clang 11 and GCC 10 has switched to use -fno-common by default.

More info:
[Clang modified-compiler-flags](https://github.com/llvm/llvm-project/blob/llvmorg-11.0.0-rc2/clang/docs/ReleaseNotes.rst#modified-compiler-flags)
[GCC porting](https://gcc.gnu.org/gcc-10/porting_to.html)
[GCC changes](https://gcc.gnu.org/gcc-10/changes.html)

Build issue:
```
---------- Yeah! That's the compiling, now the linking! ----------

Linking eggdrop (debug build).

cc -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -pipe -Wall -I.. -I.. -I/usr/include -DHAVE_CONFIG_H -g3 -DDEBUG -DDEBUG_ASSERT -DDEBUG_MEM -DDEBUG_DNS -o ../eggdrop bg.o botcmd.o botmsg.o botnet.o chanprog.o cmds.o dcc.o  dccutil.o dns.o flags.o language.o match.o main.o mem.o misc.o misc_file.o  modules.o net.o rfc1459.o tcl.o tcldcc.o tclhash.o tclmisc.o tcluser.o  tls.o userent.o userrec.o users.o  -L/usr/lib -L/usr/local/lib -ltcl86 -lm -lpthread -lz -lssl -lcrypto md5/md5c.o compat/*.o `cat mod/mod.xlibs`
ld: error: duplicate symbol: userfile
>>> defined at userrec.c:47
>>>            userrec.o:(userfile)
>>> defined at users.c:49
>>>            users.o:(.bss+0x0)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1
```

**Comment by vanosg** [comment]
Thanks for the report, dbaio, its always great to get feedback like this. What version did you find this on? Have you tried it on the current development branch? If not, could you try grabbing that (clone this repo) and let us know how it goes. Thanks!

**Comment by michaelortmann** [comment]
Probably fixed by #912

**Comment by dbaio** [comment]
Oh, we were very behind, on 4622c0c.
It's building fine with 48f236a (latest commit).
Thanks and sorry for the noise.

**Comment by vanosg** [comment]
This is noise we like to have, an engaged user! :) Thank you very much for getting back to us.

**Comment by michaelortmann** [comment]
btw: latest commit is ddcf4d0bb029bcbab5cad95626a5fcd10e02224a instead of 48f236add077d7207e8fa649d026551acd961acb
