### ISSUE TITLE
Eggdrop crashing on ubuntu after joining chan

### ISSUE THREAD

**Issue by noipstream** [eggheads/eggdrop#1024]
(Eggdrop v1.9.0+newcaps (C) 1997 Robey Pointer (C) 2010-2020 Eggheads) 

* Last context: tclhash.c/734 [Tcl proc: *raw:irc:315, param:  $_raw1 $_raw2 $_raw3]
* Please REPORT this BUG!
* Check doc/BUG-REPORT on how to do so.
* Wrote DEBUG
* SEGMENT VIOLATION -- CRASHING!
Connection closed by foreign host.

**Comment by vanosg** [comment]
Hi @noipstream, thanks for reporting this. Is it possible you have a Tcl script loaded that could be causing this? Please unload all Tcl scripts from your config, then try again. If it still crashes, let us know and I'll give you some additional troubleshooting steps. Thanks!
