### ISSUE TITLE
IRCnet allows 64 bans since 2.11.2/2008

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#108]
| Trac | Data |
| --: | :-- |
| Ticket | 108 |
| Reported by | mw |
| Status | assigned |
| Component | Core |
| Priority | major |
| Milestone | 1.8.0 |
| Version | 1.8.0 CVS |

Change max-bans/max-modes for the net-type accordingly.

Patch attached.

**Comment by thommey** [comment]
**Comment by mw**
Since trac currently reports an internal error when I try to attach a file, you may find the patch here instead: http://barfooze.de/stuff/diff/eggdrop1.8-ircnet-banlist.diff

**Comment by thommey** [comment]
**Comment by mw**
See here for the corresponding commit to the IRCnet ircd code: https://github.com/ircnet/irc/commit/4fd213be0506f080219eb9408eeffba43d93ed31

**Comment by vanosg** [comment]
This was already merged, 05362f9476e08b5f9a0c709e0484042b1d26a801
Closing.
