### ISSUE TITLE
.BOTATTR behavior when channel names are specified with global flags (other than +s/+p)

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#111]
| Trac | Data |
| --: | :-- |
| Ticket | 111 |
| Reported by | Domino |
| Status | reopened |
| Component | Core |
| Priority | minor |
| Milestone | 1.8.0 |
| Keywords | botattr |
| Version | 1.8.0 CVS |

When you ".botattr <target bot> <+s or +p> <channel>" the flag will apply to the appropriate channel.

When you use any other flag (h, a, l, r, i; 0-9), use of the channel name in the syntax will remove all flags from the bot record!

[2015-04-10 19:10:34 -0700]
[19:10] <Domino> .botattr Hub +hi
[19:10] <Bot> #Domino# botattr Hub +hi
[19:10] <Bot> Bot flags for Hub are now +hi.
Correct, of course (these are global flags)

[19:10] <Domino> .botattr Hub +hi #MyChannel
[19:10] <Bot> #Domino# botattr Hub +hi
[19:10] <Bot> There are no bot flags for Hub on #MyChannel.

(".WHOIS" verifies the result both times.)

When a global flag (all but p/s) is used, the result should just be applied to the global flag setting (i.e. ignore the channel designation). This might _visually_ confuse a script debugger in the case of "+g" (e.g. ".botattr Bot +g #MyChannel"), but, if there's a consistent rule, it shouldn't matter.

**Comment by thommey** [comment]
**Comment by Domino**
The issue listed above is NOT the problem I meant to report. Trac won't let me alter the text.

The actual issue is: the flags, even though being turn ON (+hi), are still "removed" from the channel record. Since they're global flags, it sorta makes sense they're not applied (and even "removed") from the channel.

I suggest that this behavior is changed to, instead, apply the flags globally since they are global flags. (This means: ignore the specified channel / pretend it was never specified): ".botattr Hub +hi"

**Comment by vanosg** [comment]
This appears to be desired functionality- if the user types .bottattr testbot +hi #channel, the bot should not instead choose to apply them as global flags. No flags are removed, as they were never applied. They are just not applied. The bot, correctly, states the current flags set for the channel.
