### ISSUE TITLE
addserver/delserver/$::server notice

### ISSUE THREAD

**Issue by ZarTek-Creole** [eggheads/eggdrop#1110]
Add addserver and delserver command : https://github.com/eggheads/eggdrop/commit/86ee5dd999441ee7008e3219aca7c51a289ba06c

I find the addition of these two locations very good. I still have a few opinions on it.

First thing is a bug:
`wrong # args: should be "addserverserver ?port? ?pass?"`
**addserver**server to addserver 

`wrong # args: should be "delserverserver, ?port?"` 
also a double "server"

I'm not on arguments :
good is not : `addserver ?ip/host? ?port? ?password?` and `delserver ?ip/host? ?port? ?password?`

I would have hoped to see something similar to [channel-commands](https://github.com/eggheads/eggdrop/blob/develop/doc/sphinx_source/mainDocs/tcl-commands.rst#channel-commands)

**SERVERS COMMANDS**
**server add <ip/host> [port] [password]**
Description: adds a server record for the bot. The full list of possible options are given in doc/settings/mod.server. 
Returns: nothing
Module: servers

**server remove <ip/host> [port] [password**
Description: removes a channel record from the bot
Returns: nothing
Module: servers

**saveservers**
Description: saves the serversettings to the server-file if one is defined.
Returns: nothing
Module: servers

**loadservers**
Description: reloads the server settings from the server-file if one is defined.
Returns: nothing
Module: servers

**servers**
Returns: a list of the serversthe bot has a servers record for
Module: servers

**SERVERS MODULE**

There are also some variables you can set in your config file:
set serverfile "LamestBot.srv"

server add ip/host port password
      Add each static server you want your bot to sit in using this
      command. 

**FILE SERVER**
```
#Dynamic Server File for LamestBot (eggdrop v1.9.0) -- written Fri Jan 29 23:00:00 2021

server add 127.0.0.1 +6669
server add 127.0.0.1 6667 MyPassword
server add localhost 6667 MyPassword
```

**Comment by vanosg** [comment]
Thanks for the feedback, I've put together a PR that implements parts of this. I don't know that we'll go as far as a server file, but I do agree the syntax makes sense to be changed.

Also, in case you were not aware, the server list is (and has been) stored in the $servers variable, so you can use that at any time in a script to retrieve what servers your Eggdrop is tracking via Tcl

Thanks again for taking the time to write this up!

**Comment by ZarTek-Creole** [comment]
A very good job done in the PR. Thanks for this. I understand that a server file involves some code changes for "just" one file. I had to indicate this implementation to follow the logic (in my opinion) and also because its makes it more extensible for the saving of the modifications made in a script or / and in partyline. it is a major asset.
