### ISSUE TITLE
List the servers add with "server add"

### ISSUE THREAD

**Issue by ZarTek-Creole** [eggheads/eggdrop#1131]
with commit 59d1b044f2cbacf20c5f2425922a7ae3918fc9bd

Comment: the syntax is "server add <ip/host> [[+]port [password]]", it is OK.
To list the servers I exec [servers], the command does not exist.

I have returned the variables ${::servers} and $ {::server}; the result received was not that expected.
**${::servers}**
`{127.0.0.1:+50000:PassWorD  irc.xxx.net}`

**${::server}**
`irc.xxx.net:+50000`

in my .conf file
`server add 127.0.0.1 +50000 PassWorD`

expected result :
**${::servers}/[servers]**
{127.0.0.1 +50000 PassWorD}

I changed my .conf file to get the results with two servers: 
```
server add 127.0.0.1 +50000 PassWorD
server add localhost +50500
```
**${::servers}**
`{127.0.0.1:+50000:PassWorD  irc.xxx.net} {localhost:+50500 }`

expected result :
**${::servers}/[servers]**
`{127.0.0.1 +50000 PassWorD} {localhost +50500 {}}`

My personal end goal is to have the value initially add to the server and be able to do something like:
```
foreach {s_host s_port s_password} [servers] {
    putbot mybot "send_sever_add $s_host $s_port $s_password"
}
```

**Comment by vanosg** [comment]
We can look into this; but is there a reason the code you pasted wouldn't work? I think $s_password should evaluate the same either way (with nothing, or with {})

**Comment by ZarTek-Creole** [comment]
> We can look into this; but is there a reason the code you pasted wouldn't work? I think $s_password should evaluate the same either way (with nothing, or with {})

Yes, there are even several reasons. The output of $servers does not follow a correct tcl list.
watch : `{127.0.0.1:+50000:PassWorD irc.xxx.net} {localhost:+50500 } {barjavel.freenode.net:+6697:nopassword }`

What is irc.xxx.net in the output? on behalf of IRC to recover by CAPS feature? it is to say that it is to connect on that one?

The output should respect the length of the list like this: `{127.0.0.1:+50000:PassWorD irc.xxx.net} {localhost:+50500 {}} {barjavel.freenode.net:+6697:nopassword {}}`

test:
```
.tcl foreach { server_addr server_name } $::servers { putnow  "$server_addr $server_name" }
127.0.0.1:+50000:PassWorD irc.xxx.net irc.xxx.net localhost:+50500
barjavel.freenode.net:+6697:nopassword

```

**during a rehash the irc.xxx.net disappears?!**

```
.tcl return $::servers
{127.0.0.1:+50000:PassWorD irc.xxx.net} {localhost:+50500 } {barjavel.freenode.net:+6697:nopassword }
.tcl rehash
.tcl return $::servers
{127.0.0.1:+50000:PassWorD } {localhost:+50500 } {barjavel.freenode.net:+6697:nopassword }
```

test after rehash:
```
.tcl foreach { server_addr server_name } $::servers { putnow  "$server_addr $server_name" }
127.0.0.1:+50000:PassWorD  localhost:+50500
barjavel.freenode.net:+6697:nopassword
}
```
The list is poorly constructed, all of this is confusing.

https://github.com/eggheads/eggdrop/blob/746dacd1cff0bc9bbe3c32597ba4f06f9f6dbf7a/src/mod/server.mod/server.c#L1670

I think the construction of the serverlist was patched "quickly" to be compatible with the new old fashioned syntax. It should be built to be the new syntax. If for some reason the old syntax should still work, is this one to be modified to the new one, not the other way around?

**Comment by vanosg** [comment]
Are you combining three issues here into one? The title of the post doesn't seem to match either how $servers is populated, nor the persistence of the list. You may be better served having a conversation about this in #eggdrop rather than trying to work through it here

**Comment by ZarTek-Creole** [comment]
I realize that my thread is unclear.
I will hope for a clean [servers], there is now [server list] since #1200.

The real topic of this thread is that the $: servers variable returns disturbing in the output format and lengths of list.

An expected result would be:
`{HOST PORT PASSWORD IRCNAME}`
Only HOST :
`{127.0.0.1 {} {} {}}`
HOST+ PORT SSL
`{127.0.0.1 +50000 {} {}}`
HOST+ PORT WITHOUT SSL
`{127.0.0.1 50000 {} {}}`
HOST+ PORT SSL + ircname
`{127.0.0.1 +50000 {} {irc.xxx.net}}`
HOST+ PORT SSL + ircname + password
`{127.0.0.1 +50000 {PassWorD} {irc.xxx.net}}`
HOST+ PORT SSL  + password
`{127.0.0.1 +50000 {PassWorD } {}}`
....
Multi servers :
`{{127.0.0.1 {} {} {}} {127.0.0.1 +50000 {} {}} {127.0.0.1 50000 {} {}} {127.0.0.1 +50000 {} {irc.xxx.net}} {127.0.0.1 +50000 {PassWorD} {irc.xxx.net}} {127.0.0.1 +50000 {PassWorD } {}}}`
