### ISSUE TITLE
catch exec -- eggdrop = error?

### ISSUE THREAD

**Issue by ZarTek-Creole** [eggheads/eggdrop#1145]
I'm running with TCL: 
```
.tcl if {[ catch { set OK [exec /bin/sh -c /home/eggdrop/eggdrop eggdrop2.conf] } ERR_MSG] } { return "err: $ERR_MSG" }
> err: 
Eggdrop v1.9.0 (C) 1997 Robey Pointer (C) 1999-2021 Eggheads
--- Loading eggdrop v1.9.0 (Wed Mar 17 2021)
Module loaded: blowfish
...
```
The eggdrop2.conf launches fine but the catch exec thinks there is an error.  because the variable $OK is empty but $ERR_MSG contains "Eggdrop v1.9.0 (C) 1997 Robey ..."
Does the eggdrop send an error signal when it is good or is it catch that does not work badly?

**Comment by vanosg** [comment]
Answered in channel; please use the channel for troubleshooting scripts. Thanks!

(The issue was only setting a result var, not an error var)
