### ISSUE TITLE
DOC: .fprint -

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#1148]
`.fprint -` will remove a fingerprint.

1. I expected eggdrop to say "Removed fingerprint."

But instead eggdrop says `Changed fingerprint to '-'.`

2. `.help fprint` does not mention "-" as a way to remove the fingerprint.

3. `.help chfinger` does mention "Not specifying a value for 'fingerprint' will remove"

but it does not mention that a value of `"-"` does also remove.

Somehow `.fprint`, `.chfinger` and the help strings for those functions are not consistent.

**Comment by vanosg** [comment]
Why do we think a '-' removes the fingerprint? It looks like it set the fprint to '-' as you told it to. I don't see any reference in code or docs that makes me think specifying a '-' should remove the fingerprint

**Comment by michaelortmann** [comment]
Because it does.

`.fprint` - will remove a fingerprint:

```
.fprint 1234AB
[05:43:07] tcl: builtin dcc call: *dcc:fprint testuser 1 1234AB
[05:43:07] #testuser# fprint...
Changed fingerprint to '1234AB'.
.save
```

eggdrop.user:
```
[...]
testuser   - efjlmnoptuvx            
--FPRINT 12:34:AB
[...]
```

```
.fprint -
[05:43:24] tcl: builtin dcc call: *dcc:fprint testuser 1 -
[05:43:24] #testuser# fprint...
Changed fingerprint to '-'.
.save
```

eggdrop.user:
```
[...]
testuser   - efjlmnoptuvx        
[...]
```

see:
https://github.com/eggheads/eggdrop/blob/1fb5875f9a8a00722bdf37ec2bd6ca3715a80ea9/src/userent.c#L1394-L1399
