### ISSUE TITLE
file dns.help

### ISSUE THREAD

**Issue by carlin0** [eggheads/eggdrop#1149]
Is this file correct? 

`%{help=server module}%{+n}
###  %bdns module%b
   This module provides support for asynchronous DNS queries.
   This guards the bot from blocking several seconds while
   resolving IP addresses or hostnames.

   Config file variables for configuring the server module:
     %bdns-retrydelay%b    %bdns-maxsends%b    %bdns-servers%b
     %bdns-negcache%b      %bdns-cache%b

   (Use %b'.help set <variable>'%b for more info)`

Why does the server module wrote instead of the DNS module?

**Comment by vanosg** [comment]
Because we love to copy and paste from other files :) Thank you for the catch!
