### ISSUE TITLE
Share bots

### ISSUE THREAD

**Issue by carlin0** [eggheads/eggdrop#1151]
Can anyone confirm that it is the passive bot to send the user file to the active bot?
That is the exact opposite of what was written in the Eggdrop's help

**Comment by vanosg** [comment]
Hi @carlin0 which file are you referencing on this? Thanks

**Comment by carlin0** [comment]
It is written both in the cmds2.help file under "help whois" than in the share.help file

**Comment by vanosg** [comment]
Can you point out the lines you're talking about? All I see are references for the hub/active bot to send to the passive/leaf bot:
```
        The active bot will SEND a userfile to the passive bot. %bThe passive%b
        %bbot's userfile will be overwritten.%b We shall call the %bACTIVE%b bot
        "A", and the %bPASSIVE%b bot B.
```
And this is correct. What line is giving you the idea that a passive bot sends to an active bot?

**Comment by carlin0** [comment]
When linking 2 bots between them and the userfile exchange takes place, i read in the partyline:

in that of the passive bot (the one with the flag +p) "I send the user file to ..."

and in that of the active bot (the one with the flag +s) "userfile received from .." 

Do you read the opposite? it seems strange ...

**Comment by vanosg** [comment]
Can you paste a log of what you're seeing?

**Comment by carlin0** [comment]
it is enough that you try to link 2 share bot to see who you send and those who receive

**Comment by carlin0** [comment]
it is enough that you try to link 2 share bot to see who you send and those who receive

**Comment by carlin0** [comment]
it is enough that you try to link 2 share bot to see who send and those who receive

**Comment by vanosg** [comment]
I can't see the issue that you are referring to. If you can paste an exact log we can look at the exact line you're referencing, but when I link bots everything looks fine to me when I do it on my own. A pasted log will show the exact issue and we can both look at the same output to determine what the issue is, if any. Thanks
