### ISSUE TITLE
Eggdrop doesn't finsish DNS resolving an incoming telnet connection

### ISSUE THREAD

**Issue by DasBrain** [eggheads/eggdrop#1174]
As user, you won't see any password prompt, but the telnet connection is established.  
User input is ignored, no banner is shown.

When the connection is closed by the client (Ctrl++, Q), then a "Lost connection while resolving hostname" line will be logged.

Log from my bot with `.console +d`

```
<BrainBot> [06:15:15] net: connect! sock 4
<BrainBot> [06:15:26] net: eof!(read) socket 7
<BrainBot> [06:15:26] Lost connection while resolving hostname [1.2.3.4/52680]
```

(IP redacted.)

This happens spontaneously, no known way to reproduce.  
It also sometimes fixes itself.

Eggdrop version: 1.9.0, dns module, no tdns.

**Comment by vanosg** [comment]
Reference #1175

**Comment by ERR1R** [comment]
i have the exact same issue.. after a while i get this:

Lost connection while resolving hostname [1.2.3.4/52680]

 When i connect multiple times with putty, the connection comes back and everything works again. 
When i run putty just once nothing happens (times out)

**Comment by Lord255** [comment]
try set
`set resolve-timeout 0`

```
# Set here the amount of seconds before giving up on hostname/address lookup
# (you might want to increase this if you are on a slow network). The default is
# RES_TIMEOUT, which is generally 5, the allowed maximum is RES_MAXRETRANS (see
# <resolv.h>).
#set resolve-timeout 5
set resolve-timeout 0
```

**Comment by crazycatdevs** [comment]
Short comment: the proposed solution doesn't work for me.
My eggdrops (1.9.1) doesn't respond to a telnet when they run for a certain time (unable to say how much, less than 1 hour).

Only one doesn't reproduce the bug, but it's on a raspberry (raspbien / home eggdrop). All others (debian / 2 different shells) have the bug, no matter if they are on a botnet or not.

**Comment by vanosg** [comment]
Has anyone seen this behavior in an eggdrop running tdns, or without the DNS module? If, no, I'm going to close this issue, we believe is fixed with the tdns capability.

**Comment by crazycatdevs** [comment]
I forget to coment the loadmodule dns on my eggdrops 1.9.2.
I just did it, will answer you tomorrow (usually, 24h is largely enough to get the bug)

**Edit**: the bug alway exists with eggdrop 1.9.2 and Threaded DNS core enabled
