### ISSUE TITLE
[FR] +R reop mode/list for IRCnet

### ISSUE THREAD

**Issue by wilkowy** [eggheads/eggdrop#1177]
On IRCnet there is +R channel list similar to b/e/I lists.

Idea behind R is to:
- when channel is opless - server will op one user matching any +R entry after some time
- when channel is opless - server will allow user to join channel overriding channel limit if it matches any +R entry

Currently adding any +R entry will cause such incorrect messages (haven't noticed invalid behavior): `[30/13:15:00] @#***** (+Rtnl 52) : [m/46 o/9 h/0 v/10 n/27 b/12 e/9 I/9]`

Articles:
- https://www.ircnet.com/articles/reop
- https://ircnet.barfooze.de/articles/reop/

**Comment by Lord255** [comment]
see: https://github.com/eggheads/eggdrop/issues/923

**Comment by vanosg** [comment]
If this is different than #923 then we can reopen, but otherwise lets move discussion there. Thanks!
