### ISSUE TITLE
Script dont work after update to 1.9.1

### ISSUE THREAD

**Issue by mkgeeky** [eggheads/eggdrop#1182]
After I have updated to 1.9.1 this script does not work anymore. It's have worked perfect with previous versions. Can you take me in the right direction where to fix the problem?

**The error:**
``
Tcl error in file 'eggdrop.conf':
a proc name must be specified for a script listen
    while executing
"listen $conf(port) script idle:listen"
    (file "scripts/noname.tcl" line 5)
``

**The file:**
``
set conf(port) 35789
set conf(chan) "#t"
set conf(pass) "a"

listen $conf(port) script idle:listen

proc idle:listen {idx} {
    control $idx idle:process
}

proc idle:process {idx args} {
        global conf

        set args [join $args]
    set password [lindex [split $args] 0]
    set message [join [lrange [split $args] 1 end]]

    if {[string match $password $conf(pass)]} {
        putquick "PRIVMSG $conf(chan) : $message"
    }
}

putlog "New announce script loaded!"
``

When I disable the noname.tcl - the bot starts up.

**Comment by vanosg** [comment]
What version did you update from?

**Comment by mkgeeky** [comment]
1.8.4

**Comment by vanosg** [comment]
The error doesn't match what you have above, but the first thing that seems to be missing is the <flag> argument, which should be 'pub' (https://docs.eggheads.org/mainDocs/tcl-commands.html#listen-ip-port-type-options-flag) . Is that a copy/paste issue?

**Comment by mkgeeky** [comment]
I have c/p the script from here
https://github.com/Bigjoos/U-232-V4/blob/master/announce.tcl
It have worked until I update to v1.9.1
I have looked at the URL, but cant seem to find anything with pub 🤔

søn. 25. jul. 2021 01.37 skrev Geo ***@***.***>:

**Comment by vanosg** [comment]
Good news and bad news- we still can't reproduce your exact issue, but we did find a mismatch between code, docs, and how it used to work- I'm not positive it will fix the issue you're seeing since we can't reproduce it, but maybe we'll get lucky. From that link:

> listen [ip]  \<port\> script  \<proc\> \<flag\>
>
>    Description: accepts connections which are immediately routed to a proc. The proc is called with one parameter: the idx of the new connection. If the script type is used, flag must also be set. Flag may currently only be ‘pub’, which makes the bot allow anyone to connect and not perform an ident lookup.

By setting the flag, this could remedy your issue. Otherwise, we'll likely have a patch for this put into the develop version of eggdrop, you could grab that once its in and see if that fixes your issue as well.

**Comment by vanosg** [comment]
For tracking: flag was incorrectly changed from optional to required, this needs to be reverted and docs updated to match

**Comment by mkgeeky** [comment]
Unfortunately, add proc dosen't help :(
``ircd@newhost:~/eggdrop$ ./eggdrop

Eggdrop v1.9.1 (C) 1997 Robey Pointer (C) 1999-2021 Eggheads
--- Loading eggdrop v1.9.1 (Wed Jul 28 2021)
Listening for telnet connections on XXX port 3333 (all).
Listening for telnet connections on XXX port 5555 (all).
Listening for telnet connections on XXX port 35789 (all).
Module loaded: blowfish
Module loaded: dns
Module loaded: channels
Module loaded: server
INFO: The config setting for "net-type" has transitioned from a number
to a text string. Please update your choice to one of the allowed values
listed in the current configuration file from the source directory

Module loaded: ctcp
Module loaded: irc
Module loaded: notes            (with lang support)
Module loaded: console          (with lang support)
Module loaded: uptime
own IMDb loaded
Tcl error in file 'eggdrop.conf':
missing flag. allowed flags: pub
    while executing
"listen $conf(port) script proc idle:listen"
    (file "scripts/noname.tcl" line 5)
    invoked from within
"source scripts/noname.tcl"
    (file "eggdrop.conf" line 1547)
* CONFIG FILE NOT LOADED (NOT FOUND, OR ERROR)
``

**Comment by vanosg** [comment]
You still aren't reading the docs or what I said- you need to set the FLAG. idle:listen is already the name of the proc, you should try adding a flag- which the docs tell you the only option is 'pub'
