### ISSUE TITLE
tcl for twitch

### ISSUE THREAD

**Issue by sx66627** [eggheads/eggdrop#1189]
Good day
Please tell me. I have been using a bot on mirc for 2 years.
And waited for eggdrop to finally fully support twitch. I recently installed version 1.9.1 and started writing scripts. But I immediately ran into some difficulties.
1) I need to prohibit writing messages in caps. But that would not delete messages from subs, partners and vips (isvip).
Example:
if {$user_status == 'partner'} { return; }
if {isvip ($nick)} { return; }
if {$user_status == 'subcriber'} { return; }
putserv "twcmd $chan delete $msgid";

I haven't found how to get badges yet.

2) How do I get subscription notifications from twitch?
I can see them in the console, but I don't understand how to intercept these events in tcl.

3) I need to get the id of the twitch message. To delete messages that contain bad words.
Also did not find out how to do it.

If you show an example, I will be very grateful to you.

**Comment by vanosg** [comment]
Two quick things to check- ~~first, (and we'll make this more clear or even force it), did you request the required Twitch capabilities? They are twitch.tv/tags twitch.tv/commands twitch.tv/membership . This can be done via the 'set cap-request' setting in the config, or in Tcl via ```cap req "twitch.tv/tags twitch.tv/commands twitch.tv/membership"```  This will enable the Eggdrop to see the messages.~~  (we force these modes by default when loading the twitch module, you can ignore this)


For 1 and 3, it is the same answer (and thank you for pointing this out, we may need to add a better/simpler way to do this). 
```
bind rawt * PRIVMSG foo

proc foo {from key text tag} {
putlog "The tags for this message are: $tag"
}
```
Results in:
```
[00:23:25] The tags for this message are: badge-info {{}} badges broadcaster/1 client-nonce 32da5a17358da0367874878f7e7156e3 color #2E8B57 display-name eggdroptest emotes {{}} flags {{}} id 73c360ac-8127-4293-9f67-ac001d84c490 mod 0 room-id 470220570 subscriber 0 tmi-sent-ts 1629073405324 turbo 0 user-id 470220570 user-type {{}}
```
and then to parse, just treat it as a dict:
```
dict get $tag badges
Tcl: broadcaster/1

dict get $tag id
Tcl: 73c360ac-8127-4293-9f67-ac001d84c490
```

For your second question, can you post an example of a subscription notice? I suspect it may be similar to the same answer I've already provided here. 

It would be absolutely amazing if you were to publish your script when you were done; I have yet to see one built and I'm sure sharing your experience and expertise with the rest of the community would be much appreciated. 

Normally I would push questions like this to #eggdrop on Libera, but we are still actively seeking feedback and working through issues like this with Twitch as it is so new, so I am posting this here in the hopes it will help someone else. Please stop in to #eggdrop on Libera if you have further questions though. Thank you for your interest in Eggdrop Twitch support!

**Comment by sx66627** [comment]
Thank you very much for your answers.
Yes, I have the twitch module loaded.

An example of a subscription & other events from twitch: 
- 31 raiders from WanessaToxic have joined!
- Must_Die__ gifted a Tier 1 sub to d0mit0ri! They have given 14 Gift Subs in the channel!
- Korochyn subscribed at Tier 1. They've subscribed for 17 months!
- Happy_Dolphin subscribed at Tier 1. They've subscribed for 8 months, currently on a 8 month streak!
- ulianakarter subscribed with Twitch Prime. They've subscribed for 6 months!
- arinaa33 is continuing the Gift Sub they got from gnat0485!
- tunch1k is gifting 10 Tier 1 Subs to vika_karter's community! They've gifted a total of 50 in the channel!

This is the original text from twitch. Taken from the logs of an old bot (mirc).

And logs from eggdrop:
[17:24:04] * TWITCH: Roomstate 'followers-only' for #ilame changed to 1440
[17:24:04] * TWITCH: Roomstate 'slow' for #ilame changed to 3
[17:25:30] * TWITCH: Chat logs cleared on #ilame for user snoopidubidogg
[17:27:26] * TWITCH: thearchewolf sent a mystery gift
[17:27:27] * TWITCH: thearchewolf gifted sorcesman a subscription to the sorcesman plan
[17:27:27] * TWITCH: thearchewolf gifted amity_v_ a subscription to the amity_v_ plan
[17:27:27] * TWITCH: thearchewolf gifted schvedx a subscription to the schvedx plan

**Comment by vanosg** [comment]
To catch many of those events, look at the binds listed in https://docs.eggheads.org/mainDocs/twitch-tcl-commands.html . You probably want to use those instead of a RAWT bind when able, it will make life a little easier.

We don't have a usernotice bind it seems; that is probably something we should add for the next version. For now, you can do a RAWT bind again, similar to above, but instead of a PRIVMSG use USERNOTICE. https://dev.twitch.tv/docs/irc/tags#usernotice-twitch-tags will be your friend to find the right tag, if you haven't already seen that page.

**Comment by sx66627** [comment]
Working version of the first and third question: 
bind rawt * PRIVMSG twitch:tags
bind pub * !msgid pub_msgid
bind pub * !whoami pub_whoami

proc twitch:tags {from key text tag} {
global twtags
set twtags $tag
#putlog "The tags for this message are: $tag"
}

proc pub_msgid {nick host hand chan arg} {
global twtags
set msgid [dict get $twtags id]
putserv "PRIVMSG $chan : $nick your msgid $msgid"
#twcmd $chan delete $msgid
}

proc pub_whoami {nick host hand chan arg} {
global twtags
set badges [dict get $twtags badges]
putserv "PRIVMSG $chan : $nick $badges"
}

putlog "test.tcl -->loaded"

But messages about subscriptions and raids for example. So it was not possible to get it. From the suggested binds did not find a suitable one.
Only hosttarget came in handy.
Example: 
setudef flag nopubhost

bind htgt * * tw:host

proc tw:host {target chan viewers} {
if {[channel get $chan nopubhost]} { return }

set streamer [regsub "#" $chan ""]

    if {$target != "-"} {
        if {$viewers != "-"} {
            putserv "PRIVMSG $chan :$streamer now hosting channel $target with $viewers viewers.";
        } else {
            putserv "PRIVMSG $chan :$streamer now hosting channel $target";
        }

    }

}


putlog "host.tcl -->loaded"

**Comment by vanosg** [comment]
For subscriptions, that was my comment about not having a usernotice bind. LIke I said above, you'll want to use a RAWT bind with USERNOTICE as the type, and search the tags for the information you're looking for.

**Comment by sx66627** [comment]
Thank you very much for answer! 👍
