### ISSUE TITLE
bind ircaway : comma after nick

### ISSUE THREAD

**Issue by crazycatdevs** [eggheads/eggdrop#1207]
in the bind ircaway (CAP away-notify), the nick is followed with a comma.
**Test code:**
```
bind ircaway - * testaway
proc testaway {nick uhost handle chan text} {
   putlog "AW: *$nick*"
}
```
Result:
```
[16:11:46] triggering bind testaway
[16:11:46] AW: *CrazyCat,*
[16:11:46] triggered bind testaway, user 4.000ms sys 0.000ms
[16:12:11] triggering bind testaway
[16:12:11] AW: *CrazyCat,*
```

**Comment by vanosg** [comment]
well gee. That doesn't seem right, does it :)

**Comment by vanosg** [comment]
I can't reproduce this yet. Can you share what server this was on? Can you enable console mode +r and paste the server AWAY message that is sent to the Eggdrop? Thanks
