### ISSUE TITLE
new configure option --disable-old-botnet

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#1235]
It would be nice to have have a configure option `--disable-old-botnet` instead of wanting the user to edit eggdrop.h:

https://github.com/eggheads/eggdrop/blob/d6f53d9a6a9b07dc92b4beb43bb7baad677b5fb8/src/eggdrop.h#L31-L35

**Comment by vanosg** [comment]
This is already on the roadmap to be removed in 2.0
