### ISSUE TITLE
Creating invitation doesn't send invite to user

### ISSUE THREAD

**Issue by crazycatdevs** [eggheads/eggdrop#1248]
When you create a new channel invitation, sticky or not, nothing is sent to the user, you have to add a `putserv "INVITE $nick $chan`.

It could be a good idea to have an option in newchaninvite to force the sending of the invitation (when the invitation is created and if the user is in a channel where the eggdrop is)

**Comment by vanosg** [comment]
I don't think this is the intended functionality, nor do we want to add this as a functionality. The .+invite command (which I assume is what you're talking about here? Either way, Tcl works the same I believe) maintains an internal list of invites associated with the +I mode, similar to the internal ban and invite list. Additionally, invites are sent to a nickname, whereas .+invite uses a hostmask. My opinion is that I'm not interested in sending an invite request when it would only happen one time for a setting that is stored longterm, the user may already be in the channel the +I is being added to, and when the command takes a hostname. I think the implementation of this will be complex, confusing, and create a large amount of different branches where it does not function the same for all people.

FWIW, .dump INVITE nick channel is an alternative for partyline usage that doesn't rely on Tcl. I would however be supportive of adding a plain .invite partyline command, and maybe a Tcl command, although I'm sure @thommey has 8 reasons why we don't need one :)

**Comment by crazycatdevs** [comment]
I'm talking about the [newchaninvite](https://github.com/eggheads/eggdrop/blob/d3083ccbed17e9663854d6c359fdb74f78c811ce/doc/tcl-commands.doc#L609) command that I use in a script.

Actually, I've to create the newchaninvite and invite the user. It's a game script and user doesn't know the channel name neither if he is in the "winner" group, so the only way I've to notice him is the invite command (the channel is +i)

This is not a trouble, I was just surprised that the invite was not sent. And I really think that adding an option (a `notice` ? as `sticky` exists) to send the invite to the user when the newchaninvite is created could be usefull.

BTW, I can live without it, and my scripts will work too :)
