### ISSUE TITLE
ident lookup bind wrong

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#1252]
On an incoming partyline connection an ident lookup is performed to resolve the host to match hostmasks of users for partyline permissions. That lookup is intended to come from the listen-host IP address so it is consistent with the lookup on the client side.

However, it seems like the bind() is wrong and binds to the actual listen port that is already in use instead of to the IP address but using sin_port=0. That causes the bind to fail and potentially perform the ident lookup from an unknown (main) IP instead of the designated vhost/listenip.
```
18:47:28.937762 getsockname(11, {sa_family=AF_INET, sin_port=htons(64444), sin_addr=inet_addr("87.106.X.Y")}, [28->16]) = 0
18:47:28.937817 bind(12, {sa_family=AF_INET, sin_port=htons(64444), sin_addr=inet_addr("87.106.X.Y")}, 16) = -1 EADDRINUSE (Address already in use)
18:47:28.937873 connect(12, {sa_family=AF_INET, sin_port=htons(113), sin_addr=inet_addr("213.239.X.Y")}, 16) = -1 EINPROGRESS (Operation now in progress)
18:47:47.456952 accept(8, {sa_family=AF_INET, sin_port=htons(59976), sin_addr=inet_addr("213.239.X.Y")}, [28->16]) = 11
```

**Comment by michaelortmann** [comment]
There is not even an error check for bind():

https://github.com/eggheads/eggdrop/blob/447fde00cc1be86f316271c207b94169ff53267b/src/dcc.c#L1360
