### ISSUE TITLE
[Suggestion] Add filters to channels command

### ISSUE THREAD

**Issue by crazycatdevs** [eggheads/eggdrop#1268]
I think it could be interesting to filter channels of an eggdrop with `channels` command

Example: `channels +nodesynch` will retrieve the list of channels with nodesynch flag, when `channels -bitch` will retrieve the list of channels without the bitch flag.
I actually do it with tcl, but it might be cool to have the filter directly

**Comment by vanosg** [comment]
It is an interesting idea, but as you said it can be done in Tcl. I don't think something we are interested in pursuing at this time. Thanks!
