### ISSUE TITLE
Extended-join not fully operated

### ISSUE THREAD

**Issue by crazycatdevs** [eggheads/eggdrop#1278]
When the CAP extended-join is used, I didn't find any way to use the informations (accountname, realname) provided.
The only staying bind is the usual JOIN, peharps could it be interesting (if it's possible) to add a EJOIN which will provide all the informations existing in the extended-join.
Advantage of having it: some scripts use the realname of user, actually we have to do a /who and parse the raw to get it, it charges the eggdrop and the server whereas the information is already present.

**Comment by vanosg** [comment]
We're discussing a few longer-term solutions, but right now, something similar to 
```
bind rawt * JOIN foo
```
might be a good starting point to check this information at join time.
