### ISSUE TITLE
Setting away-notify doesn't enable the cap

### ISSUE THREAD

**Issue by jobe1986** [eggheads/eggdrop#1283]
Summary says it all but setting away-notify in the config does not enable the cap even though the C code tracks the tcl variable away-notify.

**Comment by vanosg** [comment]
away-notify is not a setting provided for in the config file at this time; setting it is not intended (nor documented) to have an effect. It would be treated the same as any other Tcl variable a user adds to their config file. It is not intended to enable a capability.
