### ISSUE TITLE
(Improvement timer system) : Naming of utimers and timers

### ISSUE THREAD

**Issue by ZarTek-Creole** [eggheads/eggdrop#1285]
Currently the syntax is like this:
```
timer <minutes> <tcl-command> [count]
utimer <seconds> <tcl-command> [count]
killtimer <timerID>
killutimer <timerID>
```

I propose to have the possibility of naming them in an optional way:

```
timer [name] <minutes> <tcl-command> [count]
utimer [name] <seconds> <tcl-command> [count]
killtimer <timerID/timerName/partialname*>
killutimer <timerID/timerName/partialname*>
```

What is the point of naming the timers?
The first, it would be easier to kill them if we know the name.

The second, for a reason X or Y we could replace the timer. if we use the same name the eggdrop will kill the old one and recreate the new one.

In some cases this is very useful. In mrc scripting the timers are nameable and this opens up a greater number of possibilities.

A third thing with naming timers:
Imagine that my script is called ZarTeK and in it I create 3 timers for example:
`ZarTeK_1, ZarTeK_2 and ZarTeK_3`

I want to kill the 3 when unloading my script or at the end of the game if it's a game..
I just need to do a `killtimer ZarTeK_*`

if the first argument to timer is a digit it is an unnamed user; if the first is a digit value then it is a timer with a name.

**Comment by vanosg** [comment]
I looked a little into the structure of timers; at first glance adding a name to timers might be possible without too much rework, at least in a limited capacity. Thanks for contributing the idea
