### ISSUE TITLE
'make sslcert' fails

### ISSUE THREAD

**Issue by fred0r** [eggheads/eggdrop#131]
'make sslcert' fails after 'make install DEST=...'
the regular 'make install' installs to '~/eggdrop'
after doing that the make sslcert works

4.2.5 # 1 SMP PREEMPT Wed Oct 28 01:18:34 CET 2015 x86_64 GNU/Linux
Debian Jessie

**Comment by vanosg** [comment]
Hi fred0r,

  Take a look at #127 ... it will be merged soon, but that patch should fix the issue for you. You can pick that commit and merge in locally yourself, or wait a few days for it to make it into the main branch. Thanks for reporting!

**Comment by thommey** [comment]
Hey,
the documentation is now updated and should properly reflect that you need DEST= for make sslcert as well, thank you for your bug report :-)
