### ISSUE TITLE
Latest (22.08.28) dev crashes on android/termux

### ISSUE THREAD

**Issue by ploxxusVulgaris** [eggheads/eggdrop#1324]
Debug (eggdrop v1.9.3+gotmsg) written Sun Aug 28 13:35:32 2022
Patch level: gotmsg
Tcl library: /data/data/com.termux/files/usr/lib/tcl8.6
Tcl version: 8.6.11 (header version 8.6.11)
Tcl is threaded
Compiled with IPv6 support
Compiled with TLS support
Configure flags: '--with-tcl=/data/data/com.termux/files/usr/lib/tclConfig.sh'
Compile flags: gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H -I/data/data/com.termux/files/usr/include -g3 -DDEBUG -DDEBUG_ASSERT -DDEBUG_MEM -DDEBUG_DNS 
Link flags: gcc -lpthread
Strip flags: touch
Context: main.c/1042, []
         main.c/1042, []
         main.c/1042, []
         main.c/1042, []
         main.c/1042, []
         main.c/1042, []
         main.c/1042, []
         main.c/1042, []
         main.c/1042, []
         main.c/1042, []
         main.c/1042, []
         main.c/1042, []
         main.c/1042, []
         main.c/1042, []
         tclhash.c/219, []
         tclhash.c/247 []

IDX ADDR                                     + PORT NICK      TYPE  INFO
--- ---------------------------------------- ------ --------- ----- ---------
5   127.0.0.1                                  3990 (users)   lstn  3990
6   127.0.0.1                                + 3991 (users)   lstn  +3991

Not logging file main.c!
File 'language.c' accounted for 20041/20041 (ok)
File 'chanprog.c' accounted for 0/0 (ok)
File 'misc.c    ' accounted for 182079/182079 (ok)
File 'userrec.c ' accounted for 0/0 (ok)
File 'net.c     ' accounted for 0/0 (ok)
File 'dccutil.c ' accounted for 5680/5680 (ok)
File 'botnet.c  ' accounted for 0/0 (ok)
File 'tcl.c     ' accounted for 2000/3696 (debug follows:)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 933 :(0016)
   933 :(0016) 852 :(0016) 852 :(0016) 852 :(0016) 852 :(0016)
   852 :(0016) 852 :(0016) 852 :(0016) 852 :(0016) 852 :(0016)
   852 :(0016) 852 :(0016) 852 :(0016) 852 :(0016) 852 :(0016)
   852 :(0016) 852 :(0016) 852 :(0016) 852 :(0016) 852 :(0016)
   852 :(0016) 852 :(0016) 852 :(0016) 852 :(0016) 852 :(0016)
   852 :(0016) 852 :(0016) 852 :(0016) 852 :(0016) 852 :(0016)
   852 :(0016) 852 :(0016) 852 :(0016) 852 :(0016) 892 :(0016)
   892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016)
   892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016)
   892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016)
   892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016)
   892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016)
   892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016)
   892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016)
   892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016)
   892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016)
   892 :(0016) 892 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   319 :(0032) 892 :(0016) 892 :(0016) 852 :(0016) 852 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016) 351 :(0016)
   351 :(0016) 351 :(0016) 852 :(0016) 852 :(0016) 852 :(0016)
   892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016)
   892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016)
   892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016)
   892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016) 892 :(0016)
   892 :(0016) 933 :(0016) 933 :(0016) 933 :(0016) 933 :(0016)
   933 :(0016) 933 :(0016) 933 :(0016) 933 :(0016) 933 :(0016)
   933 :(0016) 933 :(0016) 933 :(0016) 933 :(0016) 933 :(0016)
  
File 'tclhash.c ' accounted for 12068/12068 (ok)
File 'tclmisc.c ' accounted for 19/19 (ok)
File 'modules.c ' accounted for 440/440 (ok)
File 'tcldcc.c  ' accounted for 32/32 (ok)
File 'dns.c     ' accounted for 0/0 (ok)
File 'tls.c     ' accounted for 0/0 (ok)
Module 'channels  ' accounted for 3732/3732 (ok)
Module 'encryption' accounted for 0/0 (ok)
Module 'encryption2' accounted for 0/0 (ok)
Module 'eggdrop   ' accounted for 0/0 (ok)
--- End of debug memory list.
Open sockets: 5 (listen), 6 (listen), 7 (file), done.

**Comment by vanosg** [comment]
Hi @ploxxusVulgaris , thanks for taking the time to submit this! Can you provide any additional context as to what is causing this crash? ie, on startup, when it joins a server, when someone talks, etc. Also, does this happen when you remove all your Tcl scripts?

There are a lot of questions we have, as Android isn't a "normal" platform for us. It would be great if you could join us on #eggdrop on Libera and talk this over with us. Thanks again, and we look forward to talking more with you
