### ISSUE TITLE
DCC

### ISSUE THREAD

**Issue by atulicipro** [eggheads/eggdrop#1328]
I can't get into DCC from eggdrop, can someone help me to get into DCC. It doesn't work on any new version, I tried on 3 versions and nothing.

**Comment by vanosg** [comment]
Hi @atulicipro ,
 The issues forum here is used for reporting bugs, not troubleshooting usage. To ask questions about Eggdrop usage and troubleshooting, please join #eggdrop on Libera. Thanks!
