### ISSUE TITLE
Expand the [channels] command

### ISSUE THREAD

**Issue by ZarTek-Creole** [eggheads/eggdrop#1342]
Found by: CrazyCat

The [[channels]](https://docs.eggheads.org/using/tcl-commands.html#channels) command could be extended as done in the PR #1341 with options/flags channels to list channel with that.

Example: 

- List of channels with autop is enabled

`channels +autoop`

- List of channels with autop is disabled

`channels -autoop`

- With Custom channel option
```
< setudef flag idlekick
< .chanset #example +idlekick
< channels +idlekick
> {#example}
```

`channels [options]`
Returns: a list of channels record on the bot. You can use the options matching system. The full list of possible options are given in [doc/settings/mod.channels](https://github.com/eggheads/eggdrop/blob/develop/doc/settings/mod.channels).

Module: channels

**Comment by vanosg** [comment]
This is more a comment on #1341 rather than an Eggdrop issue; any further discussion should go there

**Comment by ZarTek-Creole** [comment]
Title: Enhancing Efficiency and Readability by Extending Functionality of [channels] Command to Include Flags

Description:

An interesting topic was identified on a forum that could significantly impact the efficiency and readability of our current C code base (the full discussion can be found [here](https://forum.eggdrop.fr/Retourner-le-max-users-dans-un-channel-t-1999.html#pid14508)).

The topic proposes the refactoring of a particular code snippet which is currently implemented as follows:

```tcl
foreach chan [channels] {
    if {![channel get $chan dstats]} { continue }
       ...code... 
    }
```

The code essentially loops through all channels, subsequently checking for the 'dstats' flag using [channel get $chan dstats]. This approach has a performance overhead and affects readability.

The proposed refactoring could streamline the code into a simpler, more efficient form like this:

Option 1:
```tcl
foreach chan [channels dstats] {
   ...code... 
}
```

Or this:

Option 2:
```tcl
foreach chan [channels +dstats] {
   ...code... 
}
```

These refactored versions remove the need for the `if {![channel get $chan dstats]} { continue }` line, thereby improving readability.

The deeper suggestion, however, is to extend the functionality of the [channels] command to accept flags directly, such as [channels (+/-)dstats]. This would make the command return the list of channels that either have the 'dstats' flag (+dstats) or do not have it (-dstats). This proposed feature would shift the processing from TCL to C, further enhancing efficiency and readability. 

In light of these findings, it is recommended to consider implementing these changes, or similar ones, to optimize our code base. This will not only simplify the overall structure but also make the code easier to comprehend.
