### ISSUE TITLE
Executing "save" (or any other "event") sets the event variable "$_event1" in the local scope, not the global scope

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#135]
When you use the SAVE command, because of the event binding introduced in recent Eeggdrop versions, the variable $::_event1 is supposed to be set to "save" (the first element of the list of event bind triggers). However, for SAVE, it sets $_event1 instead (in the local scope, not the global scope).

Tested with the following code:
<Domino> happy tcl ; proc crap args { unset -nocomplain ::_event1  ; debug ::_event1 _\* ; save ; debug ::_event1 _\* ; return 0 }
<Domino> happy tcl crap
<Happy> [DEBUG] [CRAP] ::_event1
(this means: no variables match either $_\* (local scope, unreferenced) or $::event1 (global, obviously))

<Happy> [DEBUG] [CRAP] ::_event1:_event1(save)
(this means: the local variable $_event1 was created and set to "save;" the global (true) one wasn't created)

Translation: when the event is triggers by the SAVE command, the local variable (in-scope) $_event1 is created _instead of_ the global variable $::_event1

Cursory tests of other events reveal the same result / issue: (userfile-reloaded, et al). My understanding that all ^_[a-z]+[0-9]$ variables are created at the global scope, and left there until re-assigned by something else.

The commands PUTLOG & PUTCMDLOG do the same thing with the $_log1 / $_log2 / $_log3 variables. I haven't tested PUTLOGLEV yet.

This does NOT seem to happen when creating "fake events" as reported in bug #136.

Is this by design or a bug similar to the UPDATE bug I reported a couple of years ago?

**Comment by thommey** [comment]
Will be fixed as part of #51.
