### ISSUE TITLE
In file included from botcmd.c:25: main.h:41:10: fatal error: eggint.h: No such file or directory

### ISSUE THREAD

**Issue by brendoncdrew** [eggheads/eggdrop#1358]
In file included from botcmd.c:25:
main.h:41:10: fatal error: eggint.h: No such file or directory
   41 | #include "eggint.h"
      |          ^~~~~~~~~~
compilation terminated.
In file included from botmsg.c:27:
main.h:41:10: fatal error: eggint.h: No such file or directory
   41 | #include "eggint.h"
      |          ^~~~~~~~~~
In file included from bg.c:25:
main.h:41:10: fatal error: eggint.h: No such file or directory
   41 | #include "eggint.h"
      |          ^~~~~~~~~~
compilation terminated.
compilation terminated.
In file included from botnet.c:29:
main.h:41:10: fatal error: eggint.h: No such file or directory
   41 | #include "eggint.h"
      |          ^~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:83: bg.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:83: botcmd.o] Error 1
make[1]: *** [Makefile:83: botmsg.o] Error 1
make[1]: *** [Makefile:83: botnet.o] Error 1
make[1]: Leaving directory '/home/bdrew/source/eggdrop/src'
make: *** [Makefile:271: static] Error 2
┌─[bdrew@HpEE] - [~/source/eggdrop] - [Mon Nov 28, 15:49]
└─[$] <git:(develop*)> fd eggint.h
┌─[bdrew@HpEE] - [~/source/eggdrop] - [Mon Nov 28, 15:50]
└─[$] <git:(develop*)>

**Comment by michaelortmann** [comment]
`eggint.h` is created in current working directory by the configure script.

so i suspect the configure script was run while the working directory was not `eggdrop/`.

does running `./configure` in `eggdrop/` directory help? like:

```
$ cd eggdrop
$ ./configure
```

**Comment by brendoncdrew** [comment]
Oops my bad ./configure was erroring out not finding tcl and i didn't notice.... pointed it to the rite place with --with-tcllib and it finished correctly... and built just fine this time... thx for the assitance :^)
