### ISSUE TITLE
Event binds (BIND EVNT) allow you bind to *any* keyword, not just the ones in tcl-commands.doc

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#136]
<Domino> ;; bind evnt - cow evnt:cow ; proc evnt:cow args { debug args _event1 ; return 1 }
-Santana- [TCL (0ms)] 
<Domino> ;; callevent cow
-Santana- [DEBUG] [EVNT:COW] _event1:args(cow)
<Domino> ;; evnt:cow
-Santana- [DEBUG] [EVNT:COW] _event1:args()
( $args == "" )

By binding to any keyword whatever, you can call the proc directly or by "callevent." You can invent any event you want.

Is this intentional?

Note: the $_event1 variable isn't set like reported in bug #135. I guess that is only set by official Eggdrop code that required updating for event handling when you introduced it.

**Comment by thommey** [comment]
Fixed by 5a87412ec7ef0538a32ff4f31981a24bd0dc7da9. It documents that arbitrary events are allowed (it's a feature), and at least sets the evnt and log variables in the global scope for now. Will get really fixed in #51.
