### ISSUE TITLE
Tcl binds-command output changed in 1.9.4

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#1373]
Previously we formatted "ignore flags" as `-|-` but now format it as `*|*` for both the dcc command and the Tcl `[binds]` command.
The latter caused scripts to break that rely on it being formatted as `-|-`, for example, https://github.com/glftpd/pzs-ng/blob/master/sitebot/plugins/Blow.tcl#L640

Scripts having a special case for `-|-` instead of passing it to `[matchattr]` is justified because `-|-` wasn't allowed in `[matchattr]` for some versions of Eggdrop, see #1267 

Found by: fred

**Comment by vanosg** [comment]
Can this be closed? I believe this was reverted in 1.9.5

**Comment by vanosg** [comment]
@thommey

**Comment by thommey** [comment]
We cannot change the Tcl [binds] format back to -|- because of backwards-compatiblity requirements, so it's probably not worth it to change the dcc .binds command which would add complexity. I vote close and leave this as-is, as unfortunate as the -|- syntax is.
