### ISSUE TITLE
Publish mail address of signing public key of eggdrop at keys.openpgp.org?

### ISSUE THREAD

**Issue by robert-scheck** [eggheads/eggdrop#1376]
Do you see a chance to publish the mail adress of the public key of key E01C240484DE7DBE190FE141E7667DE1D1A39AFF, being used for signing eggdrop release tarballs, at keys.openpgp.org? This would allow Fedora to switch from the current binary GnuPG output blob (manually created) to the ASCII format provided there. Unfortunately keys.openpgp.org [strips all user IDs unless the owner of the corresponding email address has allowed them to be published](https://superuser.com/questions/1485213/gpg-cant-import-key-new-key-but-contains-no-user-id-skipped), thus keys.openpgp.org can't be used for the ASCII format right now.

**Comment by vanosg** [comment]
@robert-scheck thanks for submitting these issues... are you able to join us on Libera #eggdrop? It seems you're pursuing something larger here, we'd love to understand the bigger picture and maybe see how we can better help. Thanks!

**Comment by robert-scheck** [comment]
Aside of our IRC followup, I would like to mention https://keys.openpgp.org/about/faq also here.

**Comment by robert-scheck** [comment]
Thank you! Changed in the Fedora eggdrop RPM package build with [commit c30e7b7d7fb0075a9cd198c2ef0562d35bfed872](https://src.fedoraproject.org/rpms/eggdrop/c/c30e7b7d7fb0075a9cd198c2ef0562d35bfed872?branch=rawhide).
