### ISSUE TITLE
Please make hardcoded ./language a ./configure build-time option

### ISSUE THREAD

**Issue by robert-scheck** [eggheads/eggdrop#1377]
As of writing, I'm using https://src.fedoraproject.org/rpms/eggdrop/blob/rawhide/f/eggdrop-1.6.17-langdir.patch at Fedora and EPEL (for CentOS Stream, RHEL, Rocky Linux etc.) to relocate the hardcoded `./language` according to FHS properly for a system-wide installation of eggdrop using RPM without forcing users to `EGG_LANGDIR` environment variable usage.

I wonder if you see a chance for turning the hardcoded `./language` (in the actual code as well as in the man page) into a `./configure` build-time option that packagers/downstreams could use?

**Comment by vanosg** [comment]
We're tracking this in #474, and this is probably something we're going to look heavily at as part of the 1.10 release, alongside the possibility of doing a system-wide install option. Closing this to not duplicate.
