### ISSUE TITLE
Timer drift: doesn't show hours

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#138]
I have a couple of scripts that do "heavy background work" (will most definitely ping out any other bot), but I have server PING? PONG! events scripted into it so the bot doesn't ping off the server (and PI PO events to protect the botnet as well). I monitor progress of the script in debugs to IRC or through PUTLOG on the party line.

The problem is: while developing this, I noticed that (when the PING? PONG! failed and the bot did ping out), if the bot was "locked up" for more than 60 minutes, the "timer drift" error message in the party line (log) doesn't show hours, only minutes (hours are truncated).

[2015-12-31 03:11:51] <Scorpion> [2015-12-31 03:11:39 -0800] [03:11] [r->] privmsg #Home :[DISTRO: REL REDO] Rebuilding new distro tarballs: %MAJOR%.%MINOR%.%BUILD:5%.%DISTRO%.tar.gz / 1 / 1 / 6
[2015-12-31 03:11:51] <Scorpion> [2015-12-31 03:11:39 -0800] [03:11] [r->] PING :1451560299
[

<SNIP: a bunch of crap>
( server pingout: the frequency of the PING? PONG! events was longer than the server's Y:line ping frequency )

[2015-12-31 04:45:57] <Scorpion> [2015-12-31 04:45:46 -0800](!) timer drift -- spun 33 minutes

It should have reported "1 hour, 33 minutes" and not just "33 minutes" (really, 34). Is this is based off of the not-on-server error time, or how long the bot didn't return to the tcl loop?

I know most bots won't be written to "survive" online for over an hour while doing tasks; this is a cosmetic issue for accuracy.

**Comment by thommey** [comment]
A bit more complicated than just adding hours. Eggdrop attempts to catch up on the missed events by calling minutely hooks (time binds etc.), but the current code really only works if it hangs for less than an hour, otherwise it fails completely (and would, in your example, only call a bind time on \* 33 times instead of 93 times). Needs to be fixed, but not a "trivial" fix.
