### ISSUE TITLE
Rename doc/MODULES -> doc/README.MODULES

### ISSUE THREAD

**Issue by jHackenthal** [eggheads/eggdrop#1392]
Please rename doc/MODULES to something else that makes equal sense.

Upon clone of this repository the presence of "MODULES" file and "modules" directory cancels each other out.

For instance while working on a MacBook Pro with the default apfs filesystem which is case-insensitive unless specifically formatted differently, the initial clone removes doc/MODULES. After a (git checkout doc/MODULES) the directory of doc/modules is removed.

Updating this repository while in a dirty state is impossible to track on a  default apfs install or other similar systems.

**Comment by jHackenthal** [comment]
Apologies if this happens to be a duplicate after a quick cursory search of issues.

**Comment by crazycatdevs** [comment]
I agree with that, evenn if I'm using case-sensitive fs.
Could be a trouble for windows users

**Comment by thommey** [comment]
Makes sense, there is no good reason to have case collisions in our source code or installation

**Comment by jHackenthal** [comment]
Ping back !

**Comment by michaelortmann** [comment]
same problem on cygwin. but some other dev will have to fix this, i dont want to mess with doc design.
