### ISSUE TITLE
Implement Server Name Indication (SNI)

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#140]
Yep.

**Comment by YogSottot** [comment]
https://wiki.tcl.tk/2630
In tcl-tls 1.7.11 was added -autoservername true option for SNI support.
For older version solution also provided.

**Comment by michaelortmann** [comment]
We may need SNI for TLS 1.3? Currently TLS 1.3 is working for me, but if you see any renegotiation issues with TLS 1.3, come back here.
