### ISSUE TITLE
bind monitor and wildcards seems to not work

### ISSUE THREAD

**Issue by crazycatdevs** [eggheads/eggdrop#1404]
Reading the doc about bind monitor:
> nick is the nickname of the intended MONITOR target and can be used with wildcards

But it doesn't seems to work, I made a try:

```
.tcl proc mon {nick online} { putlog "$nick is now $online"}
.tcl bind monitor - crazycat mon
.tcl monitor add crazycat
> CrazyCat is now 1
.tcl monitor delete crazycat
.tcl unbind monitor - crazycat mon
.tcl bind monitor - * mon
.tcl monitor add crazycat
> ... nothing
```

**Comment by vanosg** [comment]
Confirmed, thanks for reporting!

Also TODO, based on research into this: 
- properly update tcl list when receiving 733
- reset list when jumping servers (or resend list?)
