### ISSUE TITLE
Eggdrop forgets channel state after being opped

### ISSUE THREAD

**Issue by Pixelz** [eggheads/eggdrop#141]
Upon being opped in a channel, eggdrop throws out everything it knows about the channel (.channel #chan is blank), but doesn't send WHO #chan to update itself again.

Console log:
Eggdrop is unopped, and has a fully populated .channel #chan at this stage

[@] Pixelz!pix@pix.pp.se MODE #eggdrop +o Eggdrop  
[!m] MODE #eggdrop +eI  
[m->] MODE #eggdrop +eI  
[@] barjavel.freenode.net 349 Eggdrop #eggdrop :End of Channel Exception List
[@] barjavel.freenode.net 347 Eggdrop #eggdrop :End of Channel Invite List   

At this stage, .channel #chan is blank. sending .dump #WHO #chan fixes it.

**Comment by vanosg** [comment]
I can't reproduce this. 

```
[23:43:08] egg21 joined #chan.
.channel #chan
Channel #chan, 2 members, mode +sn:
(n = owner, m = master, o = op, d = deop, b = bot)
 NICKNAME  HANDLE     JOIN  IDLE  USER@HOST
@user       user   23:40 N      foo@user.com
 egg21     egg21   23:43 N     <- it's me!
End of channel info.
[23:43:51] #chan: mode change '+o egg21' by Geo!foo@user.com
[23:43:52] #chan: mode change '+t ' by egg21!foo@user.com
.channel #chan
Channel #chan, 2 members, mode +stn:
(n = owner, m = master, o = op, d = deop, b = bot)
 NICKNAME  HANDLE     JOIN  IDLE  USER@HOST
@user       user   23:40 N      user@foo.com
@egg21     egg21   23:43 N     <- it's me!
End of channel info.
```

**Comment by vanosg** [comment]
For historical sake, this is only triggered when net-type 0 was being used (specifically when eI mdes were being checked)
