### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by docgonzo2015** [eggheads/eggdrop#1430]
Hi!

If someone posts a smiley,  eggdrop  crashes:

|06:03:2023|22:54:53| <+itest> liegt wohl an sowas ... 😃
|06:03:2023|22:54:54| * Quits: Eggdrop  (Connection closed)

**Comment by michaelortmann** [comment]
probably fixed by #1402

**Comment by vanosg** [comment]
Fixed in current release candidate
