### ISSUE TITLE
Remove quick-logs, write to logfiles instantly

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#1449]
quick-logs might have had a purpose in the past to protect disks against frequent writes, but I don't think it's relevant anymore and it would be much more beneficial to have logs be live. At least in my opinion.
This proposes to eliminate the quick-logs setting entirely and always instantly write to the logfiles that are held open anyway. It should be made sure they're line-buffered.

**Comment by thommey** [comment]
As far as I can see, quick-logs was added in 1999 to enable faster flushing so the 5-minutely log flushing might have been in the intial release of Eggdrop

**Comment by crazycatdevs** [comment]
And what about add a little check to verify the file is alway present and recreate it if needed ?

**Comment by michaelortmann** [comment]
i dislike frequent writes, but i think we should leave users with choice, and do it like for example firefox, which has interval setting, like browser.sessionstore.interval.
so, what about replacing quick-logs, which can only be on or off, with a replacement setting called log-interval? i would prefer that settings to be in millisecs, but our current eggdrop main loop is ticking with 1Hz, so, it can be only in seconds.
default interval could be 30 secs, 15 secs, 5 secs, 1 sec or 0 secs, which would be live logging. the current 5 mins ?! is too high, i agree.

**Comment by michaelortmann** [comment]
we already have ticket #181 for this issue

**Comment by michaelortmann** [comment]
quick_logs also controls whether eggy writes "last message repeated x times" into logfiles. what are we gonna do about this? see https://github.com/eggheads/eggdrop/blob/develop/src/misc.c#L710

**Comment by vanosg** [comment]
I think the intent of this is not to create a configurable option as in #1477  but remove it altogether. The point of this issue is that there isn't an understood requirement in this modern day buffer logs, so why keep it.

**Comment by michaelortmann** [comment]
We talked about this in IRC, and #1477 was changed accordingly.
