### ISSUE TITLE
Module with twitter functionality

### ISSUE THREAD

**Issue by moonlightz** [eggheads/eggdrop#1453]
This is just an idea... MORE useful than the unuseful twitch module that no one probably uses.

Background: 
Twitter is a very popular platform since its being for sending tweets/getting latest news and other useful things.
I myself have an account since 2017 but I rarely send messages. I use it to read tweets posted by known people that I selected.
Few years later, I decided why not use the both worlds irc and twitter at same time. Twitter itself resembles to irc with those pound sytmbols and "at" symbols.
So I found horgh's script and api libs here in github. It took some work to set it up, configure, and then squash that emojis bug (tcl needed to be compiled with TCL_UTF_MAX 4 and tcl being 8.7 alpha.
This twitter script worked for quite sometime until May of this year where Twitter itself changed the api from version 1.1 to 2.0 breaking the script and leaving many people furious because they were using this script or some sort of tool that suddenly stopped working.
I myself had to revoke the application and generate a new one, it kind allowed to auth again with oauth 1.0 but I was getting different things and the script wasn't recognizing them. With patience, I could fix the script but I don't longer have time and patience.

Present:
Before the script stopped working, I split the script and its 2 lib files to another eggdrop bot for this specific task that is displaying tweets to specific irc channels. Few weeks after, Twitter changed its api. Got to find an alternative.
I came across with twitter/t ruby gems. It posts twitters to the linux shell. Not a great way but it is an way to achieve a goal. I had to workaround problem and make the two things happy. I had to create a tcl from scratch that calls the twitter gem executable, send a command, process the tweets, send the text to specific irc channels using the same config file of horgh's script, and store the last id. This kinda works fine. The eggdrop log logs what who tweeted, what channel it goes, text send.

For now there are at least 1 MAJOR problem I am still facing:
• The text received is... shortened and I didn't found a way/why this ruby gem does this. I can't get a full text.

IN SUM:
Someone creating a TWITTER module would be more useful for people and MAYBE turn eggdrop even more popular. (maybe for evil purposes?)

**Comment by vanosg** [comment]
This type of application (web/API interaction) is better suited for a Tcl script, not a module. The server structure underlying Twitch uses a version of IRC, so a module to supplement what Eggdrop already does made sense. We certainly feel the pain of web APIs changing versions and breaking compatibility, but writing a Twitter Tcl script is not something in the cards for us as maintainers to build- for exactly the reason that we can't keep up with API changes. I'd suggest heading over to the forums at forum.egghelp.org and asking there, or googling! Good luck
