### ISSUE TITLE
Logfile: action is logged twice

### ISSUE THREAD

**Issue by crazycatdevs** [eggheads/eggdrop#1494]
Hi there,

Looking in my logfiles, I can see that ACTION are loged twice:
On irc: `12:59:10  * CrazyCat fait un test ici`
In logfile :
```
[12:59:10] Action: CrazyCat fait un test ici
[12:59:10] <CrazyCat> ACTION fait un test ici
```

My logfile configuration: `{pjks #zeolia logs/artus_zeolia.log}`

I think it's in relation with #1313

**Comment by vanosg** [comment]
Agree, that it's part of 1313, let's track all this over there as the single issue that it is
