### ISSUE TITLE
botnet userfile transfer issue since v1.9.3, due to commit f9d8af4

### ISSUE THREAD

**Issue by pym67** [eggheads/eggdrop#1496]
Hello,

since v1.9.3 i'm experiencing botnet userfile transfer issue, like below:
The issue is reproduced with 1.9.4, 1.9.5 and current dev-branch

Linking to mybot at [IPv6]:39229 ...
TLS: handshake successful. Secure connection established.
Received challenge from mybot ... sending response ...
Linked to mybot.
Sending user file send request to mybot 
TLS: handshake successful. Secure connection established.
**Lost userfile transfer from mybot ; aborting.**

after debugging,  the TLS connection is well established but the userfile is never received on the other party in the socket.

After some investigation, the issue looks to be introduced by the following commit : f9d8af4
<details>
"Fix -t without active other sockets
Found by: Geo
Patch by: thommey

On a docker instance of eggdrop stdin is a pipe if run with -i. Eggdrop blocked forever on a read(stdin) because stdin was assumed readable even though select returns 0. The only explanation is that select returning 0 does not clear the input FD sets. It is pointless to loop through all sockets then anyway."
</details>

After reverting this commit, the issue is gone.

I don't know if this commit is itself creating a new bug or whether this commit is surfacing an already existing hidden bug somewhere else in the file-transfer code.

**Comment by vanosg** [comment]
This is some great debugging, thank you! You saved us a lot of time tracking down the source. Nothing jumps out as an obvious cause but we'll definitely dig into this further. Two quick questions:
- could you enable the debug flag (.console +d) and paste a log of the failed connection
- Does this happen all the time, or only intermittently 

Thanks!

**Comment by pym67** [comment]
i will provide the log of failed in the coming days.

in the mean time, i can clarify that the issue is intermittent in the sentence it does affect only some bots of the botnet.
The leaf bots which are effected are however always impacted permanently. 
Sometime, after killing and restarting them a few times it does suddenly work, but if you .unlink and .link again the issue is reproduced again.

**Comment by vanosg** [comment]
Very interesting... looking forward to seeing the debug log. Thanks!

**Comment by pym67** [comment]
below are logs from +d.

The point/fix mentionned by @michaelortmann about SSL make sense, it may be linked an SSL read issue but on the opposite side, by removing this https://github.com/eggheads/eggdrop/commit/f9d8af4bb3a8f13bcf81db9f197f2893ea02f853 the issue is gone (tested for 2 weeks).

there maybe also something left to dig in  https://github.com/eggheads/eggdrop/commit/f9d8af4bb3a8f13bcf81db9f197f2893ea02f853


Downloading user file from MyBot
TLS: attempting SSL negotiation...
TLS: not setting the server name indication (SNI) because host is an empty string
TLS: state change: before SSL initialization
TLS: state change: before SSL initialization
TLS: state change: SSLv3/TLS write client hello
TLS: awaiting more reads
TLS: handshake in progress
TLS: state change: SSLv3/TLS write client hello
TLS: state change: SSLv3/TLS read server hello
TLS: state change: TLSv1.3 read encrypted extensions
TLS: state change: SSLv3/TLS read server certificate request
TLS: peer certificate warning: self-signed certificate
TLS: state change: SSLv3/TLS read server certificate
TLS: state change: TLSv1.3 read server certificate verify
TLS: state change: SSLv3/TLS read finished
TLS: state change: SSLv3/TLS write change cipher spec
TLS: state change: SSLv3/TLS write client certificate
TLS: state change: SSLv3/TLS write certificate verify
TLS: state change: SSLv3/TLS write finished
TLS: handshake successful. Secure connection established.
TLS: certificate subject: C=EU, O=None.net, OU=None, CN=MyBot, UID=MyBot
TLS: certificate issuer: C=EU, O=None.net, OU=None, CN=MyBot, UID=MyBot
TLS: certificate SHA1 Fingerprint: 24:F8:3A:51:5E:76:C5:F9:C4:00:BA:AD:E0:F2:D3:B7:9D:70:E2:A5
TLS: certificate SHA-256 Fingerprint: 41:81:26:27:15:8C:82:AA:92:69:BB:87:E5:54:76:00:CA:79:DA:90:CC:EE:06:48:5F:84:B2:69:44:3A:51:0A
TLS: certificate valid from Nov 11 12:56:16 2023 GMT to Nov 10 12:56:16 2024 GMT
TLS: cipher used: TLS_AES_256_GCM_SHA384 TLSv1.3; 256 bits (256 secret)
TLS: cipher details: TLS_AES_256_GCM_SHA384         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(256)            Mac=AEAD
sockread EAGAIN: 8 11 (Resource temporarily unavailable)
net: connect! sock 8
TLS: state change: SSL negotiation finished successfully
TLS: state change: SSL negotiation finished successfully
TLS: state change: SSLv3/TLS read server session ticket
sockread EAGAIN: 8 11 (Resource temporarily unavailable)
TLS: state change: SSL negotiation finished successfully
TLS: state change: SSL negotiation finished successfully
TLS: state change: SSLv3/TLS read server session ticket
Timeout on userfile transfer.
Received close notify warning during write

.... looping again and again forever

**Comment by michaelortmann** [comment]
yes, its related. the commit you mentioned introduced an early return `when x==0`:
https://github.com/eggheads/eggdrop/commit/f9d8af4bb3a8f13bcf81db9f197f2893ea02f853#diff-e83dab64ed96e8a50f94260f6a3dea5712ef4150a7c2aa3c1c282d4227c93b66R923-R924
so, the line looking for `SSL_pending()` is not reached anymore.

**Comment by vanosg** [comment]
@pym67 , I'm sure you're very busy, but if you get a chance, could you try running the code from https://github.com/michaelortmann/eggdrop/tree/SSL_read ? This is the patch @michaelortmann created to address this issue you found, and is baselined off of the most recent version of eggdrop in the develop branch. We would greatly appreciate it if you were able to give it a try and see if the error remains resolved- thank you very much for any assistance you can offer.

**Comment by pym67** [comment]
@vanosg @michaelortmann sorry for my latency. 
 i've made coupe of tests and i confirm that the SSL_read branch fix the issue. Great !

**Comment by vanosg** [comment]
Thanks for reporting back!
