### ISSUE TITLE
Incorrect SASL logging

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#1497]
After Eggdrop authenticates with a NickServ service via message (not via SASL), the authentication is logged as:
```
[03:20:13] SASL: You are now logged in as MyBot
```

It's not a SASL authentication, but my guess after a quick look at the log is that the 900 reply is sent after SASL and msg authentication, but the SASL code assumes the 900 reply only happens for a SASL login. Probably need to remove the SASL prefix from this log message

**Comment by michaelortmann** [comment]
same problem for numerics 900 and 901. dunno for 902.
