### ISSUE TITLE
Update blowfish modinfo text

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#1499]
Found by: jackal

Blowfish modinfo file (shown during make iconfig) still says Blowfish is the only encryption option, needs updating

**Comment by michaelortmann** [comment]
There is also a comment in code, which looks old?

https://github.com/eggheads/eggdrop/blob/322bddbd102d58cdb00864a3a335b086beaf042c/src/mod/blowfish.mod/blowfish.c#L477
