### ISSUE TITLE
Eggdrop & Tcl 9.0b1

### ISSUE THREAD

**Issue by moonlightz** [eggheads/eggdrop#1532]
While visiting the tcl site, I noticed that the Tcl 8.6.13 is stable as usual but then I noticed that Tcl 8.7a5 was vanished. Instead, Tcl 9.0b1 was in its place. It appeares it was released less than one month ago.
I read the news and changes. I saw the "incompatibilities" list.
I decided to try it out. Downloaded, compiled, and installed.
Then I went to this eggdrop repository, I saw the dates, cloned the repository to the target machine.
I extracted and ran ./compile as usual.
It detected Tcl 9.0b1 
Ran make config. So far, nothing special.
Then I ran make and went to do other things.
When I came back, I found make stopped due error 2 and there were some text saying -w incompatible.
This happened yesterday. I'm just let you know that apperently Eggdrop and tcl 9.0b1 are not friends yet.

**Comment by michaelortmann** [comment]
```
gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H -I/home/michael/opt/tcl9.0git20240212/include -g3 -DDEBUG -DDEBUG_ASSERT -DDEBUG_MEM -DDEBUG_DNS  -c net.c
net.c: In function ‘traced_myiphostname’:
net.c:1708:15: error: ‘TCL_INTERP_DESTROYED’ undeclared (first use in this function); did you mean ‘TCL_TRACE_DESTROYED’?
 1708 |   if (flags & TCL_INTERP_DESTROYED)
      |               ^~~~~~~~~~~~~~~~~~~~
      |               TCL_TRACE_DESTROYED
```

https://core.tcl-lang.org/tips/doc/trunk/tip/543.md
