### ISSUE TITLE
isidentified also acts as onchan

### ISSUE THREAD

**Issue by crazycatdevs** [eggheads/eggdrop#1533]
A small issue found yesterday. isidentified returns 1 if the user is not identified but has a common channel with the eggdrop.

Network configuration: unrealircd + anope (latests versions)

Example: 
- test0r and the eggdrop are on #test 
- test0r is not identified:

```
.tcl isidentified test0r
Tcl: 1
```
test0r does a /part #test : 
```
.tcl isidentified test0r
Tcl: 0
```

**Comment by vanosg** [comment]
Thanks for reporting, this was a regression due to a change in how we stored non-identified account names internally.
