### ISSUE TITLE
--disable-ipv6 disables TLS in develop

### ISSUE THREAD

**Issue by ZarTek-Creole** [eggheads/eggdrop#1554]
./configure 
Operating System: Linux 6.1.0-18-amd64
IPv6 Support: yes
Tcl version: 8.6.13 (threaded)
SSL/TLS Support: yes (OpenSSL 3.0.11 19 Sep 2023)
Threaded DNS core: yes

./configure --disable-ipv6
Operating System: Linux 6.1.0-18-amd64
IPv6 Support: no
Tcl version: 8.6.13 (threaded)
SSL/TLS Support: no
Threaded DNS core: yes

./configure --disable-ipv6
Operating System: Linux 6.1.0-18-amd64
IPv6 Support: no
Tcl version: 8.6.13 (threaded)
SSL/TLS Support: no
Threaded DNS core: yes
./configure --disable-ipv6 --with-sslinc=/usr/include/openssl

**Comment by michaelortmann** [comment]
doesnt affect eggdrop 1.9.5 and below
affects eggdrop git since commit https://github.com/eggheads/eggdrop/commit/642e99dbedc7083452dc3fbb58addd6c0f632843
