### ISSUE TITLE
FreeBSD 14 release and eggdrop 1.9.5 doesnt work with any version of openssl

### ISSUE THREAD

**Issue by ia2115** [eggheads/eggdrop#1561]
Operating System: FreeBSD 14.0-RELEASE-p6
IPv6 Support: no
Tcl version: 8.6.14 (threaded)
SSL/TLS Support: no
Threaded DNS core: yes

/usr/include/openssl
/usr/local/include/openssl

pkg installed: openssl-3.0.13_2,1             TLSv1.3 capable SSL and crypto library

# ./configure

This is Eggdrop's GNU configure script.
It's going to run a bunch of tests to hopefully make your compile
work without much twiddling.

checking for gcc... no
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether cc accepts -g... yes
checking for cc option to enable C11 features... none needed
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking for sys/time.h... yes
checking for sys/select.h... yes
checking for sys/socket.h... yes
checking for sys/param.h... yes
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking for library containing strerror... none required
checking for icc... no
checking whether the compiler understands -pipe... yes
checking whether the compiler understands -Wall... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for make... make
checking whether make sets $(MAKE)... yes
checking for ranlib... ranlib
checking whether ln -s works... yes
checking whether head -n 1 works... yes
checking for strip... strip
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking for basename... basename
checking for uname... uname
checking build system type... x86_64-unknown-freebsd14.0
checking host system type... x86_64-unknown-freebsd14.0
checking for a sed that does not truncate output... /usr/bin/sed
checking how to run the C preprocessor... cc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for library containing gethostbyname... none required
checking for library containing socket... none required
checking whether cc is Clang... yes
checking whether pthreads work with "-pthread" and "-lpthread"... yes
checking whether Clang needs flag to prevent "argument unused" warning when linking with -pthread... no
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for library containing dlopen... none required
checking for tan in -lm... yes
checking target system type... x86_64-unknown-freebsd14.0
checking system type... FreeBSD
checking system release... 14.0-RELEASE-p6
checking module loading capabilities...
checking for dl.h... no
checking for dlfcn.h... yes
checking for loader.h... no
checking for rld.h... no
checking for mach-o/dyld.h... no
checking for mach-o/rld.h... no
checking for dlopen... yes
checking for load... no
checking for NSLinkModule... no
checking for shl_load... no
checking for rld_load... no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for arpa/inet.h... yes
checking for fcntl.h... yes
checking for limits.h... yes
checking for locale.h... yes
checking for netdb.h... yes
checking for netinet/in.h... yes
checking for stdio.h... (cached) yes
checking for stdarg.h... yes
checking for stddef.h... yes
checking for sys/file.h... yes
checking for sys/param.h... (cached) yes
checking for sys/select.h... (cached) yes
checking for sys/socket.h... (cached) yes
checking for sys/time.h... (cached) yes
checking for unistd.h... (cached) yes
checking for wchar.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking whether byte ordering is bigendian... no
checking for inline... inline
checking for flexible array members... yes
checking for intptr_t... yes
checking for pid_t... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for cc options needed to detect all undeclared functions... -fno-builtin
checking for struct tm.tm_zone... yes
checking for working volatile... yes
checking for socklen_t... yes
checking for stdint types... stdint.h (shortcircuit)
make use of stdint.h in eggint.h (assuming C99 compatible system)
checking for dprintf... yes
checking for explicit_bzero... yes
checking for memset_explicit... no
checking for explicit_memset... no
checking for getrandom... yes
checking for inet_aton... yes
checking for isascii... yes
checking for memset_s... yes
checking for snprintf... yes
checking for strlcpy... yes
checking for vsnprintf... yes
checking types of arguments for select... int,fd_set *,struct timeval *
checking for b64_ntop... yes
checking for getpagesize... yes
checking for working mmap... yes
configure: Autoconfiguring Tcl with tclConfig.sh
checking for correct TEA configuration... ok (TEA 3.10)
configure: configuring Eggdrop 1.9.5
checking for Tcl configuration... found /usr/local/lib/tcl8.6/tclConfig.sh
checking for existence of /usr/local/lib/tcl8.6/tclConfig.sh... loading
checking platform... unix
checking for sin... no
checking for main in -lieee... no
checking for main in -linet... no
checking for net/errno.h... no
checking for connect... yes
checking for gethostbyname... yes
checking for Tcl linker... ${CC} ${CFLAGS} ${LDFLAGS} -shared
checking for Tcl version... 8.6.14
checking for Tcl library flags... -L/usr/local/lib -ltcl86  -lz -lpthread -lm
checking for Tcl header flags... -I/usr/local/include/tcl8.6
checking for system IPv6 support... no
checking whether to enable TLS support... no
checking whether to compile the Python module... autodetect
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating scripts/Makefile
config.status: creating src/Makefile
config.status: creating src/compat/Makefile
config.status: creating src/md5/Makefile
config.status: creating src/mod/Makefile
config.status: creating config.h
config.status: executing eggint.h commands
config.status: creating eggint.h : __EGGINT_H
config.status: eggint.h is unchanged
config.status: executing replace-if-changed commands
lush.h is unchanged
config.status: executing catch-make-rebuild commands

Operating System: FreeBSD 14.0-RELEASE-p6
IPv6 Support: no
Tcl version: 8.6.14 (threaded)
SSL/TLS Support: no
Threaded DNS core: yes

If you experience any problems compiling Eggdrop, please read the
compile guide, found in doc/COMPILE-GUIDE.

Type 'make config' to configure the modules, or type 'make iconfig'
to interactively choose which modules to compile.

sadly documentation or make files dont tell me exact what filename it looks for then i could find it and link it with
--with-sslinc=/usr/include/openssl --with-ssllib=/usr/include/openssl

i tried all combos with those directories including openssl files.

please advise where to go/ test check or try.

regards

**Comment by ia2115** [comment]
funny thing, if installing port 1.9.3 from ports i get:
checking whether to enable TLS support... autodetect
checking for openssl/ssl.h... yes

Operating System: FreeBSD 14.0-RELEASE-p6
IPv6 Support: no
Tcl version: 8.6.14
SSL/TLS Support: yes (OpenSSL 3.0.13 30 Jan 2024)
Threaded DNS core: yes


did you break something? from 1.9.3 vs 1.9.5

i git cloned 1.9.5 from here, where 1.9.3 was freebsd /usr/ports/irc/eggdrop

**Comment by ia2115** [comment]
by reading your 1.9.3 code (configure) i find out i can use 
./configure --enable-tls   

Operating System: FreeBSD 14.0-RELEASE-p6
IPv6 Support: no
Tcl version: 8.6.14 (threaded)
SSL/TLS Support: yes (OpenSSL 3.0.12 24 Oct 2023)
Threaded DNS core: yes

then it works... doh, nothing in any document or help page anywhere about this...

but hey its solved! now i need to remember now autodetect doesnt really work? or is enabled in 1.9.5 vs 3

you can close this..

thanks for great project.

regards

**Comment by vanosg** [comment]
Hi @ia2115 ,

Thanks for reporting this! A few comments here, so that we're not comparing apples to oranges, and to address a few comments you made:

Installs from repositories such as ports are often modified by the maintainers of that package (who aren't us), so its possible that they modified something.

FBSD14 is relatively new, it wasn't out when 1.9.5 was released so its possible that the libraries are in a place that Eggdrop doesn't know to look

For your last comment, --enable-tls is the default internal configuration, manually specifying it shouldn't really do anything (and thus why it's not in any doc exposed to the user). Did you do that on 1.9.5 and it worked?

Once we can find a FBSD14 machine we'll take a look at how it compiles and respond with additional details. Thanks again

**Comment by ia2115** [comment]
yes i did exactly that with the source pulled from source. and it worked with   ./configure--enable-tls
where ./configure didnt.   and yes thats also why i wondered why ports worked with 1.9.3 when 1.9.5 git compiled didnt ;)

**Comment by vanosg** [comment]
When you say 'source from source', do you mean the 1.9.5 stable release, or the most current develop branch maintained on git?

**Comment by michaelortmann** [comment]
FreeBSD includes a stable OpenSSL in the base system

So, eggdrop should not need `pkg install openssl`

For reference, on a minimal FreeBSD 14 install i get:

https://pastebin.com/AgXB5e8g

eggdrop can be made to pick up any other openssl install, like from ports, via:

`./configure --with-sslinc=/foo/bar/include/openssl/ssl.h --with-ssllib=/foo/bar/lib/libssl.so`

If after compiling, eggdrop doesnt use the lib it was linked to, `LD_LIBRARY_PATH=/foo/bar/lib/` could be used

If we have a problem with FreeBSD, i cannot see it yet. But i want to find out and fix it, and therefore i need to be able to repeat the problem or see the difference in our FreeBSD 14 setups.

**Comment by ia2115** [comment]
its very wierd, what michaelortmann says, i just tested in other jail where i didnt really do anything yet and here its working and detecting correctly:

Operating System: FreeBSD 14.0-RELEASE-p6
IPv6 Support: no
Tcl version: 8.6.14 (threaded)
SSL/TLS Support: yes (OpenSSL 3.0.12 24 Oct 2023)
Threaded DNS core: yes

and i didnt install any openssl its just base 
testjail01.archive.lokal 14.0-RELEASE-p6

wonder what triggered my source to not find any ssl.

root@testjail01:~ # find / -name 'ssh.h'
root@testjail01:~ # find / -name 'libssl.so'
/usr/lib/libssl.so

root@testjail01:~ # ls /usr/lib/ | grep ssl
libssl.a
libssl.so
libssl.so.30
ossl-modules

no sign of any ssl.h even so it detects correctly in the test
i did a find on it and nothing came up.

but must be my jail who broke the autodetect somehow, as i see it working as michael described 
i followed his steps and default bsd 14.p6 worked

so maybe just in document, put if for somereason it doesnt work try this :)

and thanks ppl for all this great input, if you need more info feel free to write, and i will do my best to help.
nice to see really live development, and i use this eggdrop a lot.

**Comment by michaelortmann** [comment]
Could have been related to #1554
