### ISSUE TITLE
Python issues

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#1587]
Documenting a few things here from a fresh install

Without python installed, this appears in ./configure
```
./configure: line 10630: EGG_PYTHON_ENABLE: command not found
```

With python3 installed but not the dev files:
```
./configure: line 10630: EGG_PYTHON_ENABLE: command not found
```
and
```
checking  version is >= 3.8.0... no ()
configure: WARNING: Eggdrop requires python version 3.8.0 or higher

  There was an issue with your python installation.
  Please read python.mod/config.log for more details.
  The python module will be disabled.
```

and still the same error as above once python3-dev is installed.

In addition to fixing this, we probably need to document somewhere what libraries are required to run python; similar to what we have done for Tcl

**Comment by Rajinikanth-Kakarla** [comment]
Go for a clean installation of Python with the latest one and if there are any requirements files then install them using the following command
`pip3 install -r requirements.txt`
