### ISSUE TITLE
Review CTCP CHAT IP selection logic

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#159]
In the context of #151 and #90, it came up that it is not at all obvious or trivial how eggdrop selects which IP to tell a user to connect to after /ctcp chat.

Questions:
a) Eggdrop is listening on multiple specific IPs, mixed ipv4/ipv6, localhost, LAN ips, ... which one to tell the user?
b) Eggdrop is listening on all interfaces, which one to tell the user? vhost4? vhost6? prefer-ipv6? self-lookup?
c) we have nat-ip for v4 only now, but this forces eggdrop to tell users that IP, would that not make sense for v6 as well?

**Comment by thommey** [comment]
maybe we need a /ctcp bot chat6/chat4 command to specify?

**Comment by thommey** [comment]
Proposal for a) in order of decreasing priority, skipped if not listening on it:
- nat-ip (v4 only though?)
- External IPv4 (not 192.168/24, 172.16/12, 10/8) (prefer the one also set as vhost4)
- External IPv6 (not ::1/128, fe80::/10) (prefer the one also set as vhost6)
- LAN IPv4
- LAN IPv6
- Localhost IPv4
- Localhost IPv6

how should prefer-ipv6 play into this? preferring ipv4 over ipv6 regardless is not future proof

**Comment by thommey** [comment]
b) is actually a special case of a) where all available IPs are being listened on, so solving a) is enough

**Comment by thommey** [comment]
maybe dcc-ip4 dcc-ip6 settings? (renaming nat-ip)

**Comment by vanosg** [comment]
Here's what I have working so far:

If listen_addr is valid, that is what is used, skipping all the below. If not....

If the bot is listening on either :: or 0.0.0.0,     //This means listen-addr is not set to a specific IP
&nbsp;&nbsp;&nbsp;&nbsp; if prefer_ipv6 is set, and the bot is listening on an ipv6 socket, 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try to use the IP in vhost6 
if vhost6 is attempted but invalid, or prefer_ipv6 is 0  //again, listen-addr is not set, so it doesn't factor
&nbsp;&nbsp;&nbsp;&nbsp;try to use vhost4
&nbsp;&nbsp;&nbsp;&nbsp;if vhost isnt valid (ie, 0.0.0.0 or non-existent)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lookup hostname, using first the IPv-type indicated by prefer-ipv6 setting, then try the other

if we're trying to use ipv6 but can't get a valid ipv6 ip, OR we're only using ipv4, then we check for natip, and if present, it trumps anything set in vhost4 (and listen-addr), if set. nat_ip does not trump (obviously) if a valid ipv6 address was found and used above.

**Comment by Robby-** [comment]
I think having a CHAT4 and CHAT6 command to specify would be good to have indeed, because when you have a bot that connects to IRC using IPv6 (and thus vhost6), and users that do not have IPv6 connectivity and want to get into the partyline, it will fail because the bot doesn't know that the user has IPv4 connectivity only. This way I can tell those users to specifically use CHAT4 and be done with it. This combined with new dcc-ip4 and dcc-ip6 settings would be great.

**Comment by thommey** [comment]
if listen-addr is a LAN address, we still need self-lookup and use that external IP.

**Comment by vanosg** [comment]
Hmm. What if I'm running a LAN net of eggdrops, and don't want to provide the external IP? Or if I'm listening on 127.0.0.1 only...  Are there other use cases where I want to provide what I set in listen-addr? Maybe add a 'resolve-lan' option?
