### ISSUE TITLE
internal bans override channel exempts

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#16]
| Trac | Data |
| --: | :-- |
| Ticket | 16 |
| Reported by | John |
| Status | new |
| Component | Module: channels.mod |
| Priority | minor |
| Milestone | 1.8.0 |
| Keywords | bans exempts |
| Version | 1.8.0 CVS |

to reproduce: set sticky ban in the bot on a wide host  _!_@_.charter.net
set  .chanmode #channel +user-exempts
then manually set exempt:  *!e-mail@_.charter.net in the channel

when client joins, the bot will remove the channel exempt and kick/ban.

This should _not_ happen when the .chaninfo  is  +user-exempts

This bug has been confirmed by 3 people in efnet.

Comment # 1 From Rumen Stoyanov 2009-11-17 02:49:35

I find it natural to have internal bans to override external exempts. The
userexempts setting is intented to allow regular users to place exempts,
without the bots removing them. This doesn't mean, however, that user exempts
should override bot bans. This is against the philosophy eggdrop is built
around.

Not a bug. This entry is quite old (Feb 2008), so I'll change it's status to
INVALID without waiting for a reply. If the reporter or anyone else has
objections, feel free to reopen and comment.

Comment # 2 From John 2009-11-17 08:30:25

I couldn't disagree more. Please read the original writeup closely.

External exempts are (presumably) set by live, breathing people who:

a) May not have bot access to remove a ban/invalid/improper internal ban.

b) More importantly: may be trying to selectively "permit" individuals to join
on a narrower scope than the internal ban.

As an example:

Suppose you want to ban all of charter.net.
You would set an internal ban like _!_@*.charter.net 
Then a live OP in the channel wants to permit 1 individual to join the channel.

Presumably, the feature on the bots:  +user-exempts   should allow an external
channel exempt to take priority over a (larger) internal ban.

I agree this is an old report that has not been addressed. I have not confirmed
that this bug report still applies to 6.1.19 but it is likely still a problem
waiting to be resolved.

Comment # 3 From John 2009-11-17 08:36:51

Followup:

The definition given with .HELP chaninfo appears to support my conclusion:

userexempts    Allow exempts to be made by users directly? If
               turned off, the bot will require all exempts to be made
               through the bot's console.

By enabling +userexempts, we should be able to set 'external' (user) exempts in
the channel which would override internal bans.

As it stands now, exempts must be set inside the bot and made sticky in order
to override a larger ban scope and permit specific users to join a channel.

Comment # 4 From Thomas Sader 2010-01-16 06:49:23

Let's take a look at a few example cases to illustrate analogous situations.
The following terms are used:
"channel op" - user who is not known in the bot and has operator status on the
channel
"eggdrop op" - user who is known in the bot and has at least |o on the channel
"eggdrop user" - user who is known in the bot
"he" - he/she ;-)
## Case 1

There's an eggdrop user with the +d flag on the channel (deop). This deop flag
is placed by an eggdrop op. Now a channel op attempts to op that guy. Result:
Eggdrop ignores the channel op and follows its eggdrop op orders and deops the
guy.
## Case 2

There's an eggdrop user with the +k flag on the channel (autokickban). This
flag is placed by an eggdrop op. Now a channel op invites that guy and he joins
even though he has an active ban placed (invites override bans on most ircds).
Result: Depends on 'enforcebans'. +enforcebans: Eggdrop kicks the guy.
-enforcebans: Eggdrop doesn't kick the guy.
## Case 3

There's an eggdrop exempt placed internally on \_!_@_.aol.com. A channel op bans
*!_@_.com now. -userbans: immediately removed. +userbans: allowed. Assuming
+userbans now. Eggdrop places the exempt, effectively overriding the channel
op's choice to ban all \*!_@*.com users. In no way can that channel op override
eggdrop's internal exempt with a channel ban.
## Interpretation:

Let's start with case 3 because it's analogous to your case. +userbans is just
a general flag that either allows channel ops to place bans or not. In general,
not taking into account if they override internal exempts.
- Conclusion: +userexempts is the same thing, it's a generic flag, either
  _immediately_ revoke _all_ exempts placed by channel ops or don't.
  Unconditionally. Your case has nothing to do with the +userexempts flag,
  because it's a special case of channel ops overriding eggdrop ops'
  instructions.

Case 2 shows us that the situation can occur that a channel op uses his op
power to work around eggdrop's internal orders. There is a flag which
determines if he can or cannot do so. It's called +enforcebans.
- Conclusion: There is a flag which determines if a channel op can work around
  an eggdrop ban by inviting people - enforcebans. There is no flag which
  determines if a channel op can work around an eggdrop ban by exempting people.

Case 1 is just an illustration of the defaults of eggdrop. It defaults to
follow its orders ignoring channel ops that aren't known.
- Conclusion: A flag controlling permission for channel ops to work around
  eggdrop internal bans should default to not allow it. Eggdrops current
  behaviour is consistent with that.
## Suggestion

At this point, I'd suggest either making -enforcebans not only avoid kicking
users but also allow exempts to be placed that override eggdrop internal bans,
OR a new flag that does so.

Maybe I went a little fast over the "it has nothing to do with +userexempts"
portion, because that point seems to be the disagreement, but it is a special
case if channel ops work around eggdrop's internal instructions. Whenever they
can, there's a flag to explicitely allow that. After all, someone wanted to ban
all users with _!_@*.com, placing that ban in eggdrop, with no exempts in mind
(or he would've added them to eggdrop as well). Channel ops are never equal to
eggdrop ops, eggdrop ops can be protected, revenged, ... Channel ops can't.
Comment #5 From Thomas Sader 2010-01-16 06:56:59

Quick note:

I totally see how you prefer the judgement of breathing ops to eggdrop, it's
the correct way to think about it, but then again, why not add the ops you
trust to eggdrop and give them permission to add eggdrop internal exempts?
Eggdrop even has flags to restrict the power of channel ops (-userbans,
-userexempts), the concept is that instructions should be made to eggdrop, not
to the channel.

Comment # 6 From John 2010-01-16 09:23:12

Thomas:

CASE 6:

CHARTER.COM users have been harassing your channel so you sticky ban
_!_@*.charter.com in the bots ban list.

(I believe this is a valid usage of bots and sticky bans).

BILLYBOB (also a charter user) would like to join the channel.

NO BOT OWNERS are present at the time.

SALLY is a channel OP but has no bot access. She only has +o for the channel.

SALLY sets mode +e  BILLYBOB!asdf@blah.charter.com

(Lets assume this matches BILLYBOB's address).

The bot has  +userexempts  set for the channel.

It would seem that +user-exempts would PERMIT sally to exempt BILLYBOB and
allow him to join the channel.

The IRC server allows BILLYBOB to join, and the eggdrop removes the exempt and
kicks billybob.

If the bot is going to REMOVE a valid channel exempt set by a valid OP when
+user-exempt is set internally for the channel, then what is the point of
+user-exempt ?

Comment # 7 From John 2010-01-16 09:30:46

QUICK NOTE:

To address the original objection more specifically:

The very definition of EXEMPTs is to 'override' bans.

It seems to me that you would want a specific external exempt to override a
more general broad internal ban.

The same argument for:  Specific channel exempts override more broad channel
bans.

Exempts are there to override bans. +user-exempt is there to allow users to set
channel exempts.

IMHO:

+user-bans  +user-exempts

are flags that you set when you TRUST the channel ops to manually set bans and
exempts. They should override the bot controls. If you don't want users to set
channel exempts, then set  -user-exempts  in the bot.

**Comment by Pixelz** [comment]
There's no clear right or wrong on this one. The default behavior can be changed via `bind out` if desired.
