### ISSUE TITLE
Update tcl.m4

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#1615]
A lot of version and path detection stuff and whatnot changed in never versions of upstream tcl.m4

https://core.tcl-lang.org/tclconfig/finfo?name=tcl.m4

But ive got a hard time updating eggdrops https://github.com/eggheads/eggdrop/blob/develop/m4/tcl.m4

coze there is a lot off difference and no doc about how to get from A to B

**Comment by vanosg** [comment]
Close

**Comment by vanosg** [comment]
Closed by #1649
