### ISSUE TITLE
Clean up eggdrop.conf

### ISSUE THREAD

**Issue by Pixelz** [eggheads/eggdrop#164]
Get rid of redundant words in comments that provide no information. For example, the phrase `this setting` appears 67 times in the file.

Remove settings believed to be useless. Some examples:
- `paranoid-telnet-flood`
- `hourly-updates`
- `quick-logs` should default to 1 and be removed

**Comment by vanosg** [comment]
What are you defining as 'useless'? Those settings are all used by eggdrop, they have not been abandoned. Can you provide any further reasons?

67 times in a ~1500 line file isn't bad, either :P

**Comment by Pixelz** [comment]
The argument is that these settings are never changed by anyone, and thus should be removed from the config. The listed ones are just examples, there might be more.

`paranoid-telnet-flood` defaults to 1. It makes Eggdrop boot friends (+f) flooding on the partyline (and not exempt them). Even if you get booted you can just log straight back in. You have to flood pretty heavily in order to get booted and disabling it would introduce a potential endless DoS sink.

`hourly-updates` defaults to 00 (00 minutes, at the top of the hour) changes when Eggdrop writes files. The files that Eggdrop write are so tiny that the IO is barely measurable on a modern system.

`quick-logs` is off by default. If enabled, it makes Eggdrop write log files quicker (but still not instantly). Same thing here, this setting barely made sense 20 years ago, and today it certainly doesn't.

As for the remark regarding the comments, a lot of them are unclear and they use a lot of redundant text. The config is huge and a massive undertaking for new users. Anything we can do to make it shorter, without removing settings that people actually change would be good.

**Comment by andy5995** [comment]
I worked on this a little today. Am I on the right track?
[164.patch.1.txt](https://github.com/eggheads/eggdrop/files/441552/164.patch.1.txt)

**Comment by eagleusb** [comment]
It's true that it is a pain every time we need to open eggdrop.conf and configure It. 
Maybe we can split it into multiple files and use includes ?

A 1k lines configuration file for an app is a bad idea too.

**Comment by ZarTek-Creole** [comment]
Maybe related to #1288, indeed thinning the configuration files compared to the modules compiling maybe one of the solutions to go to the eggdrops configuration for new users and at the same time why keep configurations that are useless for an eggdrop who doesn't use them?
