### ISSUE TITLE
Ident failed for "my-ip" Connection refused

### ISSUE THREAD

**Issue by ia2115** [eggheads/eggdrop#1683]
im using latest eggdrop from github here, i keep getting Ident failed for 172.16.1.12: Connection refused
im not using ident, and the new install doesnt have any user file yet.

also im on freebsd 14.1 

started the eggdrop with

./eggdrop -m mybot.conf

from logfile:
[04:16:58] Telnet connection: 172.16.1.12/56895
[04:16:58] Ident failed for 172.16.1.12: Connection refused

#!/home/cbot/my-eggdrop

##### BASIC SETTINGS #####

# This setting defines the username the bot uses on IRC. This setting has no
# effect if an ident daemon is running on your bot's machine. See also ident
# module.
set username "mybot"
set admin "Lamer <email: lamer@lamest.lame.org>"
set network "EFNET"
set timezone "CET"
set offset "1"

set prefer-ipv6 0
set my-ip 172.16.1.12

set max-logs 20
set max-logsize 0
set raw-log 0

logfile mco * "logs/eggdrop.log"

set log-time 1

set timestamp-format {[%H:%M:%S]}
set keep-all-logs 0
set logfile-suffix ".%d%b%Y"
set switch-logfiles-at 300
set quiet-save 0
set check-ident 0

set console "mkcoblxs"

set userfile "my.user"
#set pidfile "pid.mybot"
set help-path "help/"
set text-path "text/"
set motd "text/motd"
set telnet-banner "text/banner"
set userfile-perm 0600

listen 32768 all

set remote-boots 2
set share-unlinks 1
set protect-telnet 0

set dcc-sanitycheck 0
set require-p 1
set open-telnets 0
set stealth-telnets 0

set stealth-prompt "\n\nNickname.\n"

set use-telnet-banner 0
set connect-timeout 15
set dcc-flood-thr 3
set telnet-flood 5:60
set paranoid-telnet-flood 1

#set ssl-privatekey "eggdrop.key"
#set ssl-certificate "/home/cbot/my-eggdrop"
#set ssl-capath "/etc/ssl/"
set nat-ip "172.12.1.12"
#set reserved-portrange 2010:2020
set ignore-time 15
set hourly-updates 00
set notify-newusers "$owner"
set default-flags "hp"
set whois-fields "url birthday"
set must-be-owner 1
unbind dcc n simul *dcc:simul
set max-socks 100
set allow-dk-cmds 1
set dupwait-timeout 5
set cidr-support 0
set show-uname 1

set mod-path "modules/"

loadmodule pbkdf2
loadmodule channels

set chanfile "my.chan"
set force-expire 0
set share-greet 0
set use-info 1
set allow-ps 0

# The following settings are used as default values when you .+chan #chan or .tcl
# channel add #chan. Look below for explanation of every option.

set default-flood-chan 15:60
set default-flood-deop 3:10
set default-flood-kick 3:10
set default-flood-join 5:60
set default-flood-ctcp 3:60
set default-flood-nick 5:60
set default-aop-delay 5:30
set default-idle-kick 0
set default-chanmode "nt"
set default-stopnethack-mode 0
set default-revenge-mode 0
set default-ban-type 3
set default-ban-time 120
set default-exempt-time 60
set default-invite-time 60

set default-chanset {
        -autoop         -autovoice
        -bitch          +cycle
        +dontkickops    +dynamicbans
        +dynamicexempts +dynamicinvites
        -enforcebans    +greet
        -inactive       -nodesynch
        -protectfriends +protectops
        -revenge        -revengebot
        -secret         -seen
        +shared         -statuslog
        +userbans       +userexempts
        +userinvites    -protecthalfops
        -autohalfop     -static
}
# .+chan #channel. Check also .help chanset and .help chaninfo.
#channel add #mychan

loadmodule server
set net-type "EFnet"
set nick "mybot"
set altnick "myb0t"

set realname "/msg hello"

bind evnt - init-server evnt:init_server

proc evnt:init_server {type} {
  global botnick
  putquick "MODE $botnick +i-ws"
#  putserv "PRIVMSG NickServ :identify <password>"
}

set default-port 6667

server add efnet.deic.eu 6697
server add efnet.portlane.se +6697

#server add you.need.to.change.this +6667
#server add another.example.com 6669 password
#server add 2001:db8:618:5c0:263:: 6669 password
#server add ssl.example.net +7000

set extended-join 1

set msg-rate 2
set keep-nick 1
set quiet-reject 1
set lowercase-ctcp 0
set answer-ctcp 3
set flood-msg 5:60
set flood-ctcp 3:60
set server-cycle-wait 60
set server-timeout 60
set check-stoned 1
set serverror-quit 1
set max-queue-msg 300
set trigger-on-ignore 0
set exclusive-binds 0
set double-mode 1
set double-server 1
se
set learn-users 0
set wait-split 600
set wait-info 180
set mode-buf-length 200

unbind msg - ident *msg:ident
unbind msg - addhost *msg:addhost

set opchars "@"
set no-chanrec-info 0

set prevent-mixing 1
set max-dloads 3
set dcc-block 0
set xfer-timeout 30
set share-compressed 1

set files-path "/home/cbot/filesys"
set incoming-path "/home/cbot/filesys/incoming"
set upload-to-pwd 0
set filedb-path ""
set max-file-users 20
set max-filesize 1024

loadmodule notes
set notefile "my.notes"
set max-notes 50
set note-life 60
set allow-fwd 0
set notify-users 0
set notify-onjoin 1

# This next line checks if eggdrop is being executed from the source directory
if {[file exists aclocal.m4]} { die {You are attempting to run Eggdrop from the source directory. Please finish installing Eggdrop by running "make install" and run it from the install location.} }

loadmodule console
set console-autosave 1
set force-channel 0
set info-party 0

loadmodule seen
loadmodule uptime
loadmodule python

source scripts/autoscripts.tcl
source scripts/alltools.tcl
source scripts/action.fix.tcl
source scripts/dccwhois.tcl
source scripts/userinfo.tcl
loadhelp userinfo.help

#source scripts/compat.tcl

if {[info exists net-type]} {
  switch -- ${net-type} {
    "EFnet" {
      # EFnet
      source scripts/quotepong.tcl
    }
    "0" {
      # EFnet
      source scripts/quotepong.tcl
    }
  }
}

drwxr-xr-x   4 cbot wheel      13 Mar  9 20:51 ..
-rw-r--r--   1 cbot wheel    2510 Sep  5 03:19 FEATURES
-rw-r--r--   1 cbot wheel    9496 Sep  5 03:19 README
-rwxr--r--   1 cbot wheel    2329 Mar  9 19:52 mybot.botchk
-rw-------   1 cbot wheel      88 Sep  5 04:16 my.chan
-rw-r--r--   1 cbot wheel    5373 Sep  5 04:16 mybot.conf
-rw-------   1 cbot wheel      52 Sep  5 03:36 my.notes
drwxr-xr-x   5 cbot wheel      25 Sep  5 03:19 doc
lrwxr-xr-x   1 cbot wheel      14 Sep  5 03:19 eggdrop -> eggdrop-1.10.0
-rwxr-xr-x   1 cbot wheel 1506248 Sep  5 03:19 eggdrop-1.10.0
-rw-r--r--   1 cbot wheel   16535 Mar  9 19:08 eggdrop-basic.conf
-rw-r--r--   1 cbot wheel   68478 Mar  9 19:08 eggdrop.conf
-rw-------   1 cbot wheel    3272 Mar  9 19:08 eggdrop.key
drwxr-xr-x   3 cbot wheel       3 Mar  9 19:08 filesys
drwxr-xr-x   4 cbot wheel      26 Sep  5 03:19 help
drwxr-xr-x   2 cbot wheel      43 Sep  5 03:19 language
drwxr-xr-x   2 cbot wheel       5 Apr 15 06:00 logs
lrwxr-xr-x   1 cbot wheel      14 Sep  5 03:19 modules -> modules-1.10.0
drwxr-xr-x   2 cbot wheel      20 Sep  5 03:19 modules-1.10.0
-rw-r--r--   1 cbot wheel       6 Sep  5 04:16 pid.mybot
drwxr-xr-x   2 cbot wheel      24 Mar  9 19:08 scripts
drwxr-xr-x   2 cbot wheel       4 Mar  9 19:08 text

any advise how to fix this? or something i can try, i have no clue why it complains over something i dont have configured/ use.

unless its default and you need to specific ask it not to.

**Comment by vanosg** [comment]
Hi @ia2115 , thanks for checking in. We try to only use GitHub for tracking programming issues/bugs. For troubleshooting questions on Eggdrop similar to yours, please join #eggdrop on Libera and folks there can help you faster than going through back and forth here. Thanks!
