### ISSUE TITLE
1.10.0 stucked after restart

### ISSUE THREAD

**Issue by aleksandrov89** [eggheads/eggdrop#1701]
[08:35:00] Restarting ...
[08:35:00] Module unloaded: console
[08:35:00] Sending 'share end' to all sharebots...
[08:35:00] Unloaded sharing module, flushing tbuf's...
[08:35:00] Module unloaded: share
[08:35:00] Unloading transfer module, killing all transfer connections...
[08:35:00] Module unloaded: transfer
[08:35:00] Module unloaded: ctcp
[08:35:00] Stagnant modules; there WILL be memory leaks!
[08:36:22] * Please report problem to https://github.com/eggheads/eggdrop/issues
[08:36:22] * Check doc/BUG-REPORT on how to do so.
[08:36:22] * Last bind (may not be related): evnt:init_server
[08:35:00] * Wrote DEBUG
[08:35:00] * SEGMENT VIOLATION -- CRASHING!

Debug (eggdrop v1.10.0) written Wed Oct 16 08:35:00 2024
Patch level: stable
Tcl library: *unknown*
Tcl version: *unknown* (header version 8.6.13)
Tcl is threaded
Compiled with IPv6 support
Compiled with TLS support
Configure flags: none
Compile flags: gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H -I/usr/include/tcl8.6 
Link flags: gcc -lpthread
Strip flags: touch
Last bind (may not be related): evnt:init_server
IDX ADDR                                     + PORT NICK        TYPE  INFO
--- ---------------------------------------- ------ ----------- ----- ---------
3   0.0.0.0                                    3113 (telnet)    lstn  3113
6   x.x.x.x                          + 6697 (server)    serv  (lag: 0)
7   127.0.0.1                                 38510 alexandroff chat  flags: cpTEp/0

Compiled without extensive memory debugging (sorry).
Open sockets: 3 (listen), 6 (TLS), 7 (outbuf: 000073), 8 (file), done.

**Comment by michaelortmann** [comment]
Thank you for the report! If you are able to enable debug logging with `.console +d`  it would tell us the name(s) of the module(s) that are stagnant.

**Comment by michaelortmann** [comment]
i can reproduce. if python mod is loaded, it cannot be unloaded. so we need to add it the the stagnant module exclude check list here: https://github.com/eggheads/eggdrop/blob/277ec01e0aacfc29c8a0ce3383fe1999ca2414ce/src/main.c#L876-L877

**Comment by michaelortmann** [comment]
python mod depends on other mods. i dont know how to handle such dependencies, or if a restart is even possible with python mod loaded.

**Comment by michaelortmann** [comment]
with python mod loaded and .restart, and all debug options enabled, here is a full stacktrace:

https://pastebin.com/qdjhVXe6

**Comment by Alcheri** [comment]
I use a script to perform several bot functions, one of which is to restart the bot (below). 

```plaintext
        restart  {
          if {[matchattr $hand m]} {
            puthelp "PRIVMSG $channel :Restarting..."
            utimer 5 [list restart]
	        putlog "<<$nick@$chan>> #$hand# $cmd"
          } else {puthelp "PRIVMSG $channel :$nick, you're not a Global Bot Master"}
        }
```
That function produces:
>Stagnant modules; there WILL be memory leaks!
>* Wrote DEBUG
>* SEGMENT VIOLATION -- CRASHING!

Debug:
<code>
Debug (eggdrop v1.10.0) written Mon Jan 20 13:20:02 2025
Patch level: stable
Tcl library: *unknown*
Tcl version: *unknown* (header version 8.6.13)
Tcl is threaded
Compiled with IPv6 support
Compiled with TLS support
Configure flags: '--with-handlen=32'
Compile flags: gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H -I/usr/include/tcl8.6 
Link flags: gcc -lpthread
Strip flags: touch
Last bind (may not be related): Wendouree:input:data
IDX ADDR                                     + PORT NICK      TYPE  INFO
--- ---------------------------------------- ------ --------- ----- ---------
4   5.161.73.70                              + 6697 (server)  serv  (lag: 0)

Compiled without extensive memory debugging (sorry).
Open sockets: 4 (TLS), 5 (file), done.
</code>
I have unloaded the Python plugin and all works as expected.
