### ISSUE TITLE
eggdrop.tcl doesn't exist

### ISSUE THREAD

**Issue by Alcheri** [eggheads/eggdrop#1719]
In all examples of Python scripts the following is included:

`from eggdrop.tcl import putmsg, putlog`

In all cases, that line creates an error message stating that 'eggdrop.tcl' does _not_ exist. 

Removing that line and changing the previous line to `from eggdrop import *` and then prefixing all references of putmsg & putlog with tcl. solves that problem.

`tcl.putlog()
tcl.putmsg()`

**Comment by vanosg** [comment]
The issue here was loading the python script before scripts/alltools.tcl, where the 'putmsg' command is located. putmsg didn't exist until after the script was loaded and thus couldn't be found. 

Load your python scripts after alltools.tcl, kids!
