### ISSUE TITLE
Add NetBSD tclConfig.sh paths to tcl.m4

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#175]
NetBSD has tclConfig.sh at /usr/pkg/lib/tclConfig.sh and /usr/pkg/tcl/lib/tclConfig.sh, possible report this upstream as well.

Found by: fhorst

**Comment by vanosg** [comment]
Confirmed:   tcl-8.6.5nb1, on NetBSD 7.99.28

```
$ pkg_info -L tcl|grep tclConfig.sh
/usr/pkg/lib/itcl4.0.4/itclConfig.sh
/usr/pkg/lib/tclConfig.sh
```

**Comment by vanosg** [comment]
```
`ls -d ${prefix}/lib 2>/dev/null` \
```

If I'm reading that correctly, that line from tccl.m4 should catch tclconfig.sh in that type of install, as PREFIX is usually /usr/pkg on NetBSD. It may be possible that the user has a wonky or otherwise customized install? Is he available to comment or confirm what $PREFIX returns?
