### ISSUE TITLE
Failed telnet logins due to invalid handles are not logged to the logfile

### ISSUE THREAD

**Issue by Robby-** [eggheads/eggdrop#184]
In both the partyline and logfile, this appears:
`[09:05:23] Telnet connection: some.hostname.tld/50349`

But this:
`[09:05:26] Refused UNKNOWN@some.hostname.tld (invalid handle: Test)`
only appears in the partyline.

This should really be logged to the logfile as well, as such information can be useful, and should probably be covered by the `o` flag.

The current logfile flags I'm using are `mscow`, my console flags are `mjkcobxw`.

Edit: Turns out this was because this message is logged to the `b` flag (`LOG_BOTS`).

**Comment by ghost** [comment]
Does this link, logically, to #109 (particularly what it's thought to address)?
