### ISSUE TITLE
Refuse msg commands with empty password set

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#188]
Most of our msg commands require a password, but if the user hasn't set one, seem to work without it.
E.g. /msg bot hello, /msg bot rehash.
Found by: elWanderino

**Comment by vanosg** [comment]
I will note that as I write this patch, that the code structure appears to reflect that this is a feature, not a bug. However, using the partyline requires a password, and the functionality of eggdrop is extremely limited via just msg commands, so I'm going to go ahead and remove this no-pass functionality. But, I do want to document this and see if anyone else can think of a use case where a user would intentionally not want to set a password.
