### ISSUE TITLE
Cosmetic alltools.tcl update

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#190]
Suggestion for "alltools.tcl" upgrade (were deemed unnecessary).

**Comment by Cizzle** [comment]
The suggested replacement for "ordnumber" is incorrect. The default should return "${number}th", the first case match should be "{1$}" and as new first case match it should have "{1[123]$} { return ${number}th }".
Whether this is "better" or faster than the now existing one I leave in the midst.
A suggestion of myself would be to replace the "[expr [string length $string] - 2]" to "end-1".

**Comment by Cizzle** [comment]
The isnumber replacement should be called differently as other procs relying on this proc now don't expect signs, scientific notation or decimals.
The existing isnumber proc regards "007" as a number but I guess this is not unwanted?

**Comment by Cizzle** [comment]
The existing docs for number_to_number (why not number_to_text?) should be changed to have 0 included.
The suggested replacement again has flaws: the $sign isn't used at all (and returning "$sign$word" could return "Negative 16" which might be unwanted). I'm not sure having that "Negative " is a plus at all.
And again whether this is "better" or faster than the now existing one I leave in the midst.

**Comment by vanosg** [comment]
Hi @maimizuno,

  Thanks for the suggestions- we've reviewed your suggestions agree with Cizzle's comments. If you are interested in revisiting your edits to address those issues and then resubmitting, we'll be glad to re-evaluate them for inclusion into the next version of eggdrop. Thanks again for all your submissions thus far, we're excited to see your next one!

**Comment by maimizuno** [comment]
Sorry for delay in replying; was in hospital for 3 months.

Cizzle was correct in finding the errors (especially, the DEFAULT); can't believe I missed that one. The combo one was meant to catch 11 12 13 which are "th" endings (the "teens" are unique from the others multiples of ten): 11th [eleventh], 12th [twelfth], & 13th [thirteenth].

I'll repair it shortly.

**Comment by maimizuno** [comment]
;# Allows a number sign (only one), SCINOT, and any form of decimal ( 5, 5. , .5 , 5.5 , 5.0 , 0.5 )
proc isnumber number { regexp -- {^[+-]?(\d+|\d+\.\dASTERISK|\dASTERISK\.\d+)([Ee][+-]\d+)?$} $number }

proc ordnumber number {
	if ![isnumber $number] { error "Illegal non-numeric value: $number" }
	switch -regexp -- $number {
		{1[123]$} { return ${number}th }
		{1$} { return ${number}st }
		{2$} { return ${number}nd }
		{3$} { return ${number}rd }
		default { return ${number}th }
	}
}

Test:
foreach a [sequence 0 .. 30] { puts "${a}: [ordnumber $a]" }

0: 0th
1: 1st
2: 2nd
3: 3rd
4: 4th
5: 5th
6: 6th
7: 7th
8: 8th
9: 9th
10: 10th
11: 11th
12: 12th
13: 13th
14: 14th
15: 15th
16: 16th
17: 17th
18: 18th
19: 19th
20: 20th
21: 21st
22: 22nd
23: 23rd
24: 24th
25: 25th
26: 26th
27: 27th
28: 28th
29: 29th
30: 30th

I do not know the "most efficient way" to detect / remove leading zeroes (including the infamous "fake octal" values of 08 and 09); I am open to input on the matter. I know there are some regexps that can "remove" (not report) certain matches, similar to "(!?=0+)\d+" or somesuch, but I'm not personally familiar with them.

**Comment by maimizuno** [comment]
As far as "number_to_number," yes, "number2text" would be a better name, and the extra code was an attempt to do sanity checks. A simple, one-line LINDEX could do the entire job without sanity checking, but I was just trying to be thorough. I re-submit it as follows:

proc number2text number {
	if ![isnumber $number] { error "Illegal non-numeric value: $number" }
	if { $number < 0 } { set sign "negative " ; set number [ expr abs( $number ) ] } { set sign "" }
	# set number [string range $number 1 end] also would work, but since we're treating it as a number ... (OK to delete this comment)
	set word [lindex [list zero one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen] $number]
	if [string eq "" $word] { set word $number }
	return ${sign}$word
}

Line #2 sets $sign to "" if $number >= zero.

To the comment re: the value of returning the word "negative" with the value: if the value is negative, falsely replying "five" instead of "negative five" would be an absolute logic error, depending on the script's purpose (i.e. scientific work). I also lower-cased the returned text above.

And I didn't miss the pun (well played): "I'm not sure having that 'Negative ' is a plus at all."

**Comment by Cizzle** [comment]
I've edited your messages to use Code-formatting as `\.` turned to `.` and "ASTERISK" or "_" should of course be "*". Indentation is better then too.

My previous comment about the `isnumber` proc stays: it should be called differently as other procs (e.g. ordnumber) relying on this proc now don't expect signs, scientific notation or decimals.

The `number_to_number` (or `number2text`) proc still has a, to my feeling, inconsistency: calling it with "-777" will return "negative 777" while this, IMHO, should remain "-777". Adding `if { $number > 15 || $number < -15 } { return $number }` after the `isnumber` check would solve that and obsolete the `if [string eq "" $word] { set word $number }`.

Rest looks fine. A PR (including doc changes) would be advised for easy integration.

**Comment by maimizuno** [comment]
@Cizzle : I offer it up as a suggestion only; feel free to integrate as best you feel (if you even think it worthy of inclusion / updating).

**Comment by ghost** [comment]
Was a bad idea; I shouldn't have filed this.
