### ISSUE TITLE
resetchan fails with flags beI

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#197]
In egg1.8+infinitinfo (with the whois/bot $botname patch), RESETCHAN fails with some of the flags.

flag w [WHO]: performs gets a list of current channel members

flag t [TOPIC]: gets the current channel topic

flag m [MODE]: get the current channel mode

flag b [BANLIST]: =supposed= to get the current list of channel bans. Does nothing, returns an empty string (""). No output to the server, as per console mode +v

flag e [EXEMPTLIST]: =supposed= to get the current list of channel exempts. Does nothing, returns an empty string (""). No output to the server, as per console mode +v

flag I [INVEXLIST]: =supposed= to get the current list of channel invexes. Does nothing, returns an empty string (""). No output to the server, as per console mode +v

Has this already been patched and I have not seen it yet?

**Comment by vanosg** [comment]
Grab the most recent development snapshot and try it again... resetchan was modified a few commits back, maybe that fixes what you're seeing? If not, please include exact examples of code that is/is not working, so that we can gauge context a little better. Thanks!

**Comment by ghost** [comment]
Having freshly downloaded the "development" snapshot a couple of hours ago:

[2016-03-02 06:24:38 PST (-0800): domino@Pi] ~/bots/1.8/
$ ./eggdrop -v
Eggdrop v1.8.0+tclconfig (C) 1997 Robey Pointer (C) 2010 Eggheads
  (patches: CVS 1451356129 tclconfig)
Configured with:  '--enable-tls' '--enable-strip' '--enable-ipv6'
Compiled with: IPv6, TLS, handlen=32

&lt;Domino> :: format:date 1451356129 domino
&lt;Brittany> 2015-12-28 18:28:49 -0800

(This is 2015-12-29 02:28:49 UTC)

.**\* Notice the copyright date of "2010" ***

[2016-03-02 06:17:15 -0800] -Scorpion- armv6l 32-bit GNU/Linux (Linux) [Pi] :: EGGDROP v1.8.0+tclconfig :: NICKLEN 9 :: HANDLEN 32 :: TCL v8.6.5 :: &lt;SNIP: script list> (Wed, 13 Jan 2016, 01:29:41 PST)

The tcl-commands.doc is still out of date as reported in bug #172, showing a 2010 version. I've _SEEN_ a version of it with the updated info for RESETCHAN, but, it might be for 1.6.21.

-rwxr--r-- 1 domino domino 99658 Feb 26 21:44 tcl-commands.doc

Eggdrop Tcl Commands
Last revised: October 24, 2010

  resetchan &lt;channel> [flags]
    Description: rereads in the channel info from the server. If flags are
      specified, only the required information will be reset, according to
      the given flags. Available flags:
        b - reset channel bans
        e - reset channel exempts
        I - reset channel invites
        m - refresh channel modes
        t - refresh channel topic
        w - refresh memberlist
    Returns: nothing
    Module: irc

[2016-03-02 06:20:06 -0800] 
&lt;Domino> .tcl resetchan #BotHouse a
&lt;Scorpion> [TCL (1ms)] invalid reset flags: a
&lt;Domino> .tcl resetchan #BotHouse b
 &lt;Scorpion>  [!m] MODE #BotHouse +b
 &lt;Scorpion>  [m->] MODE #BotHouse +b
 &lt;Scorpion> [TCL (28ms)] 
 &lt;Domino> .tcl resetchan #BotHouse e
 &lt;Scorpion>  [!m] MODE #BotHouse +e
 &lt;Scorpion>  [m->] MODE #BotHouse +e
 &lt;Scorpion> [TCL (37ms)] 
 &lt;Domino> .tcl resetchan #BotHouse I
 &lt;Scorpion>  [!m] MODE #BotHouse +I
 &lt;Scorpion>  [m->] MODE #BotHouse +I
 &lt;Scorpion> [TCL (17ms)] 
 &lt;Domino> .tcl resetchan #BotHouse w
 &lt;Scorpion>  [!m] WHO #BotHouse
 &lt;Scorpion>  [m->] WHO #BotHouse
 &lt;Domino> .tcl resetchan #BotHouse t
 &lt;Scorpion>  [!m] TOPIC #BotHouse
 &lt;Scorpion>  [m->] TOPIC #BotHouse
 &lt;Scorpion> [TCL (8ms)] 
 &lt;Domino> .tcl resetchan #BotHouse m
 &lt;Scorpion>  [!m] MODE #BotHouse
 &lt;Scorpion>  [m->] MODE #BotHouse
 &lt;Scorpion> [TCL (23ms)] 

So, the individual mode issues (as originally reported) are fixed (beIwtm); any new modes (including "a" for "all") do not work.

**Comment by vanosg** [comment]
Sorry, I'm still not seeing the issue - per the documentation included with the snapshot, 'a' is not a valid flag to pass to resetchan. From your paste, the flags that are valid seem to work as expected?

**Comment by ghost** [comment]
Besides the wrong "last updated" date within doc/tcl-commands.doc (in both current versions of Eggdrop distribution: 1.8 CVS / git & 1.6.22 CVS), I'm very sure I found an upgrade to "resetchan" that allowed a new option, "a" (for "update all"), and one other option: an unknown eighth one. However, since the "last updated" date is not accurate (I double it hasn't been updated in 6 years at all), I can't specifically show you where I saw it. :(

My computer crashed with all my archives so I can't find it and can only download the "online verisons" available now. I've read tclirc.c and have not found the changed code I'm speaking of. :(

The issues I originally reported (+beI) has since been fixed; the only remaining issue is the pair of options. Sorry but I just can't find it after my computer crash (I downloaded every version of Eggdrop source code and was comparing various things at the time of the crash).

An "a" option (do all) would be nice, in case a script needs to pass params and, in a given case, it would be easier to pass "resetchan a" instead of: if no flags, resetchan, else: resetchan $flags.

**Comment by ghost** [comment]
I have found where I saw the optional flags, but, it was from _another_ command (strip); I got them confused. I apologize for the error (I know I will be mocked for it).
