### ISSUE TITLE
Eggdrop randomly crashes when opening a connection to an SCHAT/SSL port

### ISSUE THREAD

**Issue by Robby-** [eggheads/eggdrop#200]
Reminder issue so that we won't forget.

**Comment by vanosg** [comment]
Robby, if you can reproduce, let us know and we'll reopen this issue. Thanks!!

**Comment by Robby-** [comment]
I still can, I have a core file of the crash.

**Comment by Robby-** [comment]
Some eggdrop.conf networking settings:

```
#set vhost4 "notset"
#set vhost6 "notset"
#set listen-addr "notset"
set prefer-ipv6 1
listen +22222 bots
listen +33333 users
set nat-ip "myexternalIPv4IP"
#set dns-servers "notset"
```

The machine itself has multiple IPv6 addresses and routes to take depending on the source IPv6 address used, although the bot sends out the machine's default outgoing IPv6 address because there's no specific one configured in eggdrop.conf (which currently works just fine for use with SCHAT in my networking setup).

The steps to reproduce this requires some time.
I can reproduce this with starting the bot, if I then do a `/ctcp bot SCHAT`, this will work without crash (then `.quit` it). However, if you then let it run and sit there for a while (in my experience, about 40 minutes) and then try `/ctcp bot SCHAT` again, it will crash.

**Comment by vanosg** [comment]
Thanks for your perseverance in this, Robby!
