### ISSUE TITLE
Add debug log that shows executed binds and time it took

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#201]
Sometimes bots just ping timeout because a Tcl script is blocking, this feature request would add a details debug log showing all triggered binds (their procs) and how long the execution took.
Found by: saapete

**Comment by michaelortmann** [comment]
pls come up/step forward with a concept answering 3 questions:

1st: where exactly we should log this

2nd: how to enable/disable that logging
debugx() ?
putlog() ?
console flags ?
additional debug log file?
(new) eggdrop.conf setting(s)?

3rd: what to log
only external tcl procs?
also builtin procs?
