### ISSUE TITLE
$::servers , once abandoned with an empty list , is never checked again

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#209]
When a bot cycles endlessly through servers that aren't connectible [ spell check :( ], it will continue cycle endlessly (as expected).

One response (if you're in DCC / telnet) is: {.tcl set ::servers ""} which will stop the bot trying servers, with the message: "No servers in server list"

Then, if you set a server manually {.tcl set servers 192.168.1.1:6667}, the bot _does not_ re-check $::servers again. Once the "No servers in list" error is given, it never checks the variable again. Only a manual {.jump}, {.rehash}, or {.restart} will make the bot attempt a server connect again.

There should be a secondly or minutely timer that checks if $::servers has a non-empty value: if not on a server, resume cycling through the server list as usual.

Tested on Eggdrop 1.6.22 (CVS) & 1.8.0+tcl_config (CVS), on TCL 8.6.5.

**Comment by ghost** [comment]
Addendum: I left the bot for a while to see if it did try again. After 13 minutes, it did suddenly try the manually set server (and successfully connected the first time). Why 13 minutes (23:53 - 00:06)? Fluke? Weird timer value?

**Comment by Cizzle** [comment]
@maimizuno The 23:53 is time of what exactly? Last "No servers in list" message, setting of ::servers, ...?

My tests indicate (on 1.8.0 stable):
- Cycling over servers happens every minute
- Once ::servers is set to "" there is one last check the next minute with the "No servers in list" message.
- Check of ::servers every 5 minutes.
- Once ::servers has an entry again, it takes the remainder of 5mins since the last ::servers check.
- Cycling happens every minute again.

**Comment by ghost** [comment]
Delay in responding: was hospitalized for 3 months.

I didn't see any documentation about the "five minute delay" thus the confusion. Should this even be there? If trying to start a bot that doesn't appear online because of a server error (IRCd IP change for example), and you use ".tcl" to set a manual server (until you can properly repair the server list in the config), you then have to throw a manual ".jump" afterward (and to which server will JUMP choose first??). Why the extra step? If $servers goes from empty to non-empty, shouldn't a jump be immediate and automatic (via a VWAIT-like mechanism)? Even if the 5 minute delay is shortened to 1 minute, it would be an improvement.

**Comment by ghost** [comment]
Oh, and forgot to mention / ask: why did it take 13 minutes in my original discovery instead of 5?

**Comment by Cizzle** [comment]
Hi, welcome back.
I can't explain the 13mins, thus my asking what exactly was started at 23:53.

**Comment by ghost** [comment]
23:53 was the time that I set $::servers to a non - "" value (a specific server) to begin the test. 00:06 was when the bot finally jumped onto the server. I was monitoring in DCC.

**Comment by maimizuno** [comment]
Also, please review bug #245; I added comments to clarify the issue. (I don't have the ability to re-open issues, and, it's not worth opening a new ticket.)

**Comment by vanosg** [comment]
Please do not mix issues between threads, it becomes very hard to track them and when it is appropriate to close them. That said, you may want to reference your *other* issue where you reference this, and see that the versioning system has been redone, and you can access a version string via the global $version variable.

**Comment by thommey** [comment]
I reopened bug #337 so you can check if whatever we changed helps.

**Comment by ghost** [comment]
(asterisk)sigh(asterisk)

Go ahead and close this one, then.
