### ISSUE TITLE
Console mode +t does not show outbound botnet traffic.

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#22]
| Trac | Data |
| --: | :-- |
| Ticket | 22 |
| Reported by | Regan Wallace |
| Status | new |
| Component | Core |
| Priority | minor |
| Milestone | 1.8.0 |
| Keywords | log loglevel |
| Version | 1.8.0 CVS |

If on the console, you set .console +t it will only show inbound botnet
traffic.

.console +t should show outbound botnet traffic as well; either that, or have
another mode that shows outbound botnet traffic.

**Comment by andy5995** [comment]
I'm going to look at this more, but may take me a few days. Adding some notes...

```
<andy_5995> Geo: which file should I look at for 22?
<Geo> probably mod/console/console.c for something
<Geo> net.c will be another part of it
<Geo> the bottom line is, putlog(LOG_<something> is how things are logged
<Geo> LOG_CMD, LOG_BOT, etc
<Geo> those map to those flags
<Geo> if I were you, I'd set up a test net where you can a) verify that this is indeed valid, and b) then test your patch
<andy_5995> ack-grep LOG_BOTNET gave me some info
<Geo> I would suggest you add a second flag to cover outgoing traffic, granularity is usually better
```

**Comment by andy5995** [comment]
What would some good examples of outbound traffic be that I could use for testing?
