### ISSUE TITLE
Update non-needed compat code

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#226]
Lots of code seems unnecessary now, particularly in the compat section. Trim the fat!

**Comment by ghost** [comment]
?

**Comment by thommey** [comment]
This is speaking about the src/compat/ directory that has a lot of compatiblity functions we can remove, because we require POSIX 2001.

**Comment by thommey** [comment]
And check the licenses of the code that remains

**Comment by Cizzle** [comment]
Reopening as not all have been checked yet.

**Comment by Cizzle** [comment]
Reopening as we still have (at least) strftime (#635).
Others that are subject to removal: inet_pton, inet_ntop, strcasecmp, snprintf.
Other inet related functions might too if we change more to use getaddrinfo and getnameinfo.
