### ISSUE TITLE
scripts/botchk not starting eggdrop unless eggdrop.conf is +x

### ISSUE THREAD

**Issue by andy5995** [eggheads/eggdrop#233]
This is the message I logged from cron after I verified botchk wasn't starting a new Eggdrop:

'Couldn't find bot 'anEggdrop' running, reloading...'

After some troubleshooting, I noticed in botchk that it was trying to launch eggdrop by using ./eggdrop.conf

After using 'chmod +x eggdrop.conf', Eggdrop now launches from botchk.

Update: I admit I haven't read ALL of the docs yet, but quite a lot. Are there already instructions somewhere that says to change permissions on eggdrop.conf?

**Comment by vanosg** [comment]
Hi Andy,

Botchk is best configured by running autobotchk in the scripts/ dir. I'd recommend you use that over manually attempting to use botchk. Thanks!

**Comment by andy5995** [comment]
Ah. It would be good if Section 7 of the README were updated then.

**Comment by vanosg** [comment]
How so? It says to use autobotchk

**Comment by andy5995** [comment]
@vanosg I hope my suggested patch (#235) will answer your question.

It doesn't say to use autobotchk, it gives the option in 7a, after the botchk instructions.
