### ISSUE TITLE
Not Real but thanks Vansog

### ISSUE THREAD

**Issue by MWestfall** [eggheads/eggdrop#234]
Hey Vansog, was trying to figure out how to thank you for furthering eggdrop development, are you with eggheads or when will there be a new official release? 

Thanks,
Matt

**Comment by vanosg** [comment]
Hi Matt,

  Yes, we (the eggheads dev team) are VERY close to a release candidate for 1.8. (although, I've been saying that for months now, but I really mean it this time!). Please join us on freenode #eggdrop if you want to chat further. Or, if you want to contribute some bugfixes! :)
