### ISSUE TITLE
autobotchk doesn't truncate default pid file name (botnet-nick) to handle-length

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#239]
The actual botnet-nick variable is truncated to the maximum handle length.
This results in the default PID file name being truncated as well, but autobotchk does not do that.
This shouldn't be much of an issue with 1.8 and default handle length 32, but it should still be fixed somehow. 

Found by: StephenS

**Comment by vanosg** [comment]
Closed by #312
