### ISSUE TITLE
Eggdrop -v response: copyright date?

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#245]
[2016-09-17 18:40:35 -0700] <Scorpion> [SHELL (11ms)] 
Eggdrop v1.8.0+RC1 (C) 1997 Robey Pointer (C) 2010 Eggheads

Um ... 2010? Time to update. :)

**Comment by maimizuno** [comment]
Option request:

./eggdrop -c
[compile flag request]
Responds with grouped text or proper TCL list:
{--with-tcllib=/home/me/lib/tcl8.6.6/lib/libtcl8.6.so --with-tclinc=/home/me/lib/tcl8.6.6/include/tcl.h --enable-strip --enable-ipv6 --disable-tls} {IPV6 handlen=32}

Helps with debugging, and, removed parsing the "eggdrop -v" response manually.

**Comment by vanosg** [comment]
The .status command already lists these args:

```
Online for 13 days, 17:30 (background) - CPU: 12:06 - Cache hit: 22.8%
Configured with:  '--with-tclinc=/usr/include/tcl8.6/tcl.h' '--with-tcllib=/usr/lib/arm-linux-gnueabihf/libtcl8.6.so'
```

Is that sufficient for your use case?

**Comment by vanosg** [comment]
Or perhaps better yet- what _is_ your use case?

**Comment by vanosg** [comment]
Closed via a4ca7a5

**Comment by maimizuno** [comment]
Sorry ~ I was in the hospital for 3 months and didn't see this until now.

The purpose was: to be able to pull data via a script.
".status" only displays to the party line / DCC output, which isn't really scriptable.

Example: If I want to write a bind for bots based on version or compile flags
*1800RC4* say I'm an RC4 bot! Upgrade me!
[bunch of bots reply with the message]

**Comment by thommey** [comment]
closed, we fixed this. see #337 for the version issue mentioned in the last comment

**Comment by maimizuno** [comment]
I don't think my request is being understood properly. Let me start over.

From the shell, "eggdrop -v" provides compile-time options.

'--tcllib=/home/me/lib/tcl8.6.6/lib/libtcl8.6.so' '--with-tclinc=/home/me/lib/tcl8.6.6/include/tcl.h' --enable-strip --enable-ipv6 --disable-tls

Currently, to get this information, you have to do: "exec ./eggdrop -v" and parse the text (via regexp, for example).

I'm asking that that information be made available for scripting purposes via a global variable ($::eggdrop, $::eggdrop(compile)), or, via INFO ([info compile]).

Yes, ".status" reports this information, but, the TCL command only supplies:
cputime 14.650000 expmem 294873 ipv6 enabled tls disabled usercache 75.8

It tells me that ipv6 was compiled on and tls was not compiled, but, (asterisk)it does not(asterisk) tell me the actual compile flags. The information is only available in the ".status" command which outputs to IDX (dcc chat).

I hope that helps clarify what I'm trying to say.
