### ISSUE TITLE
cannot execute binary file: Exec format error when cross-compiling

### ISSUE THREAD

**Issue by eelcohn** [eggheads/eggdrop#248]
Another error when cross-compiling Eggdrop 1.8.0RC1: The Makefile script tries to test-run the bot, but it will throw an error message because the eggdrop executable is compiled for a different architecture. The test-run of eggdrop should be skipped when cross-compiling IMO.

`Test run of ./eggdrop -v:`
`/bin/sh: ./eggdrop: cannot execute binary file: Exec format error`

This one is also an old bug which has also been present in the 1.6.x branch of Eggdrop.

**Comment by vanosg** [comment]
@eelcohuininga , can you grab this and see if it fixes your issue? You can join #eggdrop on Freenode if you want to chat or need some help. Thanks!

**Comment by eelcohn** [comment]
That seems to have done it! This commit fixed three issues:
- The socklen_t issue (#247)
- The eggdrop testrun issue (#248)
- Testrunning IPv6

Nicely done, and thanks for the quick response!

**Comment by vanosg** [comment]
@eelcohuininga , just trying to clean up a little bit on this- could we trouble you to try bug/xCompile branch and see if cross-compiling still works for you as expected? Notably, I'm hoping to see if a) it works for you overall and b) specifically, does it still skip the test run with a message, "This build is a cross-compilation, skipping test run..."  

Thank you!

**Comment by eelcohn** [comment]
Sure, no problem. It might take me a couple of days to get time to test this, so please be patient :)

**Comment by eelcohn** [comment]
Hi,
I've finally found some time to test it, and it works like a charm! I've tested both cross-compiling (on 6 different platforms)...

```
checking for socklen_t... yes
(...)
checking for system IPv6 support... (cached) yes
checking for inet_pton... yes
checking for gethostbyname2... yes
checking for struct in6_addr... yes
checking for the in6addr_any constant... yes
checking for the in6addr_loopback constant... yes
checking for struct sockaddr_in6... yes
(...)
This build is a cross-compilation, skipping test run...
(...)
Installation completed.
```

... and regular compiling (1 platform):

```
Eggdrop successfully compiled:
Modules successfully compiled:
```

Everything seems to be working!

I do however have noticed a warning when linking filesys.mod in cross-compile mode for the qoriq-architecture:

```
make[4]: Entering directory '/home/synology/eggdrop/spksrc/cross/eggdrop_beta/work-qoriq-5.2/eggdrop-1.8.0rc1/src/mod/filesys.mod'
/home/synology/eggdrop/spksrc/toolchains/syno-qoriq-5.2/work/powerpc-none-linux-gnuspe/bin/powerpc-none-linux-gnuspe-gcc -fPIC -I/home/synology/eggdrop/spksrc/toolchains/syno-qoriq-5.2/work/powerpc-none-linux-gnuspe/powerpc-none-linux-gnuspe/include -mcpu=8548 -mhard-float -mfloat-gprs=double -I/home/synology/eggdrop/spksrc/cross/eggdrop_beta/work-qoriq-5.2/install//usr/local/include  -pipe -Wall -I. -I../../.. -I../../.. -I../../../src/mod -I/home/synology/eggdrop/spksrc/cross/eggdrop_beta/work-qoriq-5.2/openssl-1.0.2i/include/openssl/ -DHAVE_CONFIG_H -I/home/synology/eggdrop/spksrc/cross/eggdrop_beta/work-qoriq-5.2/install/usr/local/include -I/home/synology/eggdrop/spksrc/toolchains/syno-qoriq-5.2/work/powerpc-none-linux-gnuspe/powerpc-none-linux-gnuspe/include -mcpu=8548 -mhard-float -mfloat-gprs=double -I/home/synology/eggdrop/spksrc/cross/eggdrop_beta/work-qoriq-5.2/install//usr/local/include  -DMAKING_MODS -c .././filesys.mod/filesys.c
In file included from .././filesys.mod/filesys.c:139:
.././filesys.mod/filelist.h:45: warning: 'filelist_idxshow' declared inline after being called
.././filesys.mod/filelist.h:45: warning: previous declaration of 'filelist_idxshow' was here
mv filesys.o ../
/home/synology/eggdrop/spksrc/toolchains/syno-qoriq-5.2/work/powerpc-none-linux-gnuspe/bin/powerpc-none-linux-gnuspe-gcc -shared -nostartfiles -o ../../../filesys.so ../filesys.o -L/home/synology/eggdrop/spksrc/cross/eggdrop_beta/work-qoriq-5.2/openssl-1.0.2i/ -L/home/synology/eggdrop/spksrc/cross/eggdrop_beta/work-qoriq-5.2/tcl8.6.6/unix -ltcl8.6 -lieee -lm -lcrypto -lssl -ldl -lnsl -lz 
```

Since it only happens on the qoriq-architecture, and not on any of the others I've done, or on a regular compile job, I think it's gotta be something in the qoriq-toolchain stuff, and not with the eggdrop stuff. Have you guys ever seen this type of warning before?
