### ISSUE TITLE
Eggdrop1.8 TLS Botnet link failure: SSL3_GET_CLIENT_CERTIFICATE:no certificate returned

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#252]
Example ./eggdrop -n run from leaf:
  https://gist.github.com/anonymous/fcc2a8c3e7e06f1ccba3ad335fccd45c
Another pastebin:
  https://paste.linux.community/view/ab197e23

happened during upgrading from "months old" 1.8-git to 1.8.0rc1. ssl-verify-bots is 0 on all bots.

Found by: Kiril, fred

**Comment by thommey** [comment]
Update: turns out, ssl-verify-bots was 1 and not 0, that was causing the validation error, for fred anyway.

**Comment by thommey** [comment]
Update: for Kiril, ssl-verify-\* was 0 except for ssl-verify-dcc. Setting that to 0 makes the bots link but subsequently fails on a userfile transfer: https://paste.linux.community/view/cb134756
successful transfer example: https://paste.linux.community/view/1103c6c6

Maybe we need to check that the verify settings make sense?

**Comment by vanosg** [comment]
Any theories on why that causes it to fail?

**Comment by vanosg** [comment]
set verify-dcc was 1 , but the crt Kiril was using on the hub bot was not added to his trusted ca chain. Thus, appropriately, that DCC connection was being rejected as it didn't trust the cert being provided. Changing to 0 fixed. This feature works as expected. Recommend closing.
