### ISSUE TITLE
.whois does not show bot SSL port status

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#260]
```
#vanosg# chaddr testbot 192.168.180.160 +3183/+3189
Changed bot's address.

.whois testbot
#vanosg# whois testbot
HANDLE                           PASS NOTES FLAGS           LAST
testbot                          no       0 b               00:12 (unlinked)
  ADDRESS: 192.168.180.160
     users: 3189, bots: 3183
  BOT FLAGS: ghp
```

We should probably prefix the bot and user port with a '+' if they were added that way, to denote SSL-only connections

**Comment by Robby-** [comment]
This works for me.
I tried `.+bot test 1.1.1.1 +2222/+3333` and it shows the ports prefixed with `+` in `.whois test`.
Then I tried `.+bot test 1.1.1.1 4444/5555` followed by `.chaddr test 1.1.1.1 +2222/+3333`, this again shows the ports prefixed with a `+` just fine.

```
.whois test
#Robby# whois test
HANDLE    PASS NOTES FLAGS           LAST
test      no       0 b               never (nowhere)
  ADDRESS: 1.1.1.1
     users: +3333, bots: +2222
```

**Comment by vanosg** [comment]
Hrm. Me too now, with chaddr as well. Damn gremlins.
