### ISSUE TITLE
Eggdrop with Cygwin: compilation errors

### ISSUE THREAD

**Issue by creatio-ua** [eggheads/eggdrop#262]
Hi,

I'm using recently installed cygwin on Windows 7 x64 Ultimate to build an Eggdrop 1.6.21.
Trying to follow the Eggdrop build instructions:
[http://www.eggheads.org/support/egghtml/1.6.21/compiling.html](url)
and everything went just fine, until the:

> make eggdrop

It fails with lots of errors that arguing on unknown win32 API types:

> gcc -g -O2 -pipe -Wall -I.. -I.. -DHAVE_CONFIG_H   \
> '-DCCFLAGS="gcc -g -O2 -pipe -Wall -I.. -I.. -DHAVE_CONFIG_H  "' \
> '-DLDFLAGS="gcc"' \
> '-DSTRIPFLAGS="strip"' -c ./main.c
> In file included from /usr/include/w32api/minwindef.h:163:0,
>                  from /usr/include/w32api/windef.h:8,
>                  from /usr/include/w32api/windows.h:69,
>                  from ./main.c:68:
> /usr/include/w32api/winnt.h:327:11: ошибка: unknown type name «CHAR»
>    typedef CHAR _PCHAR,_LPCH,_PCH;
>            ^
> /usr/include/w32api/winnt.h:328:17: ошибка: unknown type name «CHAR»
>    typedef CONST CHAR *LPCCH,_PCCH;
>                  ^
> /usr/include/w32api/winnt.h:329:11: ошибка: unknown type name «CHAR»
>    typedef CHAR _NPSTR,_LPSTR,_PSTR;
>            ^
> /usr/include/w32api/winnt.h:332:17: ошибка: unknown type name «CHAR»
>    typedef CONST CHAR *LPCSTR,_PCSTR;
>                  ^
> /usr/include/w32api/winnt.h:334:11: ошибка: unknown type name «CHAR»
>    typedef CHAR *PZZSTR;
>            ^
> /usr/include/w32api/winnt.h:335:17: ошибка: unknown type name «CHAR»
>    typedef CONST CHAR *PCZZSTR;
>                  ^
> /usr/include/w32api/winnt.h:336:11: ошибка: unknown type name «CHAR»
>    typedef CHAR *PNZCH;
>            ^
> /usr/include/w32api/winnt.h:337:17: ошибка: unknown type name «CHAR»
>    typedef CONST CHAR *PCNZCH;
>                  ^
> /usr/include/w32api/winnt.h:385:11: ошибка: unknown type name «SHORT»
>    typedef SHORT *PSHORT;
>            ^
> /usr/include/w32api/winnt.h:386:11: ошибка: unknown type name «LONG»
>    typedef LONG *PLONG;
>            ^
> /usr/include/w32api/winnt.h:412:11: ошибка: unknown type name «LONG»
>    typedef LONG HRESULT;
>            ^
> /usr/include/w32api/winnt.h:501:7: ошибка: unknown type name «LONG»
>        LONG HighPart;
>        ^
> /usr/include/w32api/winnt.h:505:7: ошибка: unknown type name «LONG»
>        LONG HighPart;
>        ^
> /usr/include/w32api/winnt.h:533:5: ошибка: unknown type name «LONG»
>      LONG HighPart;
>      ^

I was unable to find anything on that issue in the internet, so it might be something obvious for the guys that work with cygwin or unix frequently. Unfortunately I'm not one of them. :(

**Comment by thommey** [comment]
Hey there,

a user on our Freenode #eggdrop channel mentioned he might have a solution for you.
It might work out if you stop by and poke him. I would also appreciate to know what's going on there :)
The webchat is available at http://webchat.freenode.net/?channels=eggdrop (although you might need to hang around a bit after poking him, his nick is jackal^). Thanks!

**Comment by thommey** [comment]
As per http://windrop.sourceforge.net/compile18cvs.html the following patch removes our CYGWIN_HACKS http://windrop.sourceforge.net/patches/eggdrop1.8.0.patch which fixed this issue for creatio.

We might want to apply it to rc2 and see what happens?

**Comment by vanosg** [comment]
I'm definitely not the right guy to speak authoritatively, but it looks pretty harmless to do- in a more refined release process I'd recommend making this the first commit for 1.8.1, as we don't want to accidentally regress any other capability, especially without a robust test process in place... but those two changes are fairly trivial, so maybe it could be an option for RC2. I think my vote lands on incorporating in .1 "to be safe"

**Comment by thommey** [comment]
Hey, I think I have come up with a better fix for this (removing the windows.h inclusion breaks launching into background): https://github.com/eggheads/eggdrop/tree/bug/cygwinwinapi You can test it if you want and report back, otherwise I'll merge it into our mainline soon. Thanks for reporting this!

**Comment by creatio-ua** [comment]
Hey,

Thanks a lot for the info! I've got into trouble making the eggdrop to link with tcl, but I was a bit unsure if the problem is not on my side (seems like I did everything right, but seems like the problem is in missing x64 tcl version). But I'll be glad to check your alternative fix in a day or two.

> Воскресенье,  2 октября 2016, 16:51 +03:00 от Thomas Sader notifications@github.com:
> 
> Hey, I think I have come up with a better fix for this (removing the windows.h inclusion breaks launching into background):  https://github.com/eggheads/eggdrop/tree/bug/cygwinwinapi You can test it if you want and report back, otherwise I'll merge it into our mainline soon. Thanks for reporting this!
> —
> You are receiving this because you authored the thread.
> Reply to this email directly,  view it on GitHub , or  mute the thread .

Respectfully
Alex Dovgodko

**Comment by creatio-ua** [comment]
Hi!

Sorry for the late reply!
Looks like I've got stuck on linking and can't move any further:
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /usr/local/lib/libtcl8.5.dll when searching for -ltcl8.5
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /usr/local/lib/libtcl8.5.dll when searching for -ltcl8.5
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -ltcl8.5

This problem prevents me from being able to test the fix so far. :(

> Hey, I think I have come up with a better fix for this (removing the windows.h inclusion breaks launching into background):  https://github.com/eggheads/eggdrop/tree/bug/cygwinwinapi You can test it if you want and report back, otherwise I'll merge it into our mainline soon. Thanks for reporting this!
> —
> You are receiving this because you authored the thread.
> Reply to this email directly,  view it on GitHub , or  mute the thread .

Respectfully,
Alex Dovgodko
