### ISSUE TITLE
Display a summary of things after ./configure

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#264]
I'd like ./configure to display a summary of things at the end. Currently it only displays operating system. Other software has moved on to display a summary displaying whether TLS or IPV6 is supported, Tcl verison used, etc. I'd like that for eggdrop as well.

**Comment by ghost** [comment]
Also, a core command to report the same things that "eggdrop -v" reports but to TCL instead.

set eggcore [info eggdrop]

... or the like.
