### ISSUE TITLE
REQUEST: please add function - include external files like banlist, users list etc.

### ISSUE THREAD

**Issue by nmr50** [eggheads/eggdrop#277]
Hello authors !
Please make this feature thus users can include various bans/user records/etc from external files instead of storing them (large ones!) into one large .user file. Very useful to make country based ban lists stored in several country named files - the same way we have "source script.tcl", but for users/bans etc.
How I see this in EGGDROP.CONF:
##### INCLUDE EXTERNAL FILES

include users/botname.users
include bans/mars_dudes_ip.list
include except/jupiter_dudes_ips
###### 

Can do, please ?:)
-t

**Comment by thommey** [comment]
Hey,

the userfile is not meant to be edited or created by users, it's simply a storage system for Eggdrop's internal data. Why is it a problem if it gets large? You aren't supposed to look at it with an editor :)

But what you need can be 100% achieved by sourcing scripts that set bans, for example, you can put this into a script called germany.tcl:

``` tcl
set banlist {
  *!*@*.de
  *!*@*.dip.t-dialin.net
  *!*@*.tip.t-ipc0nnect.de
}
foreach ban $banlist {
  newban $ban script "German users are not allowed in here."
}
```

Is there any reason you don't want your userfile to get large other than you currently edit it manually? Would the Tcl script solution suffice? Let me know if you have any further questions, too :)

**Comment by nmr50** [comment]
I meant external ban lists for the one of reasons - I can automatically update those lists, and make bot reload its config in given time - right after reloading. Btw, will be nice feature to add - reload config+includes in time specified in config file.

What you will tell ?:)

**Comment by vanosg** [comment]
Hi nmr50,

  This certainly is a useful feature. I think if you read what thommey said again, you'll see this functionality already exists if you place your banlist into the format that he suggested. Just set all the bans you want to use inside the 'banlist' array he demonstrated, and run the code directly below it. You can do the same thing for excepts and users by creating their own lists, and running the same command after, replacing 'newban' with 'newexempt' or 'adduser' (and the appropriate syntax). You can view more on the details of those commands in doc/tcl-commands.doc that comes with eggdrop. Try it out and let us know if that works well for you or not! Thanks

**Comment by nmr50** [comment]
Hiya vanosg! Thanks for commenting, but what I am trying to achieve is ability to load IP addresses from external files, while those files will be updated once a day.
I am not a hardcore coder, so it will be somewhat hazy to me how to put updated lists into .tcl code...

The years ago when I were running IRC server, pal of mine (a coder) made changes to server, so it was able to load K:lines from external files, and those files were updated from GeoIP site, then-by server was reloaded via kill -HUP. Do you want me to paste those sources so you can import that code to eggdrop src ?

It's all the same - include strings are in .conf file, includes are operated by C function in server sources.

**Comment by Pixelz** [comment]
This is certainly something that is possible to achieve with Tcl scripting. It is precisely for specialized features like the one you request that Eggdrop supports scripting. It does not belong in Eggdrop itself.
