### ISSUE TITLE
OpenBSD 6.0 building

### ISSUE THREAD

**Issue by LinaSovereign** [eggheads/eggdrop#290]
Since the release 6.0 of OpenBSD i'm unable to build an eggdrop (tested with 1.6 and 1.8 same problem), Here is the following output : 

> ld -Bshareable -x -o ../../../assoc.so ../assoc.o -L/usr/local/lib -ltcl85 -lm -lpthread -lcrypto -lssl
> ld: ../assoc.o: relocation R_X86_64_PC32 against `__guard_local' can not be used when making a shared object; recompile with -fPIC
> ld: final link failed: Bad value

You can find the full build log here : https://gist.github.com/LinaSovereign/ca5b8ab08e54c88e8b1e7f0e4fd0f8b4

**Comment by thommey** [comment]
Hey,
I was able to reproduce this with OpenBSD 6.0 and believe 2f98259 fixes the problem. Could you pull again and see if it works now? Thanks!

**Comment by LinaSovereign** [comment]
Building is ok now. Thank you !

> [23:11:01] #Lina# status
> I am CagedMonster, running eggdrop v1.8.0+itcompiles: 1 user (mem: 96k).
> Online for 00:00 (background) - CPU: 00:00.02 - Cache hit: 42.9%
> Configured with:  '--with-tcllib=/usr/local/lib/libtcl85.so' '--with-tclinc=/usr/local/include/tcl8.5/tcl.h'
> Admin: Lina Sovereign
> Config file: eggdrop.conf
> OS: OpenBSD 6.0
> Process ID: 56507 (parent 1)
> Tcl library: /usr/local/lib/tcl/tcl8.5
> Tcl version: 8.5.18 (header version 8.5.18)
> TLS support is enabled.
> TLS library: LibreSSL 2.4.2
> IPv6 support is enabled.

**Comment by thommey** [comment]
Thank you very much for reporting and testing it :)
