### ISSUE TITLE
Error Loading Gseen Modules.

### ISSUE THREAD

**Issue by fahadmehar** [eggheads/eggdrop#293]
I having problem installing gseen modules. can you please tell me what this error meaning???

**gseen: Error loading module: /home/Statistics/eggdrop/modules/gseen.so: wrong ELF class: ELFCLASS32**

**Comment by vanosg** [comment]
Hello fahadmehar, 

  As we said in your previous issue, GitHub is used for code issues and bug tracking only, not general support- please join #eggdrop on freenode for support and questions. Thank you!
