### ISSUE TITLE
chattr +n/+m gives way too many flags

### ISSUE THREAD

**Issue by speechles** [eggheads/eggdrop#296]
Issue: .chattr someone +n

Expected result: Global flags for someone are now +n

Actual result: Global flags for someone are now +jlmnoptx.

Is there any reasoning behind why when asked to just add the flag +n it is adding all these other flags too? Is there any rationale?

https://github.com/eggheads/eggdrop/blob/be8bd0918f5b6e1d852b82e2d38154cb99057163/src/flags.c#L264-L272

Removing this solves the issue with respect to flags owners/masters get.

**Comment by Pixelz** [comment]
This is how Eggdrop has handled flags for the past 20-some years. I am hesitant to change it without a really good explanation as to why it's suddenly an issue.

Edit: after some digging around I've found that this concept was introduced somewhere in Eggdrop 0.9 and reached roughly its current state by 1.2.0

**Comment by thommey** [comment]
It is a cheap hack to skip checking for +o or +m or +n on every check where +o is required, it would probably quite a lot of effort to change those checks from HAS_O to HAS_AT_LEAST_O
