### ISSUE TITLE
Mixed botnet 1.6.21 and 1.8.0 RC-2 and snapshot Linked bots show no stored password

### ISSUE THREAD

**Issue by erickjvelez** [eggheads/eggdrop#299]
on Hub bot (1.6.21):
[10:32:16] #+n# whois Leafbot
HANDLE    PASS NOTES FLAGS           LAST
Leafbot      no       0 bflo            10:15 (linked)
  BOT FLAGS: gs

on Leafbot (1.8.0)
HANDLE    PASS NOTES FLAGS           LAST
Hub     no       0 b               10:15 (linked)
  BOT FLAGS: ghp

They are linked, sharing userfiles and coexist happily. 1.8.0 was compiled without TLS.

**Comment by vanosg** [comment]
Can you provide some more context as to what you've done to get them to this state? Can you start from scratch and replicate? Are you running any weird scripts? I just linked two and the PASS field shows as 'yes', as it should. We appreciate any extra detail you can offer, thanks!

**Comment by erickjvelez** [comment]
Hub Bot is 1.8.0-RC2 today. 
The leaf bots are mixed 1.8.0 and 1.6.21

.vbottree
Hub (1.8.0.3)
  |-+XXX (1.6.21.3)
  |-+XXXy (1.6.21.3)
  |-+XXX (1.6.21.3)
  |-+XXX (1.6.21.3)
  |-+XXX(1.8.0.3)
  |-+XXX (1.6.21.3)
  |-+XXX (1.6.21.3)
  |-+XXX (1.6.21.3)
  |-+XXX (1.8.0.3)
  |-+XXX (1.8.0.3)
  `-+XXX (1.8.0.3)
Average hops: 1.0, total bots: 12

Hub bot was:
Configured with:  '--with-tcllib=/usr/local/lib/libtcl86.so' '--with-tcl=/usr/local/lib/tcl8.6' '--with-tclinc=/usr/local/include/tcl8.6/tcl.h' '--disable-tls'
OS: FreeBSD 10.3-RELEASE-p11
Tcl library: /usr/local/lib/tcl8.6
Tcl version: 8.6.6 (header version 8.6.6)
Tcl is threaded.
TLS support is not available.
IPv6 support is enabled.

.match +b shows all the bots as linked. Some of the 1.6.21 and some of the 1.8.0 show up as having a password. The rest do not.

Bot1       yes      0 bflo            08:19 (linked)- 1.8.0
Bot2   yes      0 bflo            08:19 (linked)- 1.8.0
Bot3       yes      0 bflo            08:19 (linked)- 1.6.21
Bot4   no       0 bflo            08:19 (linked)- 1.8.0
Bot5      no       0 bflo            08:19 (linked)- 1.6.21
Bot6    no       0 bflo            08:19 (linked)- 1.8.0
Bot7      no       0 bflo            08:19 (linked)-1.6.21
Bot8    no       0 bflo            08:19 (linked)-1.6.21

The bots without a password on .match +b, have no PASS line in the user file.

Leaf Bot X is 1.6.21:

I am Orca, running eggdrop v1.6.21+nicklentrace:
.whois HubBot
HANDLE    PASS NOTES FLAGS           LAST
Hub     no       0 b               08:19 (linked)

Same behavior in the user file.

This only happened after switching the hub bot to 1.8.0. Happened with RC2 and the daily snapshot. Can't recall if it happened with RC1.

**Comment by vanosg** [comment]
Maybe unrelated, maybe not- is there a reason you disabled TLS yourself? You can still link 1.6 bots to 1.8 with TLS enabled.

**Comment by erickjvelez** [comment]
I could not get them to share userfiles with TLS enabled.

**Comment by vanosg** [comment]
OK, I was able to replicate the problem. Thanks!

**Comment by vanosg** [comment]
This only occurs with the --disable-TLS . It also appears that unlinking and relinking them will fix the display- can you confirm on your side as well?

For fun, you may want to stop in #eggdrop on Freenode and see if you can get some help getting your bots to link without using --disable-TLS ... 1.8 was built to be able to still link with 1.6 bots without needing to disable TLS. 

Thanks again for reporting this!

**Comment by erickjvelez** [comment]
I relinked the hub bot multiple times and it really does not correct.
I tried getting help in Freenode's #eggdrop, no one could figure out what the problem was to link using TLS/SSL. The suggestion to --disable-TLS came from them.

**Comment by vanosg** [comment]
This should do it- I'll let some people smarter than me review before we merge 'just in case', but if you want to merge that PR into your own code base while you wait (just 2 line edits, really), I think it should do the trick.

...and we should really get your TLS working so you don't have to use this in the first place :) Thanks a ton for reporting this, it was definitely an important bug to catch.

**Comment by erickjvelez** [comment]
Thank you so much for looking into it.
