### ISSUE TITLE
"Invalid Argument" error

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#301]
If  my-ip, my-hostname, vhost4, or vhost6 are improperly set, the incredibly helpful "Invalid Argument" error is returned. Recommend catching the error and replacing with something slightly more useful.

**Comment by Cizzle** [comment]
Could you tell when you see those errors? I've set vhost4 to "999.99.99.0" which is in my eyes "improperly set", but I see no error when starting the bot or on partyline. Aren't my-ip and my-hostname deprecated?

**Comment by vanosg** [comment]
From thommey-

Failed connect to chat.freenode.net (Cannot assign requested address) 
  * valid IP that is not bound to an interface (random IP)

Failed connect to chat.freenode.net (Invalid argument) 
  * assigning 127.0.0.1 as vhost but trying to connect to an IP outside of that netmask (not 127/8, e.g. chat.freenode.net)
