### ISSUE TITLE
Add ability to reset console to defaults

### ISSUE THREAD

**Issue by Pixelz** [eggheads/eggdrop#311]
If you turn on a lot of console modes via the .console dcc command, for instance all of them via .console +*, it is later annoying having to reset the console to the default state by individually turning off each console flag.

I propose a new subcommand be added, for instance ".console reset" which will reset the console to the defaults set in eggdrop.conf

**Comment by thommey** [comment]
.resetconsole
the console command itself is too overloaded with ambiguity
