### ISSUE TITLE
Non-matching handle lengths

### ISSUE THREAD

**Issue by solbu** [eggheads/eggdrop#320]
Hi.
I run two botnets, and is trying out the new eggdrop v1.8.0, which compiles and runs jut finr. But it is apparently not able to link with v1.6.21.

Bot X runs v1.8.0 and Bot Y runs v1.6.21, and the upgraded bot attempt to linkup with the botnet.

eggdrop 1.8.0 complains on «Non-matching handle lengths with X, they use 9 characters»
eggdrop 1.6.21 complains on «Non-matching handle lengths with Y, they use 32 characters.»

All bots have configured nick-len to 9.
I can't upgrade untill this is resolved.

**Comment by vanosg** [comment]
Hello solbu,

  As that message implies, handle lengths need to match. You'll need to recompile your 1.6 bot with a matching handlen length if you want them to link. As this is not a bug, please join #eggdrop on Freenode for further assistance for further troubleshooting with your problem. Good luck!
