### ISSUE TITLE
Telnet: cursor keys

### ISSUE THREAD

**Issue by TimerWolf** [eggheads/eggdrop#335]
```
Really important

1: Left to move left if you typed wrong
2: Right to move back
```

```
Additional nice features linux like style

1: Up / Down to see recently used commands

Note: Only store this one in memory no need to remember that if client/session is restarted
```

**Comment by Cizzle** [comment]
This depends on the client used and is not under control of the eggdrop. [Rlwrap](https://github.com/hanslub42/rlwrap) will help you.

**Comment by antonstarlid** [comment]
I found [this](http://forum.egghelp.org/viewtopic.php?t=7514)

I have try some diffrent softwares and none of them response at all

**Comment by TimerWolf** [comment]
I found [this](http://forum.egghelp.org/viewtopic.php?t=7514)

I have try some diffrent softwares and none of them response at all

You just get this "Left: ^[OD" and "Right: ^[OC"
