### ISSUE TITLE
Compile warning

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#336]
eggdrop 1.8.0 final release [2016-12-04] against TCL 8.6.6

gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H   \
'-DCCFLAGS="gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H  "' \
'-DLDFLAGS="gcc"' \
'-DSTRIPFLAGS="strip"' -c ./main.c
./main.c:730:13: warning: ‘patch’ defined but not used [-Wunused-function]
 static void patch(const char *str)
             ^

Obviously, it's only a warning and the compile succeeds. Just letting you know.

**Comment by vanosg** [comment]
Already fixed by #319
