### ISSUE TITLE
Re-visit version announcement documentation

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#340]
How do we want to handle upgrade notices that come with the bot? Do we want NEWS-1.8, NEWS-1.8.1, UPGRADE-1.8, etc etc?

**Comment by vanosg** [comment]
We went with UPGRADE-1.8 and NEWS-1.8.1 for 1.8.1 ... is this closed?

**Comment by Cizzle** [comment]
I'd say so it's closed...
