### ISSUE TITLE
Feature: compile information available via TCL code

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#342]
From the shell, "eggdrop -v" provides compile-time options. Would be helpful to get that via script (without relying on "exec eggdrop -v").

**Comment by thommey** [comment]
What's the use-case for exact compile flags? Are you compiling an Eggdrop from Eggdrop via a script? ipv6/tls can be reconstructed from "ipv6 enabled tls disabled"

**Comment by ghost** [comment]
To access compile flags via script.

**Comment by thommey** [comment]
After discussion on IRC it is clear that the use-case is close enough to running ./configure from Tcl to justify simply providing the flags as a Tcl list in a global variable (or similar).

**Comment by maimizuno** [comment]
In the spirit of "info patchlevel" and "info library," maybe "info compile" ?

**Comment by maimizuno** [comment]
Maybe, in the spirit of the the read-only global variables Eggdrop provides, maybe this info can be referenced by the read-only variable $::eggdrop-compile (as a simple TCL list).

Delete my earlier idea about INFO COMPILE, as that's more TCL-specific information, not so much Eggdrop-specific.
