### ISSUE TITLE
Feature request: EVNT bind: prejoin

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#364]
There may be cases where the bot may need to initial values from the server (such as the endearing 005, or nick-auth or set a VHOST) before joining channels. In the case of UnRealIRCd, a setting forces a client to visually part / rejoin (cycle) all channels to show the host change [this cycle is invisible to the client itself].

Even using the event bind "init-server," the code doesn't execute until the bot has already started joining channels, which may be too late.

Request: new event bind: "prejoin" -- code to execute before the bot joins channels. This way, server-level stuff can be done before the bot joins channels, thus eliminating some channel noise (such as: bot cycles due to vhost changes).

**Comment by thommey** [comment]
I agree with that joins should not be sent before triggering init-server, to give you a chance to prevent them. The usual approach (when that is the case) would be:
```tcl
bind evnt - init-server doauth
proc doauth {args} {
  global wasinactive
  set wasinactive ""
  foreach c [channels] {
    if {[channel get $c inactive]} {
      lappend wasinactive $c
    } else {
      channel set $c +inactive
    }
  }
}
bind notc - "You are now identified for *" didauth
proc didauth {nick args} {
  global wasinactive
  if {$nick eq "NickServ"} {
    foreach c [channels] {
      if {$c ni $wasinactive} {
        channel set $c -inactive
      }
    }
  }
}
```

If that code doesn't currently work because init-server triggers after the joins are queued, that should be changed to be that way. (An inconvenient workaround for current versions would be to clearqueue in init-server, but that is of course not always acceptable - or bind out to prevent the joins being sent, but that is beyond the scope of what script authors are expected to do)

**Comment by Pixelz** [comment]
This is already possible using a combination of "bind out" and "bind evnt". You can see my [qchallengeauth.tcl script](https://github.com/Pixelz/pixelz-tcl/blob/master/eggdrop/qchallengeauth.tcl) for a fully working design for authenticating to Q (network service) on QuakeNet and hiding the bot until it's cloaked.

This is achieved by sending a random nick to the server upon connect, intercepting JOIN and NICK commands that Eggdrop attempts to add to the queue and preventing them from being queued until the bot is authed and cloaked.

**Comment by ghost** [comment]
I realize that these are workarounds, both, but they beg the question: do I need to have my bot come up with different / random nicks, or, suspend channels temporarily just to puts text out in the proper order (network issues then channel issues)? The Q challenge script was filed on 2012-07-01, which means: this has been a known issue for nearly 7 years (if not more). I'd rather hope a "prejoin" event bind can be included into Eggdrop and I can just suffer it out until then, instead of going "way out of my way" to solve what should be an otherwise "trivial" issue with all these gyrations. I guess the  channel suspend method is best for non-Q networks.

**Comment by thommey** [comment]
I believe bind evnt init-server combined with bind notc is not a "workaround" but the correct solution. If there is still an issue with eggdrop queueing joins despite correct +inactive setting in init-server, please file a new bugreport about that behavior. init-server is the actual prejoin event.
