### ISSUE TITLE
bind mode: non-standard modes

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#365]
The MODE bind only returns the target arg for chanmodes ohvlLk (and, maybe a few others like "fj"). One way to help programmers compensate for this situation is: force the MODE BIND to return the arg regardless of what mode it is (don't "process which gets args and which don't"). To help this along, a config variable would be needed:

set channel-opmodes "qaohv"

This would be IRCd independant, and, would allow the proper MODE BIND replies (+q target, +l target, -L (no arg), -o target, ... ).

This way, the following mode blast would be parsed as:
mode #channel +qomtnl Domino Domino #Overflow 50
[bind reply] mode #channel +q Domino
[bind reply] mode #channel +o Domino
[bind reply] mode #channel +m {}
[bind reply] mode #channel +n {}
[bind reply] mode #channel +t {}
[bind reply] mode #channel +l 50

Mind you, parsing RAW 005 would give you this information as well, but seeing how long THAT request has been pending, maybe this would be a faster / simpler way of handling? Otherwise, a problem still exists: modes like +L (capital L) which take a param to set but none to remove.

This is related to #3 and gives an alternate way of solving the issue (albeit temporarily).

**Comment by ghost** [comment]
An additional issue was just found:

[005::MODE:RAW] hex(234368616e **20** 2b7120446f6d696e6f):arg(#Chan +q Domino)
vs
[005::MODE:RAW] hex(234368616e **00** 2d7120446f6d696e6f):arg(#Chan

On a + mode change, the data returned by the RAW MODE bind (bind raw - mode proc) shows a space after the channel name [which you would expect]. However, on the - mode change, instead of a space, there is a NULL CHARACTER (\x00) which cuts off output past that point.

Why is there a null character there?!

See additional comment below: this is only 1 of 2 0x00 characters in the stream; this one only shows one because of parsing before the debug output.

**Comment by ghost** [comment]
@vanosg New issue created.

**Comment by vanosg** [comment]
Thank you - as a request for the future, could you not delete your comments in other threads? Leaving them there is totally fine. It's a little better for continuity and understanding in future reviews- otherwise we see disjointed threads that don't make much sense! Thank you

**Comment by ghost** [comment]
Further testing reveals two things:

(1) mode bind for - modes triggers BEFORE raw mode binds (whereas + binds trigger AFTER the raw mode bind)

(2) there's a SECOND 0x00 in the - mode raw: "nick(0x00)ident@host(0x00)#channel (+/-)mode target"

**Comment by ghost** [comment]
Demonstrated elsewhere; this is a duplicate issue.

**Comment by ghost** [comment]
Is related to:
#354
#387

**Comment by maimizuno** [comment]
```
Discussion in channel between me, @vanosg and @michaelortmann revealed these issues with this and related PRs: (#354, # 365, & #387). To combine them into one place, we've concluded this so far:

(I) any mode changes to a channel, regardless of number of targets:
    (A) any mode change will work properly: the RAW bind will trigger
        Ami-Laptop!Mercury@ShabonSpray.ShineAquaIllusion.Org MODE {#Testing +i }
    (B) then the internal MODE bind will trigger
        Ami-Laptop Mercury@ShabonSpray.ShineAquaIllusion.Org Domino #Testing +i {}

(II) the next mode change will be processed differently:
    (A) the INTERNAL bind will trigger first
        Ami-Laptop Mercury@ShabonSpray.ShineAquaIllusion.Org Domino #Testing -i {}
    (B) then the RAW bind will trigger, but two different things happen:
        (1) Ami-Laptop*[0x00]*Mercury@ShabonSpray.ShineAquaIllusion.Org Domino #Testing -i {}
            the space between the nick and host is replaced by a null char (0x00)
        (2) the order has changed from raw / internal, to internal/raw
        (3) the raw bind (II/B) comed out delayed by nearly 2/3 of a second

(III) there's an ambiguity, therefore, as to what order the binds SHOULD trigger:
    (A) raw, then internal
    (B) internal then bind

(IV) RAW bind: return value (return 1) indicates a short-circuit of bind processing 
     (per the docs). As such, it is believed (for now), that the RAW bind should come first;
     logically, having a MODE bind trigger, then the RAW bind (which can kill any further bind
     triggers) seems backward.


(v) issues to solve (as of now):
    (A) determine the order; need to confer with the OG coders (Geo, thommey, et cetera)
    (B) determine why this "toggle" exists
    (C) determine if the 0x00 substitution it related to the above, or, another issue altogether
```
