### ISSUE TITLE
Rehashing with ? in alt-nick changes nick

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#366]
Rehashing seems to generate a new preferred nickname instead of checking if the current nickname matches the existing alt-nick pattern (with ? being a digit). This leads to unnecessary nick changes.

**Comment by vanosg** [comment]
thommey, can you show a use case of this happening, so I can make sure I'm following your train of thought correctly?

**Comment by thommey** [comment]
```tcl
set nick NickServ; # something in use
set altnick Eggdrop?????
set keep-nick 1
```
let the bot connect and grab its altnick (Eggdrop19538), then .rehash the bot. It re-generates the alt-nick and sets it to Eggdrop38464 and immediately changes to it, instead of recognizing that its current nick matches the altnick pattern (? being 0-9). This should check if the current nick matches the pattern instead of blindly setting altnick to a constant new random nick.
