### ISSUE TITLE
.help chaninfo

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#381]
.help chaninfo doesn't reflect that you can set flood-* to "0" to deactivate.

**Comment by vanosg** [comment]
I'm on the fence if this is a 'shortcut' or a 'bug' ... it could be fixed one way or the other, but are there second order effects from using '0' as the value?

**Comment by Cizzle** [comment]
As it's listed as a valid option in eggdrop.conf and even in the chaninfo help itself a few lines below, I'd mark this as shortcut. Looking at the code, a "0" for either "count" or "time" disables it. Side effect of using just "0" is that the "time" is set to "1", which should actually be "0"?
