### ISSUE TITLE
Critical issue with 1.8.1+sslserverlist: GETUSER XTRA is broken

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#382]
I just upgraded to the currently available download (git).

\<Scorpion> [2017-04-25 20:25:46 -0700] Tcl error [dispatch_dcc]: expected boolean value but got "CONSOLE {#channel mpjkcobxswv12345678 - 1 0 -1} H"

This only applies to:

Eggdrop: 1.8.1+sslserverlist -- TCL: 8.6.6 -- Library: /usr/local/lib/tcl8.6

This problem did not exist before this upgrade. When I reverted down to the previous release [EGGDROP v1.8.1 - full release], the problem disappears.

I'll update this as I track this down (if I am able to).

**Comment by vanosg** [comment]
Can you paste the code for what dispatch_dcc in your Tcl script is trying to do?

**Comment by ghost** [comment]
I have found the issue to be:

Any attempt to use "getuser \<handle> xtra \<!ANYTHING!>" will result in the ENTIRE xtra list (dict) being returned.

\<Domino> .tcl getuser domino xtra zodiac

It should reply "capricorn" but, instead, it replies:

\<Bot> Tcl: CONSOLE {#Channel mpjkcobxswv12345678 - 1 0 -1} HOSTS {\<list of all hosts>} PASS \<encrypted pass> BOTADDR {} LASTON {{#Channel} 1493192715} INFO {} XTRA {\<sublist name> \<sublist item> [\<sublist name> \<sublist item> [...]]} COMMENT {}

The "anything" isn't actually parsed; the value is irrelevant: it is ignored. Requestion "xtra \<anything>" acts like the new [getuser] syntax: return a full dict of all known user data (both intrinsic and xtra, putting xtra into a sub-list). Any value for the "xtra" element triggers this; whether or not there is actual data to retrieve is ignored.

**Comment by ghost** [comment]
Confirmation:

1.8.1 [release] bot:

\<Domino> .tcl $::version
\<OldBot> Tcl error: invalid command name "1.8.1"
\<Domino> .tcl setuser domino xtra cow moo
\<OldBot> Tcl: 
\<Domino> .tcl getuser domino xtra cow
\<OldBot> Tcl: moo

1.8.1+sslserverlist bot (current git download version):

\<Domino> .tcl setuser domino xtra cow moo
\<Bot> Tcl: 
\<Domino> .tcl getuser domino xtra cow
\<Bot> Tcl: CONSOLE {#BotHouse mpjkcobxswv12345678 - 1 0 -1} HOSTS \<and all that user data crap>

Non-XTRA data works normally.

**Comment by maimizuno** [comment]
Given the severity of the issue, when will you update the "name" of the current release (from "1.8.1+sslserverlist" to something else so we know if we have the corrected version or not)?
