### ISSUE TITLE
Encrypt/decrypt upgrade issue

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#384]
Issue re: encrypt/decrypt upgrade (details irrelevant).

**Comment by Cizzle** [comment]
Sometimes things need to be "broken" for progress to happen. ECB is insecure and =SHOULD NOT= be used.

I don't see why using a global var would be any better for backward compatibility. If people just upgrade, they reuse their existing conf and won't have that setting and thus use default CBC mode anyway.

I also don't see how this is not backward compatible, ECB mode is still available AND can be enforced.

This is also the develop branch, not stable. A stable release of this will be accompanied by upgrading docs where this is mentioned.

The tcl-commands.doc (and other docs) are indeed not yet fully synced, this will be taken care of.

**Comment by ghost** [comment]
Two bots using the same code (a 1.6.21 (or a 1.8.1) and a 1.8.2) will produce different values; if the bots work together via botnet, this will cause mismatches in data (already encountered) and cause issues (also already encountered). Breaking code just "for the sake of progress" with no bridge just doesn't help; not everyone can just MAGICALLY upgrade all of their bots to "the latest and greatest" (one person does not own all shells a given botgroup uses for their botnet), and thus, there will be generational issues; one single generation's (1.8.1 vs 1.8.2) code is already broken; I have to back*-compat* SIX versions of script to compensate for this drastic change.

The variable option allows backward-compatibility in one single place instead of changing every since use of the ENCRYPT command. Saying it's unusable because it's insecure is like saying: you can't connect bots together or users into DCC without SSL any more because straight telnet is "insecure" and you won' t allow it any more; "gotta break things to make progress."

Never mind. I'll just re-write everything to work around this.

**Comment by thommey** [comment]
Still valid, maybe introduce that config variable.
