### ISSUE TITLE
Event / init-server issue

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#386]
.

**Comment by thommey** [comment]
I have a suspicion: "channel add" statements in the config seem to immediately queue joins. Does this also happen while reading the configfile the first time (not even being really connected?)

**Comment by maimizuno** [comment]
As the chanfile loads somewhere in the sequence, it's hard to test this theory.

Putting raw TCL commands into the chanfile doesn't not trigger them; removing the chanfile will not allow you to test the issue (any server commands will trigger, then, the bot will sit there as there are no instructions to join any channels by config file or chan file).

**Comment by maimizuno** [comment]
Can't test using a WEDGE to replace the channel modules load to handle server issues before joining channels; dependencies by other modules auto-load the channels module; wedges are useless, cf. #401.

**Comment by ghost** [comment]
Status?
