### ISSUE TITLE
'./eggdrop -c' should not work without -n

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#391]
Per help, 
```
-nc  Don't background; display channel stats every 10 seconds.
```
There is no '-c' option listed as a valid option in the help. The -n flag keeps eggdrop in the foreground. Running './eggdrop -c' without a -n appears to start the bot into background normally, without the -c causing any different functionality. Using -c by itself should probably error and not allow eggdrop to run. Thoughts?

**Comment by vanosg** [comment]
Same goes for the -t option by itself
```
-nt  Don't background; use terminal to simulate DCC chat.
```
-t launches without any noticeable change or error.

**Comment by Cizzle** [comment]
How about we change the help to show:
```
Usage: eggdrop [options] [config-file]

Options:
-n Don't background; send all log entries to console.
-c  Don't background; display channel stats every 10 seconds.
-t  Don't background; use terminal to simulate DCC chat.
-m   Create userfile.
-h   Show this help.
-v   Show version info, then quit.
The -n, -c and -t cannot be used together.
```
In the code we remain backward compatible of course, only a few minor changes needed (`backgrd = 0` at -c and -t and bitflags of 24 and 20).

**Comment by vanosg** [comment]
I really like that suggestion- I can't think of any reason the n flag is still needed, except as a carryover from some long-ago design decision we could get around, especially with the new code (as you identified). 

As a philosophical point, I think 1.9.0 might be a better opportunity to formally implement a command line change in the documentation while maintaining backwards compatibility (and an associated deprecation notice), and 2.0 to remove the 'old' way altogether, similar to our discussion on the CBC encryption.

**Comment by Cizzle** [comment]
Having checked the code, providing just -t or -c does not do anything without the -n, so it's just as if no flag was supplied.
I'm OK with the roadmap, the code in 2.0 will need some extra checks though to have -t/c/n be mutually exclusive.

**Comment by vanosg** [comment]
TODO: Update return value to 1 (or other value) when these errors occur (currently 0 is returned).
