### ISSUE TITLE
$::_* variables still being assigned globally

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#414]
A continuing issue with what was patched in: #137 

::_out1:server
::_out2:privmsg #Channel :Domino (Domino) just cleared my queues: ALL (40)
::_out3:sent
::_need1:#Channel
::_need2:op
::_log1:v
::_log2:*
::_log3:[!s] notice Domino :::_log2:*
::_pub1:Domino
::_pub2:Domino@Coder
::_pub3:Domino
::_pub4:#Channel
::_pubm1:Domino
::_pubm2:Domino@Coder
::_pubm3:Domino
::_pubm4:#Channel
::_pubm5:$$ foreach a [info vars ::_*] { if ![string eq "" [set $a]] { notice Domino $a:[set $a] } }
::_raw1:Domino!Domino@Coder
::_raw2:PRIVMSG
::_raw3:#Channel
::_cron1:18
::_cron2:19
::_cron3:01
::_cron4:06
::_cron5:04
::_time1:18
::_time2:19
::_time3:01
::_time4:05
::_time5:2017

Any variables not listed are set to "" (blank). Shouldn't they be null / unset (only used for their bind triggers, then unset, or is that not possible due to stackable binds)?

**Comment by thommey** [comment]
This is part of #51 and will be fixed when that is handled, at the same time. I changed the decription of #51 to reflect that those variables will be eliminated by it as well.

**Comment by michaelortmann** [comment]
The list above is not complete. Example: _notc1
