### ISSUE TITLE
matchattr: false positives or just wrong responses

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#419]
matchattr <handle> &h #ValidChannel returns true when when there are NO local (channel) flags.

\<Domino> $$ chattr domino #channel
\<Bot> [TCL (0ms)] aefghjlmnoptuvwxyzMN|-
\<Domino> $$ matchattr domino &h #channel
\<Bot> [TCL (0ms)] 1
\<Domino> $$ matchattr domino h #channel
\<Bot> [TCL (0ms)] 1
\<Domino> $$ matchattr domino h
\<Bot> [TCL (0ms)] 1

As you can see below, false-positives are being triggered as such:

b c i [Neither global nor local flag exists, yet, local is showing a match via "&" and "|" (both produce the same results)]

h j p t x [only exists as a global flag, yet, the local flag is showing a match]

\<Domino> $$ chattr domino #channel
\<Bot> [TCL (0ms)] aefghjlmnoptuvwxyzMN|-

Notice: I have \*NO\* local-level flags in this example, only global flags.

Here's a loop I did; see the insanity below:

\<Domino> $$ foreach a [alphabet -split -lower] { msghomer ${a}:GLOBAL([matchattr domino $a]):LOCAL:&([matchattr domino &$a #channel]):LOCAL:|([matchattr domino |$a #channel]) }
\<Bot> a:GLOBAL(1):LOCAL:&(0):LOCAL:|(0)
\<Bot> b:GLOBAL(0):LOCAL:&(1):LOCAL:|(1)
\<Bot> c:GLOBAL(0):LOCAL:&(1):LOCAL:|(1)
\<Bot> d:GLOBAL(0):LOCAL:&(0):LOCAL:|(0)
\<Bot> e:GLOBAL(1):LOCAL:&(0):LOCAL:|(0)
\<Bot> f:GLOBAL(1):LOCAL:&(0):LOCAL:|(0)
\<Bot> g:GLOBAL(1):LOCAL:&(0):LOCAL:|(0)
\<Bot> h:GLOBAL(1):LOCAL:&(1):LOCAL:|(1)
\<Bot> i:GLOBAL(1):LOCAL:&(1):LOCAL:|(1)
\<Bot> j:GLOBAL(1):LOCAL:&(1):LOCAL:|(1)
\<Bot> k:GLOBAL(0):LOCAL:&(0):LOCAL:|(0)
\<Bot> l:GLOBAL(1):LOCAL:&(0):LOCAL:|(0)
\<Bot> m:GLOBAL(1):LOCAL:&(0):LOCAL:|(0)
\<Bot> n:GLOBAL(1):LOCAL:&(0):LOCAL:|(0)
\<Bot> o:GLOBAL(1):LOCAL:&(0):LOCAL:|(0)
\<Bot> p:GLOBAL(1):LOCAL:&(1):LOCAL:|(1)
\<Bot> q:GLOBAL(0):LOCAL:&(0):LOCAL:|(0)
\<Bot> r:GLOBAL(0):LOCAL:&(0):LOCAL:|(0)
\<Bot> s:GLOBAL(1):LOCAL:&(0):LOCAL:|(0)
\<Bot> t:GLOBAL(1):LOCAL:&(1):LOCAL:|(1)
\<Bot> u:GLOBAL(1):LOCAL:&(0):LOCAL:|(0)
\<Bot> v:GLOBAL(1):LOCAL:&(0):LOCAL:|(0)
\<Bot> w:GLOBAL(1):LOCAL:&(0):LOCAL:|(0)
\<Bot> x:GLOBAL(1):LOCAL:&(1):LOCAL:|(1)
\<Bot> y:GLOBAL(1):LOCAL:&(0):LOCAL:|(0)
\<Bot> z:GLOBAL(1):LOCAL:&(0):LOCAL:|(0)

I know you hate me.

**Comment by vanosg** [comment]
On quick glance, it looks like a matchattr run against a non-channel flag (CHAN_VALID) incorrectly returns a 1- I don't think it has anything to do with matching incorrectly against the global flags. 

I'd start looking at line 252 in tcluser.c as a potential culprit, ```user.match = FR_GLOBAL | (argc == 4 ? FR_CHAN : 0) | FR_BOT;``` , it seems to force a comparison against global flags? mebbe.

**Comment by ghost** [comment]
@thommey
