### ISSUE TITLE
Tcl-API: extend channel get to list keys/values

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#421]
"channel get #chan" should return a dict, similar to "getuser handle"

**Comment by ghost** [comment]
To not break older scripts, can this be done as a variant command?

channel stat #list

Just like "file [L]stat"

That way, scripts aren't broken but the feature is available to upgraded / new scripts.

**Comment by thommey** [comment]
How does it break scripts? Do scripts rely on [channel get #chan] being an error?

**Comment by thommey** [comment]
Err, i was just informed that [channel get] already returns a list of key/values for channel settings since 1.6. Sorry for the confusion, this is already implemented then. Together with [chansettype] there is nothing left to do to improve it. Closing the ticket.
