### ISSUE TITLE
Telnet / Terminal Colors

### ISSUE THREAD

**Issue by rcschaff82** [eggheads/eggdrop#443]
Would it be possible to convert \003 to the proper format for Terminals and Consoles of \033[..m

ex \00304 would become \033[0;31m

**Comment by thommey** [comment]
I believe partyline connections have that functionality if an actual telnet client is detected connecting to it.
The command to toggle it manually (if telnet is not autodetected) is ```.fixcodes```.
Is that what you mean? If it's not, could you elaborate where you would like those translated?

**Comment by vanosg** [comment]
Is there any further comment on this issue, or can it be closed?
