### ISSUE TITLE
Check hosts file before DNS lookup?

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#457]
/etc/hosts has the following entry:
```
172.17.0.2	nosslbot nosslbot eggdrop_botnetnossl
```
yet
```
[21:02:41] #eggdrop# link bot2
[21:02:41] Linking to bot2 at nosslbot:1111 ...
[21:02:41] DNS Resolver: Creating new record
[21:02:41] DNS Resolver: Sent domain lookup request for "nosslbot".
[21:02:41] DNS Resolver: Domain does not exist.
[21:02:41] DNS Resolver: Lookup failed.
[21:02:41] DNS resolve failed for nosslbot
[21:02:41] Failed link to bot2.
```
Should we be checking the hosts file first?

**Comment by vanosg** [comment]
This is a dns.mod issue; hosts lookup works if dns.mod is not loaded

**Comment by ghost** [comment]
bump, this is a problem for me too because I'm using --link with docker to set the hostname / ip address of the irc server it needs to connect to.

**Comment by ghost** [comment]
the bot wont even start with my configuration if I remove the dns module, so I don't think that will do.

**Comment by ghost** [comment]
if I remove the dns module it bails always with the following error
```
|[17:18:44] * ERROR: Failed to initialize foreground chat.
[17:18:44] Warning: Attempt to kill un-allocated socket 0!

```

**Comment by michaelortmann** [comment]
Thanks for the report!
So you found **another**, more problematic bug, here, when you commented out `loadmodule dns`
See Fix #658.

To be sure:

Can you please tell me if you have both of the following options commented out and startet eggdrop with `./eggdrop -nt`?

```
# loadmodule dns
# listen
```

Thank you!

**Comment by michaelortmann** [comment]
eggdrops code is full with check like "if (term_z)"... its not fast to fix all places to make "0" a valid value also and it doesnt feel good to do so... "if (term_z) > -1"  looks ugly.  maybe it wasn't a good idea to change that variable "n" to overwrite "term_z" - now we have a problem we probably did't have before .

**Comment by michaelortmann** [comment]
There may also be another bug in misc.c:
```
  if (!backgrd && !con_chan && !term_z)                                          
    dprintf(DP_STDOUT, "%s", out);  
```
Shouldnt that read `term_z` instead of `!term_z` ?

It could fix #627

**Comment by vanosg** [comment]
@paigeadelethompson how exactly are you using --link? That should be to directly connect to a different docker container name, no? I'm not familiar with how you're using that based on your description, but at first glance I'm not seeing how --link is related to the local hosts file. Can you provide some extra detail on that? Thanks

**Comment by vanosg** [comment]
@paigeadelethompson do you have any other input on this? Thanks

**Comment by michaelortmann** [comment]
Eggdrops DNS module uses the resolver library, which does not look up /etc/hosts.

"Normal" system functions, like gethostbyname() are configurable and normally configured to look up /etc/hosts.

See:

https://serverfault.com/questions/498500/why-does-the-host-command-not-resolve-entries-in-etc-hosts

So, when we use the resolver library, we will have to implement /etc/hosts lookup ourselves.

Thats what i will do now...

**Comment by vanosg** [comment]
So this isn't building it into eggdrop, this is building it into dns.mod. dns.mod is an alternate way to do DNS resolution, one that lets it do it asynchronously and doesn't hold up other bot functions. I'm 100% ok with dictating what it checks. 

But I'm surprised a bit by what you said- unloading dns.mod checks/uses the hosts file (native OS stuff), while dns.mod does not, so I think there may be a little more at play

Either way, I'm happy to build in a /etc/hosts check

**Comment by michaelortmann** [comment]
i figured it out:
 /etc/nsswitch.conf is only used if you use functions like getnameinfo() getaddrinfo() gethostbyname().
when you use the resolver lib directly as we do, /etc/hosts is never checked.
so, yes, we must build our own check into dns.mod now.

**Comment by michaelortmann** [comment]
dns mod dns_forward() is calling into net.c:setsockname() which uses gethostbyname() with timeout. not really async as far as i see?
