### ISSUE TITLE
Tcl getuser command submits botaddr ports in wrong order

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#459]
Documentation implies (doesn't actually state) the order for changing a botaddr with setuser is address, telnet port, bot port:
```
    BOTADDR  returns a list containing the bot's address, telnet port, and
             relay port (bot-only)
```
But it appears it reverses user and bot ports when you submit it
```
> .tcl setuser ztestbot botaddr 1.1.1.1 2222 3333
>  tcl: builtin dcc call: *dcc:tcl vanosg 9 setuser ztestbot botaddr 1.1.1.1 2222 3333
>  tcl: evaluate (.tcl): setuser ztestbot botaddr 1.1.1.1 2222 3333
> Tcl: 
> .whois ztestbot
> HANDLE                           PASS NOTES FLAGS           LAST
> ztestbot                         yes      0 b               2017-08-23 (unlinked)
>   ADDRESS: 1.1.1.1
>      users: 3333, bots: 2222
>   BOT FLAGS: gs
```
Recommend adjusting documentation for 1.8.3, and discussing the merits of "fixing" this in 2.0, as it would be a non-backward compatible change to the API. (Reminder to self, if we do that, please submit a new issue for that and tag it 2.0 before we close this one).

**Comment by Cizzle** [comment]
I think clarifying the docs is enough. IMO there's nothing to fix codewise.

**Comment by vanosg** [comment]
For bonus consideration points, 
```
setuser bot botaddr 1.2.3.4 5555
```
sets only the bot port (not the user port). I'm ok with modifying docs, but just want to point out how non-standard this behavior is when compared to the +bot syntax, where specifying a single port sets bot bot and user. 

I'm on a standardization kick this month, it seems :key: :seedling: :selfie:

**Comment by vanosg** [comment]
Re-reading the help, you're right, the code is fine. I'll update the docs and close this out shortly.

**Comment by ghost** [comment]
In the past, setting only the 1st port would set both bots & users ports. In a change somewhere in 1.6 branch, it only set the bot port (users remained 3333 or some other default). Which is the intended behavior?

**Comment by vanosg** [comment]
Working on this now - bot foo is added like this:

```
foo                              no       0 b               never (nowhere)
  ADDRESS: 1.1.1.1
     users: 5555, bots: 4444
```
Doing a chaddr with *only one port* argument changes both bot and user ports:
```
.chaddr foo 1.1.1.1 3333
foo                              no       0 b               never (nowhere)
  ADDRESS: 1.1.1.1
     users: 3333, bots: 3333
```
Using the Tcl command with *only one port* argument changes only the bot listening port:
```
.tcl setuser foo botaddr 1.1.1.1 4444
foo                              no       0 b               never (nowhere)
  ADDRESS: 1.1.1.1
     users: 3333, bots: 4444
```

To standardize this between chaddr and the associated Tcl setuser command, I think it makes sense to implement this the way that chaddr does, where one argument changes both values, and two arguments allows you to set them individually. Comments/Improvements?

**Comment by Cizzle** [comment]
I agree.

**Comment by vanosg** [comment]
Ok. Part 2- can anyone come up with a reason to say this changing this is not backwards compatible (and thus belongs in 2.0)? While technically it changes functionality that could break existing scripts, every use case I can think of doesn't seem plausible that a script writer would use it this way for, but that's not my thing. On the other hand, I'm not comfortable calling this a 'bug', as it appears to be intentional coding on both commands, just not synched. 

I really want to do this now, but I can't get away from believing this is a 2.0 thing. Can someone convince me otherwise?

@maimizuno likely has some thoughts on this
