### ISSUE TITLE
Create 'addserver' command.

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#477]
Add an 'addserver' command to eventually replace 'set servers {}' in the config. Still support 'set servers' for backwards compatibility. See #470 for background.

**Comment by ghost** [comment]
Will there be DEL and EDIT options? $::servers will still return a current list of servers?

**Comment by ghost** [comment]
On bot start up [1.8.2+addbot]:
[01:06:45] Trying server [irc.server.com]:6667
The "[]" are shown as part of the server name, even though they're not there.

Why?

**Comment by vanosg** [comment]
For tracking purposes, could you please open a new issue with this? Thanks
