### ISSUE TITLE
$::servers issue with passwords; DNS failure

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#503]
$::servers normally preserves a space (by creating an extra TCL list element, index 1) to keep a server's local name. The problem is: when using a server with a port and password, the entry becomes a corrupted multi-element list that fails the DNS look-up.

set servers server-IP:6667:password
... immediately followed by this PUTLOG line:
putlog "Servers: $::servers"
[01:40:58] Servers: {server-IP:6667:password } <--- note the extra space
... no other changes to $::servers occurs ...
[01:41:02] Trying server [server-IP:6667:password ]:6667 <--- note the extra space, the unnecessary "[]" square brackets, and extra ":6667"
[01:41:02] DNS Resolver: Used failed record: server-IP:6667:password  == ??? <--- notice double (extra) space here
[01:41:02] Failed connect to server-IP:6667:password  (DNS lookup failed) <--- note the double (extra) space

The entire list element is sent for DNS look-up (which would obviously fail).

A few seconds later, the same server element is re-tried ($::servers still only has ONE entry):
[01:42:20] Trying server [server-IP]:6667
[01:42:20] Connected to server-IP
... and the password is successfully sent to the server; the bot can connect properly.

.tcl set ::servers
Tcl: {server-IP:6667:password irc.server.network.name} {[server-IP:6667:password ]:6667 }

Why does it work the second time (upon retry), but, not the first time (altered)? Why is the second entry there, with the ([]) square brackets? What added it?

**Comment by vanosg** [comment]
Are you using an ipv4 or ipv6 address?

**Comment by ghost** [comment]
v4

**Comment by vanosg** [comment]
Is your bot already connected to a server during this action, or no? If no, can you try it while it is connected to an IRC server and see if the activity is repeated?

A full screen capture of the activity would be preferred; I cannot reproduce based on my interpretation of your activity, nor a few other variations. Thanks

**Comment by ghost** [comment]
This happens on a cold start (the previously-shown log). It does NOT happen on a manual .JUMP.

**Comment by vanosg** [comment]
Setting a port and password for set servers in the config still does not give me the error you are encountering. 

I tried it two ways (I don't have a non-SSL-allowing server requiring a password):

```
{irc.freenode.net:6667:forfunsies }
```
and then it joins on the first try with:
```
[04:11:55] Trying server [irc.freenode.net]:6667
```

and also on a server that actually requires a password, but with SSL:
```
{server.org:+7000:password }
```
and connecting I get
```
[04:04:47] Trying server [server.org]:+7000
```
and in the name of thoroughness, 
```
[04:16:02] {91.217.189.42:6667:forfunsies }
```
```
[04:16:03] Trying server [91.217.189.42]:6667
```

I'd have to look at the exact server address you were using, I suppose? Trying to replicate, I get no error and it connects on first try.

**Comment by Cizzle** [comment]
Same here, can't replicate. Might be interesting what "password" exactly is?

**Comment by ghost** [comment]
I've been able to re-produce this bug on servers that have NO password listed.

[2018-05-06 21:35:04 -0800] <Test-Bot> [00:35:05] Trying server [IP:6667 ]:6667
[2018-05-06 21:35:04 -0800] <Test-Bot> [00:35:05] DNS resolve failed for IP:6667 
[2018-05-06 21:35:04 -0800] <Test-Bot> [00:35:05] Failed connect to IP:6667  (DNS lookup failed)

Again, it's taking the port and considering part of the server \*name\* instead of the port.

.tcl return $::servers
<Test-Bot> {IP:6667 Server.name} {[IP:6667 ]:6667 }

Notice the brackets [and the space] in index #1? That's what's driving us nuts.

From teh config file:

set servers {
IP:6667
}
... and ...
set default-port 6667

Yes, only ONE entry in $servers; why there are two after bot start up is not understood.

I've put a zillion DEBUGS into all scripts, \*AND\* , I've run the bot with \*NO\* scripts at all.

You know me to be thorough, so, don't think me crazy and dismiss this. Well, one of you, anyway.

**Comment by vanosg** [comment]
Still can't repliacte. Can you try joining it to freenode and see if it will replicate there? Can you paste your config file so we can review it? Are you using 1.8.3? I've tried every setting I can think of that deals with IPv4/6, and I don't see this issue. 

Full logs of actual connections and your config file is likely the only way we'll be able to resolve this. And by full log, I mean from the start of the bot all the way to the error occurring, not just the error, so we can better gauge context. Thanks

**Comment by ghost** [comment]
... then let this remain closed.

The owner of the bot in question has it on a private network and will not allow me to post that info. I will try to set-up a bot on a "public" server to replicate under (otherwise) the same circumstances. If I succeed, I will contact you.

**Comment by ghost** [comment]
I found the problem after some extensive testing.

Filing new bug. (Tried to get help on freenode; got something else instead.)
