### ISSUE TITLE
Bug: New eggdrop installation crashes on partyline command .handle

### ISSUE THREAD

**Issue by eelcohn** [eggheads/eggdrop#512]
### Description:
Found a bug some days ago on a new docker installation, but I've also just confirmed it on a regular eggdrop install. It causes a segmentation fault and crashes eggdrop. Not sure what causes it, but it seems to be related to the absense of a user file on a new bot.

### Ways to reproduce:

Docker:

1. Create a new docker container with eggdrop-docker-v1.8.3
2. Open the terminal and do `.handle crasher`

Regular install:

1. Do a new, clean install of eggdrop v1.8.3 and Tcl 8.6.8 on your system
2. Edit eggdrop.conf, and edit `username`, `nick`, `altnick`, `realname`, `admin`, `network` and `channel add #lamest`
2. Start it with `./eggdrop -ntm eggdrop.conf`
3. Enter `.handle crasher` on the partyline

### Found behaviour:
```
[17:55:52] * Last context: tclhash.c/729 [Tcl proc: *dcc:handle, param:  $_dcc1 $_dcc2 $_dcc3]
[17:55:52] * Please REPORT this BUG!
[17:55:52] * Check doc/BUG-REPORT on how to do so.
[17:55:52] * Failed to write DEBUG
[17:55:52] * SEGMENT VIOLATION -- CRASHING!
Segmentation fault
```

### Expected behaviour:
Catch the error, handle it in a clean way and show a user-readable message

**Comment by vanosg** [comment]
First - thank you for providing such a clear, precise set of steps to replicate this! It was a huge help.

I can confirm this corner-case usage crashes eggdrop. There is no crash in when no CLI flags are provided, -nt flags are provided, or -m is provided- Only -ntm creates this issue.

Thank you for reporting, we'll get to this shortly.
