### ISSUE TITLE
Show SSL link status in .(v)bottree

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#513]
This is a feature request to add an indicator whether a link is SSL or not in the bottree.
I am not sure if we can only do that for first-level links or are also aware of the distant ssl status. 

Found by: tuvok

**Comment by tuvok81** [comment]
and it was nice when you can make some shortcut from .bottree like .bt and .vbt for .vbottree

**Comment by tuvok81** [comment]
a Idea from me was

> [22:52] <login> LoGiN (1.8.3.3) (ssl)
> [22:52] <login>     |-+Worf (1.8.2.3) (ssl)
> [22:52] <login>     |-+eth0 (1.8.3.3) (ssl)
> [22:52] <login>     |-+Dummer (1.8.3.3) (ssl)
> [22:52] <login>     |-+Riker (1.8.3.3) (ssl)
> [22:52] <login>     |-+R2-D2 (1.8.2.3) (ssl)

or 

> [22:52] <login> LoGiN (1.8.3.3)
> [22:52] <login>     |-+(+)Worf (1.8.2.3)
> [22:52] <login>     |-+(+)eth0 (1.8.3.3)
> [22:52] <login>     |-+(+)Dummer (1.8.3.3)
> [22:52] <login>     |-+(+)Riker (1.8.3.3)
> [22:52] <login>     |-+(+)R2-D2 (1.8.2.3)

and this will only show for the bot they are connectet to his HUB or Alternate Bot
