### ISSUE TITLE
Feature request: botnet throughput console

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#521]
.

**Comment by Cizzle** [comment]
I believe the "m" stands for "me", so you have "me" sending to target/receiving from source. I'm fine by changing it to "b" which'd still be logical then as "bot" for the ghuv flags; unless someone opposes...?

**Comment by ghost** [comment]
Issue acknowledged by coders; issue no longer needed.

**Comment by ghost** [comment]
Cizzle commented:
>I believe the "m" stands for "me", so you have "me" sending to target/receiving from source

Makes sense. Problem is: it's ambiguous with IRC mode queue output; the marker is the same ("[m->]"). The botnet data stream header should be (IMnshO) different, in case you're trying to read through your console output to debug a problem, or, using a script to scan through a log file which may have both. Plus, isn't it better to favor the more-intuitive "understood-at-a-glance" method?
