### ISSUE TITLE
$::servers / .jump <server> lists

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#523]
Related to (research & explanation for) #503 

I found something that may explain what is happening.

Notice I'm using the (old?!) syntax: server:port 

[2018-05-24 15:21:27 -0800] \<Domino\> .jump server.ip:+7001
[2018-05-24 15:21:28 -0800] \<Dorito\> [2018-05-25 00:21:01 +0200] #Domino# jump server.ip:+7001 6667 
[2018-05-24 15:22:02 -0800] \<Dorito\> Jumping servers......
[2018-05-24 15:21:28 -0800] \<Dorito\> [2018-05-25 00:21:01 +0200] #Domino# jump server.ip:+7001 6667 

It didn't treat the port # as a separate entity; it combined them as one entity and attached $::default-port  to the entire entry (server.ip:port), creating that cluster-fuck of an address "server.ip:+7001 6667"

This is *obviously* not the desired behavior

If I obey the pattern of the output above and make one change: ";" to " " (space):

[2018-05-24 15:22:02 -0800] \<Domino\> .jump server.ip +7001
[2018-05-24 15:22:02 -0800] \<Dorito\> [2018-05-25 00:21:36 +0200] #Domino# jump server.ip +7001 
[2018-05-24 15:22:02 -0800] \<Dorito\> Jumping servers......
[2018-05-24 15:22:03 -0800] \<Dorito\> [2018-05-25 00:21:37 +0200] Trying server [server.ip]:+7001

Perfect jump! (It connected.)

... YET ...

From eggdrop.conf (the example enclosed with 1.8.3):
set servers {
  you.need.to.change.this:6667
  another.example.com:7000:password
  [2001:db8:618:5c0:263::]:6669:password
  ssl.example.net:+6697
}

So, the issue isn't whether or not a server has a password or not (that was the example at the time the bug #503 was first reported); it's the syntax of the server: how it is listed in the $::servers variable doesn't match how it is in the manual syntax!

$::servers says: address:port:password
.jump says: address port password
MISMATCH!

Was this changed during all the fuss of IPv4 vs IPv6 server addresses (because of the square-brackets) changes?????

Further tests reveal that adding the password (server.ip:port:password) continues the same as above, so it wasn't the password itself that affected anything; it's along for the ride! And, yes, DNS names for servers are treated the same as IP server addresses.

Also, the above issue exposed yet another problem: trimming. Due to the syntax of adding spaces (or tabs) within braces in code / config files, part of the issue include spaces as part of the server name

From my ORIGINAL report:

"[server-IP:6667:password ]:6667"

Notice the " " before the close-bracket? That's from the $::servers setting from the config file. Can the server name, when read from $::Servers during a JUMP request, be whitespace-trimmed to address this?

There goes an hour of my life.

**Comment by vanosg** [comment]
So in short, what is the issue you're encountering now? You mention a mismatch between the variable and the display; how is that inducing an error? What is the error relationship between $servers and the jump command display you're trying to make? If I'm following your thread correctly, you just mis-used the syntax for jump. Is there more to it than that?

**Comment by ghost** [comment]
If the logs snippets and explanations don't clarify all of the problems, then there's nothing I can do. I can't get a coder in channel (and only get bad suggestions or rude people telling me off), and my research goes misunderstood.

No more bugs reports. If anyone wants to fix this, Pixelz knows where I can be found.
