### ISSUE TITLE
Megahal module not answering

### ISSUE THREAD

**Issue by fnordson** [eggheads/eggdrop#524]
Hi,

i updated eggdrop from 1.6.x to the newest version and have an issue with the megahal module (took the new one pointed out here somewhere). 

I installed it properly, it runs, but it won't react on the set words anymore. 
However it seems to throw words from time to time. 
I have no idea what to do. It worked before the update, now it doesn't. 

I've also set: .chanset #channel +megahal +learnall +freespeak

**Comment by ghost** [comment]
What does the coder of the module say? Have others had the same issue (or similar)?

**Comment by michaelortmann** [comment]
can someone write a simple "howto repeat this bug" test case?

**Comment by fnordson** [comment]
FYI: I made this update after I updated raspbian to jessie from wheezy. Since I was unable to fix the problem or find help anywhere, I rolled back everything from a back up, updated the distro but left the old 1.6 eggdrop version. 
I don't plan to try this again, it was just to much trouble.

**Comment by ghost** [comment]
So ... this is no longer an active issue? If there's no test case available (and we don't know if this is an OS issue, an Eggdrop issue, or a code module issue now), can this be closed?

**Comment by fnordson** [comment]
Well it's no issue for me since I abandoned this version and did not try again.  
I don't know if it would be an issue again if I tried again
I don't know if it's an issue for anybody else going the same way.

**Comment by Cizzle** [comment]
I have tested the MegaHAL module provided at https://ftp.eggheads.org/pub/eggdrop/modules/1.8/megahal.mod.2.7-pseudo.tar.bz2 and have not encountered the problem you describe.
After having set the 3 udef flags, the bot occasionally talks and responds when addressed as is mentioned in the readme.
I did notice a lot of debug messages about non-mallocced pointers but that'd be another issue.
