### ISSUE TITLE
LDFLAGS and CFLAGS are not respected

### ISSUE THREAD

**Issue by sbraz** [eggheads/eggdrop#526]
Hello,
This was reported [a long time ago](https://bugs.gentoo.org/335230) but it looks like the problem is still present today.
The Gentoo build works around this by doing
```sh
sed -i -e '/\$(LD)/s/-o/$(CFLAGS) $(LDFLAGS) &/' \
   src/mod/*.mod/Makefile* src/Makefile.in
```

**Comment by michaelortmann** [comment]
I took a look at the Build log attached to:
https://bugs.gentoo.org/335230#attach_245332
and i find:

[...]
'-DCCFLAGS="i686-pc-linux-gnu-gcc -pipe -O2 -pipe -Wall -I.. -I.. -DHAVE_CONFIG_H  "' \
'-DLDFLAGS="i686-pc-linux-gnu-gcc -pipe"' \
[...]
 * QA Notice: Files built without respecting LDFLAGS have been detected
[...]

I don't have more information than this, and from what i see here, patch #568 could fix the QA Notice.
