### ISSUE TITLE
"botisop", "botisvoice", "isop", "isvoice" etc. tcl commands not working on v1.8.3

### ISSUE THREAD

**Issue by CaPaCuL** [eggheads/eggdrop#530]
Hi guys.

I used version eggdrop1.6.21 earlier.

However, a few days ago I installed version eggdrop-1.8.3 and moved my old bot configuration & tcl files to version eggdrop-1.8.3.

The file ircturk.multi.tcl runs in eggdrop1.6.21; it made some mistakes in eggdrop-1.8.3.

.tcl set errorInfo
Tcl: No such user.
Tcl:     while executing
Tcl: "setuser $bnick HOSTS $mh"
Tcl:     (procedure "onjoin_account" line 8)
Tcl:     invoked from within
Tcl: "onjoin_account $chan"
Tcl:     (procedure "check_onjoin" line 4)
Tcl:     invoked from within
Tcl: "check_onjoin $_jp1 $_jp2 $_jp3 $_jp4"

"onjoin_account" and "check_onjoin" procedures are in the ircturk.multi.tcl file, and I am adding this file.

I ran the ".tcl botisop #BotChannel" command. Return:
"Tcl: 0"
However, the bot has got an op on that channel.

The return of "isvoice", "isop", "isvoice" command's return is "0". And again, the op and voice requirements are met.

I add the relevant tcl file.

Best Regards, Have a nice day.
[ircturk.multi.zip](https://github.com/eggheads/eggdrop/files/2201501/ircturk.multi.zip)

**Comment by vanosg** [comment]
This probably requires a little more in-depth troubleshooting that can be done over GitHub. I can say with certainy though that the botisop command (and others listed) work on several bots I just tried on, to confirm. Can you join #eggdrop on Freenode and ask for help there? It may have something to do with your server settings. Thanks

**Comment by ghost** [comment]
This script is a blatant rip-off of my script; it's an EARLY version of StormBot.TCL v3.1 (c. 1998); only the version information was changed. It will not run on 1.8 without SEVERAL modifications, generally.

But the original code (which I still have to run a bot on, because users still come in for it), works fine:

[2018-07-23 13:02:26 -0800] <~Domino> thunder tcl isop Domino #StormBot
[2018-07-23 13:02:27 -0800] -Thunder- [TCL: 0ms] 1

**Comment by CaPaCuL** [comment]
I made a change to the eggdrop.conf file, and these commands are now working:
[...]
#set opchars "@"
set opchars "@&~"
[...]

> This script is a blatant rip-off of my script; it's an EARLY version of StormBot.TCL v3.1 (c. 1998); only the version information was changed. It will not run on 1.8 without SEVERAL modifications, generally.

The tcl you mentioned was in a system similar to eggdrop. Turkdrop. I used the same name only by changing the channel and nick information. If you give me a version running at 1.8, I'd like to use it.

**Comment by ghost** [comment]
Off-topic, but: current version of the script (StormBot.TCL) is available from its home page: http://www.stormbot.org/

If you have resolved the original issue, please mark the bug as closeable, or, just close it.

**Comment by CaPaCuL** [comment]
> Off-topic, but: current version of the script (StormBot.TCL) is available from its home page: http://www.stormbot.org/

Thanks maimizuno.
