### ISSUE TITLE
.+ban durations are capped at 365 days

### ISSUE THREAD

**Issue by Robby-** [eggheads/eggdrop#541]
When wanting to set a ban like so, for a duration of 2 years, so 730 days:
`.+ban *!*@2001:db8::/32 #channel %730d You have been banned for... something.`

Then verifying it with:
`.bans *!*@2001:db8::/32`
```
Channel bans for #channel:  (* = not placed by bot)
! [  1] *!*@2001:db8::/32 (expires in 364 days)
        Robby: You have been banned for... something.
        Created 22:32
```
The duration seems to be capped at 365 days.

Not sure if this is intended or a bug (because why cap this?), but it would be great to have this cap removed, so longer bans can be set.

**Comment by Robby-** [comment]
Come to think of it, maybe this is also why there is no %N`y` for years (which would also be nice to have, by the way :P).

**Comment by michaelortmann** [comment]
in cmdschan.c there is limit for %d %h and %m.

for %d its 365
for %h its 8760 (365 * 24)
for %m its 525600 (365 * 24 * 60).

so whether a ban is defined in minutes, hours or days, its always capped at 365 days.

looks like an arbitrary limit easy to lift.

but we dont want to overflow integers, we should keep limit of the resulting expiration in seconds within MAX INT.

btw: there is redundant code, maybe put it into subroutine?

**Comment by vanosg** [comment]
Current thinking on this is to, for now, cap to a larger number (WHY DO YOU NEED A TEN YEAR TEMP BAN), and re-address this when the max date issue is fixed (also known as, kicking the can down the road)

**Comment by Robby-** [comment]
5 years would be plenty I think.

**Comment by michaelortmann** [comment]
we have only %d specifier. we cant have %y (leapyear?). how many days are 5 years? we dont know. irc discussion resulted in new limit 2000 days.
