### ISSUE TITLE
IP / vhost

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#544]
> Failed connect to <server IP> (Vhost set in config is not available on this machine)

Why would this matter when you're connecting to an IP? No look-up is happening, or, seems necessary. If the \*\*bot was able to start-up\*\*, then this shouldn't prevent direct-IP connections.

.. or does it have to? It seems there's "always a reason for" whatever.

**Comment by Cizzle** [comment]
The `vhost4` and `vhost6` settings that this error message refers to are not limited to hostnames. As the eggdrop.conf already states, this is `the particular IP to bind to` in case there are multiple available.
