### ISSUE TITLE
Build autogenerator for the doc/html files

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#55]
| Trac | Data |
| --: | :-- |
| Ticket | 55 |
| Reported by | @thommey |
| Status | new |
| Component | Documentation |
| Priority | major |
| Milestone | 1.8.0 |
| Version | 1.8.0 CVS |

Build autogenerator for the doc/html files to run during 'make dist' and remove the doc/html/\* from cvs

**Comment by thommey** [comment]
**Comment by freeder**
Ready to be closed? discussed, and determined future documentation mod's should occur in the html files, then use "lynx -dump file > documentation.txt" to convert to readable text. Unless there is a better way... markdown doesn't seem practical, and formatting plaintext to html is near impossible

**Comment by vanosg** [comment]
Closed via #227 - sphinx ftw!
