### ISSUE TITLE
party line notifications: botnet +h attempts

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#550]
Every minute, I get this:

\<Agnes> [2018-08-13 21:31:01 -0700] net: attempted socket connection refused: 127.0.0.1
\<Agnes> [2018-08-13 21:31:01 -0700] net: attempted socket connection refused: 127.0.0.1
\<Agnes> [2018-08-13 21:31:01 -0700] net: attempted socket connection refused: 127.0.0.1
\<Agnes> [2018-08-13 21:31:01 -0700] net: attempted socket connection refused: 127.0.0.1

This is because the bot's +h hub is offline.

Fine.

But, I'm also console +d6 (6 = special debugging log I use), via: .console -*+d6

I'm still seeing these messages.

Shouldn't these be restricted to either console +b or +u only? I would expect link failures to be in +b log, especially, not +d debug.

Also, the message is vague. Only after looking at the pattern (at every minute-1 second) did I realize what this meant: failed botnet auto-connect. Can the text be modified to me less ambiguous as to its purpose? Maybe something more obvious, like "Botnet connect attempt to Hub-Bot (127.0.0.1:65536) failed: connection refused" instead?

This is one of those error messages that are (1) in the wrong place, &, (2) aren't intuitive enough. After all, if you don't have $::RAW-LOG set to 1, then you'll never see this and know why your botnet isn't forming!

Also, why is this thrown FOUR times? I only have one +h.

Which reminds me: +t (for ternary/tertiary link): that idea died? :( With a large botnet, either a 3rd-link or an ordered link would be useful (botattrs of +0 (primary choice) .. +9 (last choice), in order) would be nice. However, waiting for 10 attempts to connect would mean 10 minutes before coming around to the hub again. This is where obeying $::connect-timeout would be useful (and make the process quicker).

**Comment by michaelortmann** [comment]
info: connection refused means host available, but port not. see https://nmap.org/book/man-host-discovery.html: If connect returns [...] ECONNREFUSED failure, the underlying TCP stack must have received a SYN/ACK or RST and the host is [...] available. it could help to not only report the host but also the port in this debug log.

analysis: the function producing the debug, a general non-blocking connect function, doesn't know about its caller, why it was called, what connection was attempted. it only sees the destination address host/port. i think a patch providing a real +b/+u log wont be fast/small.

info: to understand what the connect()/select()/getsockopt() code does:
see: http://cr.yp.to/docs/connect.html
and connect(2): EINPROGRESS: The socket is nonblocking and the connection cannot be completed immediately. It is possible to select(2) or poll(2) for completion by selecting the socket for writing. After select(2) indicates writability, use getsockopt(2) to read the SO_ERROR option at level SOL_SOCKET to determine whether connect() completed successfully (SO_ERROR is zero) or unsuccessfully (SO_ERROR is one of the usual error codes listed here, explaining the reason for the failure).
http://cr.yp.to/docs/connect.html. it could help to have more code documentation in this function.
