### ISSUE TITLE
TCL invite, ignore, exempt and ban have unchecked expire times

### ISSUE THREAD

**Issue by Cizzle** [eggheads/eggdrop#551]
The tcl_newignore, tcl_newchanban, tcl_newban, tcl_newchanexempt, tcl_newexempt, tcl_newchaninvite and tcl_newinvite functions lack checking of the expire time being too big, like done so for the internal ban, exempt, invite and ignore commands.
Specifiers should not be added.

**Comment by michaelortmann** [comment]
tcl_newchanban() and the likes are not only using expire time from tcl argument, but also from chan->ban and the likes, so we must also check for valid expire times when chan->ban and the likes are set.
