### ISSUE TITLE
$::servers

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#559]
Per a live conversation with thommey, this issue came up:

$::servers is actually processed as a STRING, not as a LIST. This causes several situations to come up; most are created due to cosmetics.

set servers {
\<tab>server1:port:pass
\<space(s)>server2:port:pass
}

This causes $::server (when the bot tries to connect) to become: "[server1:port:pass   ]:6667" (assuming $::default-port == 6667). Of course, you will get DNS resolution errors for this gob of crap, and, the bot won't show up. Due to where teh spaces are employed, usually, at least ONE of your servers will work: either the LAST one (in order).

otherwise, the trailing spaces are appended to the previous entry, creating "server1:port "

Other nonsense occurs when anything except this is used:

set servers {server1:port:pass server2:port:pass ...} ; # This works properly

Even \*THIS\* fails:

set servers [list server1:port:pass server2:port:pass ...]

Server #1 will be pulled as: "server1:port:pass " <--- notice the trailing space

Why $::servers is treated (and  processed) as a string was unknown; it is defined as a [proper] list in (most people's) config files, via {braces}. If processed as a proper list, all whitespace will safely fall-off as expected.

Pleased adjust the way $::servers / $::server are handled so they are treated as proper lists.

Also, the space-vs-colon issue may still exist: TCL code (script) vs. party line (.JUMP) seem to have different syntaces.

**Comment by ghost** [comment]
Originally reported as #503 &  #523

**Comment by ghost** [comment]
Also:

server list uses colons.
dcc's .JUMP uses spaces.

Mismatch.

**Comment by michaelortmann** [comment]
so many issues regarding server variable, let me pick them one by one.

**1. This causes $::server (when the bot tries to connect) to become: "[server1:port:pass ]:6667"**

i can't reproduce your example (with current git version of eggdrop).

eggrop.conf:
```
set servers {
<tab>server1:port:pass
<space(s)>server2:port:pass
}
```

partyline:
```
[00:14:48] Trying server [server1]:6667
[00:14:48] Failed connect to server1 (DNS lookup failed)
[00:15:48] Trying server [server2]:6667
[00:15:48] Failed connect to server2 (DNS lookup failed)
.servers
[00:27:18] #-HQ# servers
Server list:
  [server1]:6667 <- I am here
  [server2]:6667 
End of server list.
```

i need help reproducing.

**2. Trailing whitespace**

when i reproduce the trailing whitespace problem, i find the trailing whitespace inserted for every server and it doesn't depend on whitespace vs. tab.

eggrop.conf:
```
set servers {
<tab>server1:port:pass
<space(s)>server2:port:pass
}
```

partyline:
```
.set servers
Currently: {server1:6667 } {server2:6667 }
```

result of my analyzation:

the reason for the trailing whitespace is, that "usually" eggdrop would resolve a given servername to a its realname, like ip to host, and the line would become **the poodle’s core**:
```
Currently: {server1name:6667 server1realname} {server2name:6667 server2realname}
```

you need to be able to handle "server1name:6667 server1realname" anyway, so handling the whitespace without a realname should be cheap.

the function responsible for handling config setting servers is server.c:tcl_eggserver()

it would be easy to not append (equals strip) the whitespace in case no realname was resolved,
but it doesnt look like an eggdrop function is broken,
looks more like a user tcl script problem, that a tcl script has to take care to parse server string and strip whitespace.

**3. Even *THIS* fails: set servers [list server1:port:pass server2:port:pass ...]**

where is the beef, i mean, what the bug? as you mentioned earlier, the {} notation, as used by eggdrop.conf works as expected. looks more like feature request to also handle other notations. i don't see that comming, without proof we really need / want this.

**4. server list vs. jump syntax**

yes, its different, but its only a "small" inconvenience.

i would not change both syntaxes to support both types.

but of course, we could, and maybe should, break backward compatibility for 1.9 or 2.0 and change one of those to match the other one.

**now, all issues with $server should be dissected, or did i miss any?**

**Comment by vanosg** [comment]
With the merging of #863 I believe this is OBE- syntax has been standardized to spaces, and addserver adds servers one by one to the internal list.
