### ISSUE TITLE
Botnet linking with TLS (STARTTLS)

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#580]
From the leaf's point of view:

<Domino> .link MyHub
<Leaf> [17:34:19] #Domino# link MyHub
<Leaf> [17:34:19] Linking to MyHub at <Hub's IP>:9348 ...
<Leaf> [17:34:19] Got STARTTLS from MyHub. Replying...
<Leaf> [17:34:19] Received challenge from MyHub... sending response ...
... and nothing more happens.

On the target (MyHub)
<MyHub> [02:38:00] Telnet connection: <Leaf's IP>/39848
<MyHub> [02:38:00] Timeout/EOF ident connection
<MyHub> [02:38:00] Sent STARTTLS to Leaf...
<MyHub> [02:38:00] Challenging Leaf...
<MyHub> [02:35:02] TLS: failed in: SSLv2/v3 read client hello A.
<MyHub> [02:35:02] TLS: failed in: SSLv2/v3 read client hello A.
<MyHub> [02:35:02] TLS: failed in: SSLv2/v3 read client hello A.
<MyHub> [02:35:02] TLS: failed in: SSLv2/v3 read client hello A.
... this repeats until the leaf gives-up (timeout), APPROXIMATELY 40 TIMES !!
<MyHub> [02:39:01] Lost dcc connection to Leaf (telnet@<Leaf's IP>/39848)

Once this begins, I'm helpless to STOP it!

.DCCSTAT on the leaf provides:

<Leaf> 12 <MyHub's IP> + 9348 MyHub bot* waited 39s

<Domino> .tcl killdcc 12
<Leaf> Tcl error: invalid idx

Ummmm.... That's useless (and a lie)

Let's try on the MyHub!
<Domino> .dccstat
<Snip>
<MyHub> 25 <Leaf's IP> +38008 Leaf pass waited 25s
<MyHub> [02:41:26] TLS: failed in: SSLv2/v3 read client hello A.
<MyHub> [02:41:27] TLS: failed in: SSLv2/v3 read client hello A.
<MyHub> [02:41:28] TLS: failed in: SSLv2/v3 read client hello A.
<MyHub> [02:41:29] TLS: failed in: SSLv2/v3 read client hello A.
<Domino> .tcl killdcc 25
<MyHub> [02:41:30] TLS: failed in: SSLv2/v3 read client hello A.
<MyHub> Tcl error: invalid idx
<MyHub> [02:41:31] TLS: failed in: SSLv2/v3 read client hello A.
<MyHub> [02:41:32] TLS: failed in: SSLv2/v3 read client hello A.
<MyHub> [02:41:33] TLS: failed in: SSLv2/v3 read client hello A.

So, I can't registered DCC indeces, and must "wait it out" for a timeout.

Both bots have successfully connected to other bots (TLS via STARTTLS).

... if you care.

**Comment by michaelortmann** [comment]
can someone help me understand why the log is clock jumping here?
[02:38:00] Challenging Leaf...
[02:35:02] TLS: failed in: SSLv2/v3 read client hello A.

**Comment by michaelortmann** [comment]
About the dccstat vs. killdcc:

dccstat lists ALL dccs (sockets), see dccutil.c:tell_dcc():

```
  for (i = 0; i < dcc_total; i++) {
[...]
      dprintf(zidx, format, dcc[i].sock, [...]
```

but when killdcc() returns "invalid idx", it doesn't mean, that this specific dcc doesn't exist, as was interpreted by maimizuno,
that dcc of course DOES exist,
but "invalid idx" means, that this idx is **NOT** flagged DCT_VALIDIDX, so killidx wont kill it, but report "invalid idx"  instead.
see tcldcc.c:tcl_killdcc() and dccutil.c:findidx().

**So, i propose, that we change the error message of killdcc to something more meaningful.**

**Or is it a bug instead?**

I mean, the flag DCT_VALIDIDX is described in eggdrop.h as:

```
#define DCT_VALIDIDX  0x00000010        /* valid idx for outputting to
                                         * in tcl
```

but tcl_killdcc doesnt write to idx in any case, it only writes for case DCT_CHAT.

**So, it could be that the socket, maimizuno wanted to kill is not flagged DCT_CHAT and should be killabble and tcl_killdcc could be fixed for this case (a fix here may not be that easy though).**

Would be nice, if tell_dcc() would output FLAGS for idx, but it may be an API change.

**Comment by michaelortmann** [comment]
The following compiler warning may also be related and should be fixed:

```
gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H -I/usr/include -g3 -DDEBUG -DDEBUG_ASSERT -DDEBUG_MEM -DDEBUG_DNS  -c dcc.c
dcc.c: In function ‘timeout_dupwait’:
dcc.c:1477:35: warning: ‘%s’ directive output may be truncated writing up to 323 bytes into a region of size between 67 and 99 [-Wformat-truncation=]
     egg_snprintf(x, sizeof x, "%s!%s", dcc[idx].nick, dcc[idx].host);
                                   ^~
In file included from compat/compat.h:27,
                 from main.h:102,
                 from dcc.c:26:
compat/snprintf.h:58:24: note: ‘snprintf’ output between 2 and 357 bytes into a destination of size 100
 #  define egg_snprintf snprintf
dcc.c:1477:5: note: in expansion of macro ‘egg_snprintf’
     egg_snprintf(x, sizeof x, "%s!%s", dcc[idx].nick, dcc[idx].host);
     ^~~~~~~~~~~~

```

I would prefer to first cleanup compat code, because snprintf is posix 2001 and then, fix the remaining compiler warning.

**Comment by Cizzle** [comment]
To provide a solution to the inability to stop the failing link: use `.unlink MyHub`.
