### ISSUE TITLE
.botattr allows invalid userflags to be used

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#597]
.botattr should only work with valid bot flags- aghilprs. However, 
```
.botattr bbb +v
Bot flags for bbb are now +v.
```

Additionally, +g can only be set if s or p is set... is this desired behavior?

Need to update botattr to check against these flags

**Comment by sshine** [comment]
Can't you make your own bot flags and give them a user-defined meaning? In that case, if a bot is known to have a flag, and the script that gives that flag meaning is temporarily disabled, the flag shouldn't disappear or produce an error.

**Comment by vanosg** [comment]
Custom allowed bot flags are 0-9 and yes, they are supposed to be retained (and not affected by the issue I originally raised). Now since I didn't think to test those, I tried it now...

```
There are no bot flags for foobot.
.botattr foobot +8
Bot flags for foobot are now +3.
.botattr foobot +4
Bot flags for foobot are now +z3.
```

I think I have a little more work to do on this one :)  Thanks for raising the issue.

**Comment by sshine** [comment]
That looks... weird. 3 and z instead of 8 and 4 surely is unexpected?

**Comment by Cizzle** [comment]
> Additionally, +g can only be set if s or p is set... is this desired behavior?

Yes, other desired behavior is the combos +rs, +rp, +rh and +ra not adding (and removing if any was present) those flags and +ha only adding (and keeping) +h.
