### ISSUE TITLE
[1.8.3] kick event handler returns cropped user@host

### ISSUE THREAD

**Issue by wilkowy** [eggheads/eggdrop#598]
Eggdrop 1.8.3. This is a tweaked cut from my other script:

```
proc wilktest:user_kick {nick uhost hand chan whom why} {
	putlog "#DEBUG# user_kick $nick $uhost $hand $chan $whom $why"
	if {[isbotnick $whom]} {
		putlog "#DEBUG# user_kick - me"
		return
	}
	return
}

proc wilktest:chan_mode {nick uhost hand chan mode whom} {
	putlog "#DEBUG# chan_mode $nick $uhost $hand $chan $mode $whom / [isbotnick $whom] [botisop $chan] [wasop $whom $chan] [isop $whom $chan]"
	return
}

bind kick - * wilktest:user_kick
bind mode - *+o* wilktest:chan_mode
```

The problem is that user_kick kick event handler returns invalid $uhost:

[01/17:04:41] [@] wilk!wilk@somehost KICK #***** somebot :no reason
[01/17:04:41] #DEBUG# user_kick wilk wi wilk #***** somebot no reason
[01/17:04:41] #DEBUG# user_kick - me
[01/17:04:41] [!s] JOIN #*****
[01/17:04:41] [s->] JOIN #*****
[01/17:04:41] Adding penalty: 3
[01/17:04:42] [@] somebot!~someident@somehost JOIN :#*****

As you can see the $uhost is "wi" not "wilk@somehost". I've put the same code in 1.6.21 and the uhost is correct there.

**Comment by michaelortmann** [comment]
bug in chan.c gotkick():

strncpyz(uhost, from, sizeof uhost);

sizeof uhost is 8, because uhost is declared as:

char *uhost = buf;
