### ISSUE TITLE
There are two definitions of botrealname...

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#608]
src/mod/server.mod/server.c:  strcpy(botrealname, "A deranged product of evil coders");

src/mod/server.mod/servmsg.c:    strcpy(botrealname, "/msg LamestBot hello");

additionally the second one has static "LamestBot" instead of $nick

**Comment by Cizzle** [comment]
A bot without a realname set in conf deserves to be called a LamestBot, which is also the default in conf.
We gotta init the botrealname to something at module start so why not this; the difference might make for easier debugging?
Closing this, if anyone objects with valid reasons this can be reopened.
