### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#626]
something seems wrong here:

"you may want be"

but im no native english speaker, so its for you to fix. merci!

while at it, the following paragraph has no real meaning, for this is somewhat true with every software, and you could just delete it from README:

  Eggdrop is always being improved and adjusted because there are bugs
  to be fixed and features to be added (if the users demand them and
  they make actually sense). In fact, it existed for several years as
  v0.7 - v0.9 before finally going 1.0. This version of Eggdrop is part
  of the 1.8 tree. A valiant effort has been made to chase down and
  destroy bugs.

**Comment by vanosg** [comment]
Closed by cd2aac3
