### ISSUE TITLE
File PATCH-HOWTO: check ftp link

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#629]
At the end of PATCH-HOWTO the following lines occur:

DOWNLOADING A PATCH
  Some patches for Eggdrop 1.8.x can be found at the following location:
    ftp://ftp.eggheads.org/pub/eggdrop/patches/1.8

pls check, if the ftp directories emptyness is a bug and the directory should be filled,
or if the link from PATCH-HOWTO to that ftp directory i still fine
or if those lines are deprecated and should be removed from PATCH-HOWTO

**Comment by vanosg** [comment]
Closed by 30951fd

**Comment by vanosg** [comment]
Nope.
