### ISSUE TITLE
Better solution to  #605 (NetBSD dns mod)

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#669]
We need to check for and prefer thread-safe res_n* functions over res_* functions, due to some operating systems / resolver implementations deprecated res_* functions and use statp instead of _res.

You can check for your system by `man  res_ninit`

NetBSD has it since Version 6.0
Current Linux has it
Current FreeBSD doesn't have it
Current OpenBSD doesn't have it

Other software projects, like exim, hacked around like this:
https://lists.exim.org/lurker/message/20120506.051703.cecf409b.el.html

Eggdrops dns mod is based on dns.c from mtr. mtr already updated to do what i found above. see version 0.87 of mtr:
```
#ifdef res_ninit
#define MY_RES_INIT() res_ninit(&myres);
#define RES_MKQUERY(a, b, c, d, e, f, g, h, i) \
    res_nmkquery(&myres, a, b, c, d, e, f, g, h, i)
struct __res_state myres;
#else
#define MY_RES_INIT() res_init();
#define RES_MKQUERY(a, b, c, d, e, f, g, h, i) \
    res_mkquery(a, b, c, d, e, f, g, h, i)
#define myres _res
#endif
```

Newest version of mtr switched from using a resolver lib to using os functions. Then async is implemented by forking.

I played around with libunbound https://gitlab.com/mortmann/unbound.mod to see if i could write a tiny libunbound based resolver module for eggdrop. A first tiny test worked. The manpage of libunbound states that async is implemented by threading or forking. The default is unknown (i didnt dig deeper yet). But it could be set via ub_ctx_async(). Maybe via eggdrop setting (feature bloat ;).

Now, after analyzing this, i think, we could also replace dns.mod with the newest code from mtr or our own code which uses system functions and implements async via thread or fork, or supply an unbound lib bases resolver as optional alternative to dns.mod.

**Comment by vanosg** [comment]
Closed by #760
