### ISSUE TITLE
Token 'newline'

### ISSUE THREAD

**Issue by pwpx2** [eggheads/eggdrop#686]
I'm using latest eggdrop version on debian8 system and when i want to run the eggdrop it gives me
-bash: syntax error near unexpected token `newline' error.
what to do ?

**Comment by michaelortmann** [comment]
Hi pwpx2. How exactly did you start eggdrop (full command line)?

**Comment by pwpx2** [comment]
./eggdrop -m <bot.conf>
using a normal user and not root

**Comment by michaelortmann** [comment]
What is latestg version? git? 1.8.3?
Did you install eggdrop by compiling yourself or by installing a debian package (apr).
Can you give me the output of `file eggdrop` and `file bot.conf` please?

**Comment by pwpx2** [comment]
I downloaded the latest .tar release which is 1.8.3 (at least on site)
How to display the outputs?

**Comment by michaelortmann** [comment]
so you did install like ./configure, make...?
by outputs i mean, copy paste here.
for example, i do:
`file eggdrop-1.8.3`
in console and it says:
`eggdrop-1.8.3: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=0869bd46589326ff1b2acbb4fc313ae714236178, with debug_info, not stripped`
thats the kind of output i want to see
btw: for general questions you may also try to get help in #eggdrop on freenode.

**Comment by pwpx2** [comment]
eggdrop-1.8.3: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=1149b05b49ebac2ef45b9c6e9cc355bc4c91e412, not stripped

edit: i just tried again and the eggdrop started running..
dunno why didn't changed anything

**Comment by michaelortmann** [comment]
:)

**Comment by michaelortmann** [comment]
maybe your history shows... try `history` in console. maybe something strange in there. i dunno.
