### ISSUE TITLE
Security flaws when more bots share ...

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#7]
| Trac | Data |
| --: | :-- |
| Ticket | 7 |
| Reported by | TaKeDa |
| Status | new |
| Component | Core |
| Priority | minor |
| Milestone | 1.8.1 |
| Keywords | botnet sharing owner |
| Version | 1.8.0 CVS |

normaly, when you try remove or change host, pass etc. of
permanent owner it isn't possible, but when is sharing you can do it on other 
egg ...
I think, that maybe when you change pass or hosts etc when this information 
will get bot which have this user set to permanent owner the bot shouldnm't 
change anything but eventualy force his setting ...
but when is removing user... maybe bot before do this should ask other bots 
that they agree to do this and then remove ...
actualy the removing and changing password is dangerous ...
Every who is in botnet can change somebody password or remove him from botnet
even when he doesn't have access to bot which this person owns ...

Comment # 1 From Ben Dover 2000-10-26 10:14:11 [reply]

<rant>
I think this is a good example of why things should be discussed on the maillist 
before being added here for action.  Getting user input and discussion I think 
is a critical part of the process and should not be depreciated.  
</rant>

That said, this needs thought and may have other concerns.  [that is why 
involving more in active discussion might help clarify a path to proceed on]

Ultimately permowners are permowners of bots, not permowners of the botnet.  
What if a shell of a slave bot is hacked and someone adds new permowners?  
Should someone on the master bot be able to deflag that illegal user over the 
botnet?  or should the hacked permowner status protected?

I think much of the concerns you express would be solved by the sharing changes 
I proposed a few times before.  See bug # 59.  with the option proposed, the +p 
flag would control this, controlling not only userfile shares, but changes to 
the userfile.  iow, a slave could not change ANY records on an upstream bot.  
changing owner addys and passes are not the only thing that needs protection.

Comment # 2 From TaKeDa 2001-01-15 02:59:43

Yes but this will allow changes only from hub, I need to have possibility to 
change userfile from leaf (because I don't want to give +n access everyone bot 
owner on mine hub) of course hub filters all global flags.

Comment # 3 From TaKeDa 2002-10-02 23:37:26

I already wrote mine own solution to that problem, it is part of
multilevel_sharing (I'm talking about additional flag +s (+r in patches for
eggdrop 1.6.10 and older) which is protecting selected users from changing them
on other bot than main hub)

Comment # 4 From TaKeDa 2002-10-02 23:40:58

this bug is still in current eggdrop

Comment # 5 From Will Buckner 2004-06-10 15:52:15

Moving this to Eggdrop 1.7 product.

**Comment by Pixelz** [comment]
This bug was reported 16 years ago, for Eggdrop 1.4.5 (if I did my math right, possibly 1.6.0 CVS). It has survived at least 3 different bug tracking systems and 22 Eggdrop releases. Now it looks like it's gonna make it through a 23rd one.

If nothing else, this issue is a testament to the great commitment that Eggheads has had for tracking bugs throughout the ages.

Let nobody say that Eggheads is not keeping on top of tracking security flaws.
