### ISSUE TITLE
Non functional code

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#707]
in main.c
since the oldest version here on github, there is code like:
```
	  if (dcc[idx].type && dcc[idx].type->activity)
	    dcc[idx].type->activity(idx, buf, i);
	  else
	    putlog(LOG_MISC, "*",
		   "!!! untrapped dcc activity: type %s, sock %d",
		   dcc[idx].type->name, dcc[idx].sock);
```
later there was traffic stats added and other stuff changed, but the non functional code stays more or less the same.
what i mean is that:
```
if (dcc[idx].type [...]
else
  dcc[idx].type->name [...]
```
looks like in (if) there is a check for null pointer, but then  in (else) the pointer is accessed
it never was a problem, because the error handling was never triggert.
looks like the error handling was built in but never tested.

we should rip it out completely or change it,
in its current shape it does no good for us.

(found with the help of Clang static analyzer)

**Comment by Cizzle** [comment]
That's funny indeed, I'd keep it though and put something alike:
```
putlog(LOG_MISC, "*", "!!! untrapped dcc activity: type %s, sock %d",
       dcc[idx].type ? dcc[idx].type->name : "Unknown", dcc[idx].sock);
```
