### ISSUE TITLE
Check tclchan.c for logic error

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#710]
https://github.com/eggheads/eggdrop/blob/develop/src/mod/channels.mod/tclchan.c#L1518

```
        if (strtol(item[i], &endptr, 10) < 0 || (*endptr)
|| strtol(p, &endptr, 10) < 0 || (*endptr)) {
```

`|| (*endptr) || (*endptr)` is an identical expression

but there may be a logic error

maybe we need some braces to clarify

**Comment by Cizzle** [comment]
Expressions are evaluated from left to right (and only if needed but doesn't matter here). The `strtol` function alters `endptr` which should be checked after every `strtol` evocation. See manpage:
```
If endptr is not NULL, strtol() stores the address of the first invalid character in *endptr.
If there were no digits at all, strtol() stores the original value of nptr in *endptr (and returns 0).
In particular, if *nptr is not '\0' but **endptr is '\0' on return, the entire string is valid.
```

**Comment by michaelortmann** [comment]
yes, i totally missed the strtol(). ty.
