### ISSUE TITLE
Problem Installing Eggdrop 1.8.3

### ISSUE THREAD

**Issue by fahadmehar** [eggheads/eggdrop#724]
I am Installing Eggdrop 1.8.3 and Stuck on this LINE PLEASE HELP 

configure: configuring Eggdrop 1.8.3 
checking for Tcl configuration... configure: error: Can't find Tcl configuration definitions. Use --with-tcl to specify a directory containing tclConfig.sh

**Comment by vanosg** [comment]
Hello fahad,

You need to install tcl. However, we use github issues for bug reports, not support. Please join #eggdrop on freenode for help. Thanks
