### ISSUE TITLE
improve documentation of tcl vs. dcc need-*

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#734]
.chanset does not include {} for need-* settings, Tcl does, might be confusing. Clarify on https://docs.eggheads.org/coreDocs/channels.html maybe.

Found by:  Koragg

**Comment by thommey** [comment]
Could maybe also warn if it starts with a literal '{'?

**Comment by vanosg** [comment]
@thommey  Can you add some words here and I'll include it with what I'm working on now?

**Comment by thommey** [comment]
```
Note: Be aware that the syntax for setting the need- settings is different between Tcl's [channel set] and the dcc .chanset command.
.chanset #chan need-op putmsg NickServ "op #chan"
but
channel set #chan need-op { putmsg NickServ "op #chan" }
```
