### ISSUE TITLE
".help set" format not doing orderly columns anymore

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#745]
`.help set` displays lines containing too long settings not in orderly columns and without space between them, like this example:

`switch-logfiles-atshare-unlinks`

We should rise the length/formatting here, maybe +3 chars would be enough for now. Maybe this also means only displaying 3 instead of 4 settings per row.

**Comment by vanosg** [comment]
Looking at this.. fun fact:
```
ssl-privatekey
ssl-certificate
ssl-privatekey
ssl-certificate
```
 :)
