### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#749]
[... I removed the non-typo marked as fine by Cizzle below ...]

https://github.com/eggheads/eggdrop/blob/develop/src/mod/transfer.mod/language/transfer.german.lang#L63

downloads should be Downloads (uppercase)

benutzer should be Benutzer (uppercase)

Many other stuff in this file is garbage and should be checked and corrected (Line 30?)

**Comment by Cizzle** [comment]
1. Looks fine IMO
2. If only we had a German native speaker.
