### ISSUE TITLE
chanlist minus flag, only one flag can be specified

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#78]
| Trac | Data |
| --: | :-- |
| Ticket | 78 |
| Reported by | Robby- |
| Status | assigned |
| Component | Module: irc.mod |
| Priority | minor |
| Milestone | 1.8.0 |
| Keywords | chanlist |
| Version | 1.8.0 CVS |

The chanlist tcl command works as expected when specifying + (or nothing) with multiple flags to check for, eg: 'chanlist #chan bn'.
This, however, does not work: 'chanlist #chan -bn', and just outputs everyone present, as if no flags had been specified. It only works if only one flag is specified.

**Comment by thommey** [comment]
**Comment by pseudo**
Ok, I'll look into this.

**Comment by vanosg** [comment]
What is the expected output of specifying multiple - flags? This command should be listing users on a channel that match flags stored in the user file. Eggdrop doesn't store '-' flags in the userfile,thus there will never be any matches to a '-' flag.

**Comment by vanosg** [comment]
Ah - specifying a - will list folks that do NOT have that flag. Documentation should be updated to reflect that. 

As for only one mode working, I can't confirm that- this functionality seems to work as an 'and', not an 'or'. 

```
.whois testuser
<testbot> HANDLE                           PASS NOTES FLAGS           LAST
<testbot> testuser                         yes      0 blo             19:42 (#eggdrop)

.tcl chanlist #eggdrop -bo
<testbot> tcl: evaluate (.tcl): chanlist #eggdrop -bo
<testbot> Tcl: userA userB userC

.tcl chanlist #eggdrop -bn
<testbot> Tcl: userA userB userC testuser
```

Recommend clarifying documentation and closing this issue.

**Comment by vanosg** [comment]
chanlist flag matching is nuts- can't figure out what its doing, yet. This is more than a documentation update.

**Comment by Cizzle** [comment]
For me this seems to work like: give all users who lack any of the given flags. Or to say it differently: it hides all users who have all the given flags.
And users = names in channel; flags = eggdrop flags.
So I think it's just docs needing some elaboration.

**Comment by vanosg** [comment]
Cizzle also noted that you have to use the |- syntax to specify looking at channel flags, ie 
```.tcl chanlist #channel |+o```
His explanation of how the - modifier is spot on. Will update docs accordingly... 
...  6 years later.
