### ISSUE TITLE
2 Bugs with -nc

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#787]
`$ ./eggdrop -nc`

**Bug 1:**

The first channel stats should be displayed immediately, not waiting the first 10 secs ?

**Bug 2:**

Status in mode -nc show `-nan%` for Cache hit:

`Online for 00:00 (status mode) - CPU: 00:00.01 - Cache hit: -nan%`

Mode -nt it woks fine.

Meanwhile i compiled eggdrop under FreeBSD 12.0-RC3 with `CFLAGS="-march=native -O2 -g3 -fsanitize=undefined -fstack-protector-all -D_FORTIFY_SOURCE=2 -std=c89 -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=600 -D__BSD_VISIBLE -Wall" ./configure`. It compiles cleanly, no single warning, but `./eggdrop -nc` showed the following in red color: `chanprog.c:347:39: runtime error: division by zero`. Eggdrop doesn't crash it looks more like a warning but should be fixed anyway.

**Comment by vanosg** [comment]
Same bug, two instantiations- nan (not a number) is being generated by the floating-point division by zero, which is a non-terminating error. Good catch
