### ISSUE TITLE
Twitch handling

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#798]
As Twitch gains popularity, it would be good for eggdrop to keep up with that. Right now, there are IRC gateways that connect to twitch servers, which Eggdrop can (somewhat) handle connecting to. However, many features are enabled via CAP, which bastardize the irc protocol by prefixing things like 
```
usermeta:admin=false;registered=true;ssl=true :Nick!ident@host PRIVMSG #channel :Message
```
or 
```
@badges=moderator/1,subscriber/6,sub-gifter/1;color=#FF00FF;display-name=PandaZaiGames;emotes=;flags=;id=74c84ef6-aacc-4baa-9dbb-fc437cf976d9;mod=1;room-id=100460555;subscriber=1;tmi-sent-ts=1544575129253;turbo=0;user-id=74077319;user-type=mod :pandazaigames!pandazaigames@pandazaigames.tmi.twitch.tv PRIVMSG #summerll0ve :Fallout
```
which causes many of the Eggdrop binds to fail. I'd like to look at a few possible solutions (module? config setting? core update?) to handle these deviants of nature. Right now it looks like the CAP requests for tags definitely affects things, maybe membership. 

Possible solutions: 
- add TW-PUB, TW-RAW, etc binds? 
- (via config setting) Preprocess raw messages to strip out any @-prefixed commands and store in a separate variable, available to user via Tcl?
- drink more scotch and ignore it?

There's probably a lot more to do here, as I'm not a twitch expert. Feel free to chime in with other things that could/should be handled.

**Comment by craze** [comment]
This is IRCv3 stuff which isn't really limited to Twitch. I imagine once Eggdrop handles IRCv3 tags in general, the Twitch specific information can easily be handled by user scripts.

I think Eggdrop should be able to look past these tags if present to keep existing binds functioning without requiring any user configuration. Then a new bind similar to RAW, but with IRCv3 information as an extra parameter in the proc, would be useful for custom processing. Could be a string as-is, or an array from the semi-kolon separated data.

Twitch is in my opinion too far from IRC standard to warrant special attention, but generic IRCv3 handling is indeed something worth paying attention to.

CAP tags is indeed what adds this extra stuff while membership is required to receive join/parts from server.

**Comment by vanosg** [comment]
@craze Thanks for the comment! You have some great thoughts in here, and while IRCv3 as a general concept warrants some discussion, CAP is already being implemented. I'm hoping to start working on this particular piece soon, but I wanted to touch base with you and see if you perhaps had any interest in helping in the development of this or related features? Thanks again

**Comment by craze** [comment]
I wouldn't know my way around doing actual programming in this language, but I'll be happy to provide further feedback or insight on Twitch specifics.

**Comment by DooubleTap** [comment]
But ain't Mixer the new thing, since "the one who shall not be named" moved there? :p

**Comment by michaelortmann** [comment]
M$ and OT, lets stick to technical discours :)

Discussion on IRC with Geo resulted in:

Add a net-type for twitch, so **we need to finish #693 first**.

Then exclude /WHOIS for net-type twitch and add CAP requests for twitch (CAP REQ twitch.tv/membership should enable commands like /JOIN), so we need to finish any pending CAP stuff, should there be any.

Twitch seems to suppress a users host at any times, which will limit (most?) eggdrop functionality.

Any twitch code that can be encapsulated, should go into a new twitch.mod module.

**Comment by vanosg** [comment]
Folks, I have a *very* basic connection capability to Twitch ready. Can anyone help me understand some scenarios of how you would use Eggdrop on a Twitch channel? Are there any particular functions you would use, so I can focus on that side first? Thanks!

**Comment by vanosg** [comment]
To Do:
- [x] Not send ISONs
- [x] Not send WHO
- [x] Populate channel list
- [x] Make sure Eggdrop knows it is on channel (fake WHO reply?)
- [x] Confirm JOIN/PARTs work properly
- [x] Request twitch.tv/membership upon join to server (for NAMES)

**Comment by vanosg** [comment]
@craze message tags are merged into develop now, along with the RAWT bind (pause for applause). Are there any particular 'standard' Twitch features or capabilities that Eggdrop should be looking to handle?

**Comment by craze** [comment]
In addition to twitch.tv/membership which subscribes to JOIN/PART events from server, there is twitch.tv/tags which enables the IRCv3 style message tags. 

The long read: https://dev.twitch.tv/docs/irc/guide (includes message flood limits)
Also note that most Twitch commands for a channel are sent as 'privmsg #channel :/command'

**Comment by vanosg** [comment]
Possible functionalities:
- [ ] Rate limiting messages per Twitch restrictions
- [ ] Account authentication
- [ ] Scope tracking (future work: features based on available scopes)
- [ ] Moderation levels (related to scope tracking?)
- [X] Track ROOMSTATE on join
- [x] Track changes in ROOMSTATE
- [X] Log CLEARCHAT use
- [x] Log CLEARMSG
- [ ] Track GLOBALUSERSTATE
- [x] Log bits message
- [ ] Track USERSTATE info of each user as they join (yikes)
- [x] Specifically for USERSTATE, log Subs, Resubs, Gifts, raids and rituals
- [ ] Log tag-msgs for NOTICE command (yikes again)
- [ ] separate actual log messages to language files?
- [x] Log HOSTTARGET
- [ ] Add issub/isvip ?
- [x] Handle whispers
- [ ] Handle RECONNECT
