### ISSUE TITLE
Discuss tcl.m4

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#802]
Discuss and decide how to proceed with tcl.m4. Upstream removed the LIBS macro which we used to determine whether we need -lm for Tcl or not. Upstream also doesn't seem willing to maintain a "list of paths" to tclConfig.sh because it's "not standard". We need to find a way how to find tclConfig.sh in a sane way, overwritable.

**Comment by vanosg** [comment]
#vanosgwasright
