### ISSUE TITLE
eggdrop 1.9.0 can't load modules.

### ISSUE THREAD

**Issue by CryptoSiD** [eggheads/eggdrop#804]
I can't load any module since I recompiled with the latest master branch.

Eggdrop v1.9.0+base (C) 1997 Robey Pointer (C) 2010-2019 Eggheads
--- Loading eggdrop v1.9.0+base (Wed Jan  2 2019)
Listening for telnet connections on ::1:3335 (all).
Listening for telnet connections on ::1:3336 (all).
Can't load modules blowfish: This module requires Eggdrop 1.8.0 or later.
Can't load modules dns: This module requires Eggdrop 1.8.0 or later.
Can't load modules channels: This module requires Eggdrop 1.8.0 or later.
Can't load modules server: This module requires Eggdrop 1.8.0 or later.
Can't load modules ctcp: This module requires Eggdrop 1.8.0 or later.
Can't load modules irc: This module requires Eggdrop 1.8.0 or later.
Can't load modules share: This module requires Eggdrop 1.8.0 or later.
Can't load modules notes: This module requires Eggdrop 1.8.0 or later.
Can't load modules console: This module requires Eggdrop 1.8.0 or later.
Can't load modules uptime: This module requires Eggdrop 1.8.0 or later.
Loading dccwhois.tcl...
Loaded dccwhois.tcl
Userinfo TCL v1.07 loaded (URL BF GF IRL EMAIL DOB PHONE ICQ).
use '.help userinfo' for commands.
Loading netbots.tcl v4.10...
*** WARNING: error found when loading scripts/netbots/botnetop.tcl:
bad type, should be one of: act, away, bcst, bot, chat, chjn, chof, chon, chpt, cron, dcc, die, disc, evnt, filt, link, load, log, nkch, note, time, tls, unld
Ignored masks for channel(s): #Horus #Montreal #respect 
Userfile loaded, unpacking...
You have installed modules but have not selected an encryption
module, please consult the default config file for info.

**Comment by thommey** [comment]
We do plan on releasing 1.9 next, and modules might be incompatible, but right now, everything is still compatible. Reverted the version change for now, we'll have to come up with a better solution when we do introduce an incompatible change. Thanks for the report!

**Comment by ghost** [comment]
> 
> 
> I can't load any module since I recompiled with the latest master branch.
> 
> Eggdrop v1.9.0+base (C) 1997 Robey Pointer (C) 2010-2019 Eggheads
> --- Loading eggdrop v1.9.0+base (Wed Jan 2 2019)
> Listening for telnet connections on ::1:3335 (all).
> Listening for telnet connections on ::1:3336 (all).
> Can't load modules blowfish: This module requires Eggdrop 1.8.0 or later.
> Can't load modules dns: This module requires Eggdrop 1.8.0 or later.
> Can't load modules channels: This module requires Eggdrop 1.8.0 or later.
> Can't load modules server: This module requires Eggdrop 1.8.0 or later.
> Can't load modules ctcp: This module requires Eggdrop 1.8.0 or later.
> Can't load modules irc: This module requires Eggdrop 1.8.0 or later.
> Can't load modules share: This module requires Eggdrop 1.8.0 or later.
> Can't load modules notes: This module requires Eggdrop 1.8.0 or later.
> Can't load modules console: This module requires Eggdrop 1.8.0 or later.
> Can't load modules uptime: This module requires Eggdrop 1.8.0 or later.
> Loading dccwhois.tcl...
> Loaded dccwhois.tcl
> Userinfo TCL v1.07 loaded (URL BF GF IRL EMAIL DOB PHONE ICQ).
> use '.help userinfo' for commands.
> Loading netbots.tcl v4.10...
> *** WARNING: error found when loading scripts/netbots/botnetop.tcl:
> bad type, should be one of: act, away, bcst, bot, chat, chjn, chof, chon, chpt, cron, dcc, die, disc, evnt, filt, link, load, log, nkch, note, time, tls, unld
> Ignored masks for channel(s): #Horus #Montreal #respect
> Userfile loaded, unpacking...
> You have installed modules but have not selected an encryption
> module, please consult the default config file for info.
