### ISSUE TITLE
Issue with [timer]

### ISSUE THREAD

**Issue by wilkowy** [eggheads/eggdrop#808]
Code: `.tcl timer 1 [list putlog "done 1m"] ; timer 2 [list putlog "done 2m"] ; utimer 60 [list putlog "done 60s"] ; utimer 120 [list putlog "done 120s"] ; putlog "start"`

Result:
```
[06/01:19:42] start
Tcl:
[06/01:20:00] done 1m
[06/01:20:41] done 60s
[06/01:21:00] done 2m
[06/01:21:41] done 120s
```

Is that a correct behaviour? The minute [timer] executes not after 1 minute since execution, but on the first full minute (:00) and then every minute from that. [utimer] works ok. The docs does not say about such weird behaviour.

The ban timer is also affected, but a bit different (better):

`.tcl newchanban #***** "xxx!yyy@zzz" "test" "no reason" 1 "sticky"`

```
01:33:37 -!- mode/#***** [+b xxx!yyy@zzz] by *****
01:35:01 -!- mode/#***** [-b xxx!yyy@zzz] by *****
01:35:27 -!- mode/#***** [+b xxx!yyy@zzz] by *****
01:37:02 -!- mode/#***** [-b xxx!yyy@zzz] by *****
```

As you can see it waits till the full minute and than it counts an 1 minute expiration.

The ban issue is acceptable as it waits at least minute, but [timer] can execute just few seconds after calling it - this makes them quite useless.

At least you should fix the docs to mention this issue as now it states "Description: executes the given Tcl command after a certain number of minutes have passed.". **After** and that means first interval as well.

It happens on 1.8.4 and 1.6.21.

**Comment by wilkowy** [comment]
OK, now I see in code `core_secondly`/`core_minutely` that [timer]s are broken by-design and are useless for shorter intervals (1 minute timer is always less than 60 seconds).

**Comment by vanosg** [comment]
@wilkowy you are indeed correct on that intentional function of the timer command. Does that ^ doc clarify things? Thanks for reporting, sorry it took so long to tweak such a quick but important fix!

**Comment by wilkowy** [comment]
Yes, this clarifies things. The website help still has to be updated however.

So why it works like it works? The minute timer could just create a second timer for the remaining seconds.
OK, compatibility issues then. But the command can be upgraded with a prefix/suffix to minutes value and the old timer would work the same, but new behaviour could be implemented.

Why ban timer behaves differently? Why not wait a minute on top of the remaining seconds to full time? The other solution could be to implement a similar tweak as above, but the scripter can select the required behaviour: up to 1 minute or 1 minute with acceptable remaining few seconds.
