### ISSUE TITLE
ZNC | OnChan | BotOnChan

### ISSUE THREAD

**Issue by TimerWolf** [eggheads/eggdrop#824]
A while ago the nasty long bug "onchan/botonchan" where fixed.

Sedley this did not work for the bot when its connected whit ZNC maybe its its same problem whit every bouncer i don´t know as i have not test it.

**Comment by vanosg** [comment]
Hello antonstarlid,
 Can you provide details as to what the exact problem is that you are encountering? Log files would greatly help, as well as version information and anything else you think might provide additional information to help. Thank you!

**Comment by TimerWolf** [comment]
Well i don´t see why logfiles would be needed its very easy to debug i think, i have not use the function for ages as it not working as expected yet its a very good one.

Well i think  that it strange that you ask this, as it only have two results the "bot/user" is on the channel or not and return "0" or "1".

I think the problem is when the ZNC itself disconnect and the reconnect to the server, while to bot don´t as its always connected to ZNC and has nothing to do whit the connection between the IRC and ZNC......

**Comment by vanosg** [comment]
So that's the question- please tell us what isn't working. Just saying "it isn't working" doesn't help us identify the problem. Providing additional information as to what exactly isn't working under what conditions is needed; you haven't clearly stated this to us yet so it will be difficult to do anything, as we're not sure what you're specifically referencing.

**Comment by TimerWolf** [comment]
My function did spam when it not should as it was trigged by the "onchan/botonchan" so it did tell that the "bot/user" not was in channel when it actually is in the channel.

I would think that a ZNC whit some emulated disconnects and reconnects would trigger the problem by it self.

By the way, the functions as i remember it works fine in the start its after a while (no special time) it start to give wrong results and that would be good for my theory that it happens on disconnects/reconnects on the bouncer.

I have setup a test script now to see if i can get the problem appears again.
