### ISSUE TITLE
telnet connection

### ISSUE THREAD

**Issue by burakataoglu** [eggheads/eggdrop#880]
hello,

have problem on telnet connection.

idk why delay the first step (auth)

when i try to connect telnet, i need to wait like 5~15 seconds to see "Please enter your nickname"

**Comment by burakataoglu** [comment]
on latest stable 1.8.4

**Comment by vanosg** [comment]
Hi, we use Github is for bug reporting, not troubleshooting, thanks. Please ask your question on #eggheads on Freenode

**Comment by burakataoglu** [comment]
that isnt bug?
