### ISSUE TITLE
assoc.mod/assoc.c:325: bad test ?

### ISSUE THREAD

**Issue by dcb314** [eggheads/eggdrop#907]
assoc.c:325:20: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op]

Source code is

  if ((chan > 0) || (chan < GLOBAL_CHANS)) {

maybe better code:

  if ((chan > 0) && (chan < GLOBAL_CHANS)) {

**Comment by vanosg** [comment]
Hi dbd314, thanks for reporting this! Yep, I think you're right- I'll dig into this a more in a bit to confirm what it's actually supposed to be doing, but that does seem a little pointless as written, doesn't it? :)
