### ISSUE TITLE
missing ieee doesn't kill configure

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#927]
```
checking for main in -lieee... no
```
leads to
```
gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H -I/usr/include/tcl8.5 -g3 -DDEBUG -DDEBUG_ASSERT -DDEBUG_MEM -DDEBUG_DNS -o ../eggdrop bg.o botcmd.o botmsg.o botnet.o chanprog.o cmds.o dcc.o dccutil.o dns.o flags.o language.o match.o main.o mem.o misc.o misc_file.o modules.o net.o rfc1459.o tcl.o tcldcc.o tclhash.o tclmisc.o tcluser.o tls.o userent.o userrec.o users.o  -L/usr/lib/x86_64-linux-gnu -ltcl8.5  -lpthread -lieee -lm -lssl -lcrypto -ldl  -lresolv md5/md5c.o compat/*.o `cat mod/mod.xlibs`
/usr/bin/ld: cannot find -lieee
```
Should this auto-terminate?

**Comment by michaelortmann** [comment]
i guess the -lieee is comming from tcl, which was linked to lieee. now i wonder, why eggdrops configure doesnt detect it. is tcl working on that platform? which platform is it anyway?

**Comment by vanosg** [comment]
This particular issue seemed to be a result of a debian upgrade. I'm not totally sure of the how or why, but in case someone stumbles across this in a google search, the issue is suspected to be related to an issue with the Tcl upgrade between distros. Removing the older Tcl installation and reinstalling the newer has, anecdotally, fixed this issue.

**Comment by vanosg** [comment]
Follow-up to #801

**Comment by thommey** [comment]
Mixing debian stretch and buster. Recommended solution: upgrade to buster. See #801
