### ISSUE TITLE
Remove $HOME/.oidentd.conf after successful connection to server

### ISSUE THREAD

**Issue by TehPeGaSuS** [eggheads/eggdrop#942]
Right now, on develop branch, eggdrop has support for oidentd.
The problem is that the bot creates a `$HOME/oidentd.conf` which will be read by the oidentd daemon to reply to identd queries from the IRC server.
So far, so good. The problem is that if any other kind of bot that doesn't have support for this will end up having the same ident has the eggdrop.
The solution would be to remove the `$HOME/oidentd.conf` after the bot successfully connected to the IRC server.

**Comment by michaelortmann** [comment]
Thank you. Good idea. got001() in servmsg.c must be patched, so that ident.mod can remove oidentd.conf upon successful completion of the IRC registration process.

**Comment by michaelortmann** [comment]
There is already `check_tcl_event("init-server");` in `got001()`. So we can use this event in `init.mod` and dont have to modify `servmsg.c`
