### ISSUE TITLE
longer info lines

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#96]
| Trac | Data |
| --: | :-- |
| Ticket | 96 |
| Reported by | @thommey |
| Status | assigned |
| Component | Module: channels.mod |
| Priority | critical |
| Milestone | 1.8.0 |
| Version | 1.8.0 CVS |

Kiril suggested a longer info line length.

**Comment by thommey** [comment]
**Comment by @Pixelz**
This has already been committed to 1.8.0 CVS, but after the fact it was discovered that it might break sharing. Someone needs to test this, and possibly come up with a better plan if it does.

**Comment by vanosg** [comment]
Testing this out, here's what I am seeing, when receiving a shared file with an info line length >80:

```
<NoInfoLimit> My name is NoInfoLimit and I am running eggdrop v1.8.0+infiniteinfo, on Linux 3.13.0-53-generic.
<NoInfoLimit> .whois testuser
<NoInfoLimit> HANDLE                           PASS NOTES FLAGS           LAST
<NoInfoLimit> testuser                         no       0 -               never (nowhere)
<NoInfoLimit>.info aaaaaaaaasssssssddddddffffffggggggghhhhhhhjjjjjjkkkkkkkllllllllpppppppp
<NoInfoLimit> Your default info is now: aaaaaaaaasssssssddddddffffffggggggghhhhhhhjjjjjjkkkkkkkllllllllpppppppp
```

_**Note- that is ~100 chars in the info line ^^^ *_*

```
<NoInfoLimit> .whois testuser
<NoInfoLimit> HANDLE                           PASS NOTES FLAGS           LAST
<NoInfoLimit> testuser                         no       0 -               18:47 (partyline)
<NoInfoLimit>   INFO: aaaaaaaaasssssssddddddffffffggggggghhhhhhhjjjjjjkkkkkkkllllllllpppppppp
```

Now, lets share with a 1.6.21 bot named InfoLimit

```
<NoInfoLimit> .link infolimit
*** Linked to InfoLimit
<NoInfoLimit> Creating resync buffer for InfoLimit
<NoInfoLimit> Sending user file send request to InfoLimit
<NoInfoLimit> Completed userfile transfer to InfoLimit.
```

Now on InfoLimit:

```
<InfoLimit> My name is InfoLimit and I am running eggdrop v1.6.21, on Linux 3.13.0-53-generic.
<InfoLimit> .whois testuser
<InfoLimit> HANDLE                           PASS NOTES FLAGS           LAST
<InfoLimit> testuser                         no       0 -               18:47 (partyline)
<InfoLimit> INFO: aaaaaaaaasssssssddddddffffffggggggghhhhhhhjjjjjjkkkkkkkllllllllpppppppp
```

Test case successful!

This doesn't seem to be an issue when adding an info line when the bots are already linked and sharing, as the info line doesn't seem to replicate throughout the botnet except on a re-sharing of files:

```
<NoInfoLimit> .info aaaaaaaaaasssssssssddddddddfffffffggggggghhhhhhhjjjjjjjkkkkkkklllllllppppppp
<NoInfoLimit> Your default info is now: aaaaaaaaaasssssssssddddddddfffffffggggggghhhhhhhjjjjjjjkkkkkkklllllllppppppp
```

```
<InfoLimit> .whois testuser
<InfoLimit> HANDLE                           PASS NOTES FLAGS           LAST
<InfoLimit> testuser                         no       0 -               19:10 (@testbot)
```

I tried with a <80 byte info line, and that too doesn't replicate, so I think this is actually a separate bug.  But, thats for another thread- I don't see any issues with info limits right now. Happy to test other functionalities upon request.
