### ISSUE TITLE
more options/consistency with file-names (specifically .botchk)

### ISSUE THREAD

**Issue by dchmelik** [eggheads/eggdrop#989]
In eggdrop.conf one can specify their file-names (eggdrop.user, eggdrop.chan, eggdrop.pid, etc.) _except_ eggdrop.botchk.

Though (though not common IRC style) most my IRC bots have capitalized nicknames, for command-line ease-of-use, I almost never capitalize file-names.  However when you run autobotchk (as one shell provder recommends:  cd ~/thedirectoryyoureggdropfilesarein/scripts ; chmod 700 autobotchk ; ./autobotchk yourbotsname.conf -dir /home/yourusername/thedirectoryyoureggdropfilesarein -noemail) it doesn't let you specify .botchk rather than assuming you want it based on IRC nickname rather than, for example, similar to the eggdrop.pid.  So I'm often editing/renaming my *.botchk, often leading to errors until I get them all edited/named right (not just file-name, but crontab, things inside that may not match corresponding eggdrop.conf.)

Couldn't we have a way to specify eggdrop.botchk just like the rest of a bot's files?

(improvement/feature request)

**Comment by vanosg** [comment]
Hi dchmelik,

  Could you provide an example of specific values that you need to change to get this to work? autobotchk is a fairly robust stand-alone script, designed to just 'set and forget' - it shouldn't require any editing on your part.

**Comment by dchmelik** [comment]
Other than autobotchk assuming I want capitalized 'Eggdrop.botchk' maybe its only other assumption was capitalized pid.Eggdrop (unless it gets that from eggdrop.conf, but if does, should name eggdrop.botchk similarly.)... of course, I also edit line '# Eggdrop.botchk (generated on <date>)' so don't get confused if ever looking at that file (though the comment doesn't affect functionality, just should be generated same way its file-name is.)

**Comment by vanosg** [comment]
I'm still a little foggy on what your question is, but I hope this will answer any questions you have- Eggdrop creates a .botchk file based on the botnet-nick set in the config file you give to the autobotchk script, in the format $botnet-nick.botchk . It then creates a pid file using that same name, i the format pid.$botnet-nick . If bot-net nick is not specified, then the userfile name is instead used for both those filenames. In theory, you should be able to edit the name of the .botchk file just fine, as long as you edit any corresponding cron entry as well. I'm not sure what other issue you're encountering here until you can tell me what specific values you need to change if you rename the .botchk file itself, which I think is what your root question is?

 (And in the interest of thoroughness, I'm assuming that is a typo in "Eggdrop.autobotchk" above? There is no .autobotchk file created)

**Comment by dchmelik** [comment]
(yes; edited above: Eggdrop.botchk) Clearly there may be several issues.

People may name eggdrop.pid in eggdrop.conf; autobotchk should use that, right? (even if not pid.$botnet-nick)
If one names pid.eggdrop there, there's little/no reason eggdrop.botchk should be named in different style.

**Comment by vanosg** [comment]
Sorry, I guess I didn't explicitly state it- autobotchk looks for the pidfile in eggdrop.conf, and if it is not set, then it uses the logic I described above. Again, if you're seeing different behavior, please paste a log. If you wish to discuss the approach in general, please join #eggdrop on Freenode to have a technical discussion. But without an error, there isn't much more to do here

**Comment by dchmelik** [comment]
I'm not seeing different behaviour (unless I forgot to set eggdrop.pid so that ended up different than I wanted) so it's not an error report, just report/request about how this case could have some situations be less confusing; it's not complex enough I'd say anything other than originally.  Maybe I'll come to freenode later.
