### ISSUE TITLE
Userfile Sharing failed

### ISSUE THREAD

**Issue by Manuelchen86** [eggheads/eggdrop#993]
User file sharing does not work in versions 1.8.3 - 1.8.4 and 1.9.0, all protocols and other issues have already been received by Geo.

https://paste.ubuntu.com/p/Qh86r3grzG/ @ Protocol

https://paste.ubuntu.com/p/skPRPzpMTm/ In version 1.8.2

Edit:
I now basically exclude firewall and eggdrop configuration.

Everything important is now in the Eggdrop configuration and in the firewall (iptables) all important ports and port ranges are also released.

**Comment by vanosg** [comment]
Hi @Manuelchen86,
  No other users report issues with userfile sharing that look like this. Additionally, the iptables logs you pasted in #eggdrop show that you do not have a port range open for the userfile transfer to take place (defined by reserved-portrange in the config). You can continue to work with people in #eggdrop, or perhaps join an OS help channel who can help you configure iptables, but at this time this does not appear to be a bug with Eggdrop. We can re-open this if something proves otherwise. Please continue troubleshooting in the help channel. Thank you!

**Comment by Manuelchen86** [comment]
But there is a bug with the eggdrop.

Geo <notifications@github.com> schrieb am Mo., 22. Juni 2020, 02:20:

**Comment by Manuelchen86** [comment]
The port ranges thus comply with the iptables rules

Manuel Budach <m.budach99@gmail.com> schrieb am Mo., 22. Juni 2020, 02:29:

**Comment by Manuelchen86** [comment]
`Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
Bogus      all  --  anywhere             anywhere            
Always     all  --  anywhere             anywhere            
Banned     all  --  anywhere             anywhere            
f2b-sshd   all  --  anywhere             anywhere            
Allow      all  --  anywhere             anywhere            

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
Bogus      all  --  anywhere             anywhere            
Always     all  --  anywhere             anywhere            
Banned     all  --  anywhere             anywhere            
Allow      all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain Allow (2 references)
target     prot opt source               destination         
Friend     icmp --  anywhere             anywhere             icmp echo-request
ACCEPT     icmp --  anywhere             anywhere             icmp any limit: avg 1/sec burst 5
DROP       icmp --  anywhere             anywhere             icmp any
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ftp-data
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ftp
**ACCEPT     tcp  --  anywhere             anywhere             multiport dports 1024:65535**
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:smtp
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:submission
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:pop3
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:auth
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:imap2
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:imaps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:pop3s
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:mysql
ACCEPT     tcp  --  anywhere             anywhere             multiport dports 5001:5030
ACCEPT     tcp  --  anywhere             anywhere             multiport dports ircd:6669
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:6670
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:6671
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:7778
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:9000
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable

Chain Always (2 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
Friend     all  --  anywhere             anywhere            

Chain Banned (2 references)
target     prot opt source               destination         

Chain Bogus (2 references)
target     prot opt source               destination         
DROP       tcp  --  anywhere             anywhere             tcp flags:FIN,SYN/FIN,SYN
DROP       tcp  --  anywhere             anywhere             tcp flags:SYN,RST/SYN,RST
DROP       all  --  169.254.0.0/16       anywhere            
DROP       all  --  172.16.0.0/12        anywhere            
DROP       all  --  192.0.2.0/24         anywhere            
DROP       all  --  192.168.0.0/16       anywhere            
DROP       all  --  10.0.0.0/8           anywhere            
DROP       all  --  127.0.0.0/8          anywhere            

Chain Friend (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain f2b-sshd (1 references)
target     prot opt source               destination         
REJECT     all  --  203.156.205.59       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  185.97.118.19        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  ec2-15-222-236-91.ca-central-1.compute.amazonaws.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  79.120.102.34        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  host-217-141-152-174.business.telecomitalia.it  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  197.234.193.46       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  117.33.225.111       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  222.186.52.131       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  140.143.88.129       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  104.248.182.179      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  shinracorp.fr        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  ggp68.internetdsl.tpnet.pl  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  ns329327.ip-5-135-161.eu  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  208-86-213-15.cashtn.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  cde66.codedukeofcode.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  159.89.114.40        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  128.199.176.254      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  190.44.200.170.estatic.cantv.net  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  45.77.46.173.vultr.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  134.122.111.162      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  106.13.233.150       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  140.139.69.34.bc.googleusercontent.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  191.ip-51-178-29.eu  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  2.58.228.192         anywhere             reject-with icmp-port-unreachable
REJECT     all  --  204.sub168.pika.net.id  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  140.143.137.170      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  ip8.ip-144-217-19.net  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  pool-221-10-123-181.telecel.com.py  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  189-110-107-175.dsl.telesp.net.br  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  222.239.124.19       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  static-18.58.93.111-tataidc.co.in  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  94-237-56-104.uk-lon1.upcloud.host  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  197.ip-51-91-250.eu  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  103.253.69.38        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  150.136.102.101      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  115.ip-51-75-126.eu  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  223.240.80.31        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  107.132.88.42        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  116.236.251.214      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  167.71.192.77        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  mail.gss.ru          anywhere             reject-with icmp-port-unreachable
REJECT     all  --  159.203.133.182      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  106.54.208.123       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  180.66.207.67        anywhere             reject-with icmp-port-unreachable
`

**Comment by Manuelchen86** [comment]
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
Bogus      all  --  anywhere             anywhere            
Always     all  --  anywhere             anywhere            
Banned     all  --  anywhere             anywhere            
f2b-sshd   all  --  anywhere             anywhere            
Allow      all  --  anywhere             anywhere            

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
Bogus      all  --  anywhere             anywhere            
Always     all  --  anywhere             anywhere            
Banned     all  --  anywhere             anywhere            
Allow      all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain Allow (2 references)
target     prot opt source               destination         
Friend     icmp --  anywhere             anywhere             icmp echo-request
ACCEPT     icmp --  anywhere             anywhere             icmp any limit: avg 1/sec burst 5
DROP       icmp --  anywhere             anywhere             icmp any
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ftp-data
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ftp
**ACCEPT     tcp  --  anywhere             anywhere             multiport dports 1024:65535**
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:smtp
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:submission
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:pop3
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:auth
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:imap2
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:imaps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:pop3s
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:mysql
ACCEPT     tcp  --  anywhere             anywhere             multiport dports 5001:5030
ACCEPT     tcp  --  anywhere             anywhere             multiport dports ircd:6669
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:6670
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:6671
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:7778
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:9000
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable

Chain Always (2 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
Friend     all  --  anywhere             anywhere            

Chain Banned (2 references)
target     prot opt source               destination         

Chain Bogus (2 references)
target     prot opt source               destination         
DROP       tcp  --  anywhere             anywhere             tcp flags:FIN,SYN/FIN,SYN
DROP       tcp  --  anywhere             anywhere             tcp flags:SYN,RST/SYN,RST
DROP       all  --  169.254.0.0/16       anywhere            
DROP       all  --  172.16.0.0/12        anywhere            
DROP       all  --  192.0.2.0/24         anywhere            
DROP       all  --  192.168.0.0/16       anywhere            
DROP       all  --  10.0.0.0/8           anywhere            
DROP       all  --  127.0.0.0/8          anywhere            

Chain Friend (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain f2b-sshd (1 references)
target     prot opt source               destination         
REJECT     all  --  203.156.205.59       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  185.97.118.19        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  ec2-15-222-236-91.ca-central-1.compute.amazonaws.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  79.120.102.34        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  host-217-141-152-174.business.telecomitalia.it  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  197.234.193.46       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  117.33.225.111       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  222.186.52.131       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  140.143.88.129       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  104.248.182.179      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  shinracorp.fr        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  ggp68.internetdsl.tpnet.pl  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  ns329327.ip-5-135-161.eu  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  208-86-213-15.cashtn.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  cde66.codedukeofcode.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  159.89.114.40        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  128.199.176.254      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  190.44.200.170.estatic.cantv.net  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  45.77.46.173.vultr.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  134.122.111.162      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  106.13.233.150       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  140.139.69.34.bc.googleusercontent.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  191.ip-51-178-29.eu  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  2.58.228.192         anywhere             reject-with icmp-port-unreachable
REJECT     all  --  204.sub168.pika.net.id  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  140.143.137.170      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  ip8.ip-144-217-19.net  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  pool-221-10-123-181.telecel.com.py  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  189-110-107-175.dsl.telesp.net.br  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  222.239.124.19       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  static-18.58.93.111-tataidc.co.in  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  94-237-56-104.uk-lon1.upcloud.host  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  197.ip-51-91-250.eu  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  103.253.69.38        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  150.136.102.101      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  115.ip-51-75-126.eu  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  223.240.80.31        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  107.132.88.42        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  116.236.251.214      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  167.71.192.77        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  mail.gss.ru          anywhere             reject-with icmp-port-unreachable
REJECT     all  --  159.203.133.182      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  106.54.208.123       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  180.66.207.67        anywhere             reject-with icmp-port-unreachable
```
