### ISSUE TITLE
Fails to open dcc port (compiles all fine @ ebbd70c)

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#996]
Seems to be a conflict with prefer ipv6
even when you fall back to prefer ipv6 0
it still won't bind any address for the telnet

'.jump'
'[15:29:32] #-HQ# jump'
'Jumping servers......'
'[15:29:32] Trying server 10.0.3.15:6666'
'[15:29:32] Ident error: could not bind socket port 113.'
'[15:29:32] Failed connect to 10.0.3.15 (Address family not supported by protocol)'

'.jump ::1 6666'
'[15:30:00] #-HQ# jump ::1 6666'
'Jumping servers......'
'[15:30:01] Trying server [::1]:6666'
'[15:30:01] Ident error: could not bind socket port 113.'
'[15:30:01] Failed connect to ::1 (Operation now in progress)'

'[16:34:36] -> [eggie] CHAT'
'[16:34:37] [eggie ERROR reply]: no telnet port'

'[15:39:22] #-HQ# dccstat'
'IDX ADDR                                     + PORT NICK      TYPE  INFO'
'--- ---------------------------------------- ------ --------- ----- ---------'
'5   8.8.8.8                                       0 (dns)     dns   (ready)'
'1   10.0.3.15                                     0 -HQ       chat  flags: cptEp/0'
'7   127.0.0.1                                  6668 (server)  serv  (lag: 0)'

**Comment by vanosg** [comment]
Hi @grumpy-creator 
  Can you provide a little more context for each of those log pastes? What activity are you expecting to see that you aren't? What are the settings you are using that generate those logs? Thank you!

**Comment by ghost** [comment]
Hey @vanosg 
I just downloaded and installed the latest git version, couldn't get it to listen on any ip address.
But i think this has just been fixed with last update

**Comment by vanosg** [comment]
Great, thanks!
